(function(g){
'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg=d3.select('#graph'),world=d3.select('#world'),ctx=document.createElement('canvas').getContext('2d');
const measure=(t,font=14,weight=400)=>{ctx.font=`${weight} ${font}px system-ui`;return ctx.measureText(t).width;};
let catalog,scopes,m,L,projection,selected,transform=d3.zoomIdentity,layoutMs,scope,mini,builds=0;
const zoom=d3.zoom().scaleExtent([.02,4]).on('zoom',e=>{transform=e.transform;world.attr('transform',transform);$('#zoom-value').textContent=Math.round(transform.k*100)+'%';updateMini();});svg.call(zoom).on('dblclick.zoom',null);
function bounds(){const p=L.plans.get(m.root.key);return{x0:p.left-8,y0:-8,x1:p.right+8,y1:p.height+8};}
function camera(b,max=1.3){const r=$('#graph').getBoundingClientRect(),available={x:24,y:62,w:r.width-48,h:r.height-112},k=Math.min(max,available.w/(b.x1-b.x0),available.h/(b.y1-b.y0));svg.call(zoom.transform,d3.zoomIdentity.translate(available.x+available.w/2-(b.x0+b.x1)/2*k,available.y+available.h/2-(b.y0+b.y1)/2*k).scale(k));}
function fit(){camera(bounds());$('#status').textContent=`Fit All · ${(14*transform.k).toFixed(1)} px Topic text`;}
function focusTopic(key=selected){const n=L.byKey.get(key);if(n?.data.type!=='topic')return;select(key);camera({x0:n.x-n.width/2-30,x1:n.x+n.width/2+30,y0:n.y-36,y1:n.y+n.height+36},16/14);$('#status').textContent='Topic Focus · full title';}
function fitSubtree(key=selected||m.root.key){let n=L.byKey.get(key);if(n?.data.type==='topic')n=L.byKey.get(n.parent);if(n){camera(n.subtreeBounds);$('#status').textContent='Fit subtree · '+n.data.title;}}
function ancestors(n){const a=[];while(n){a.unshift(n);n=m.parent(n);}return a;}
function select(key){selected=key;const n=m.nodes.get(key);world.selectAll('.node').classed('selected',d=>d.key===key);const chain=new Set(ancestors(n).map(a=>a.key));world.selectAll('.taxonomy').classed('selected-path',d=>chain.has(d.parent)&&d.children.some(k=>chain.has(k)));inspect();}
function inspect(){const n=m.nodes.get(selected)||m.root;$('#inspector-drawer').hidden=false;const exact=n.type!=='context';
 $('#inspector').innerHTML=`<h2>${esc(n.title)}</h2><p>${esc(n.key)}</p><div><span class="badge">${n.type==='context'?'Presentation only':n.scopeRole==='context'?'Context Category':scope.scope_type==='course'?'Course membership':scope.scope_type==='stage'?'Stage requirement':'Project requirement'}</span>${n.is_learned?'<span class="badge personal">Learned</span>':''}${n.is_verified?'<span class="badge personal">Verified</span>':''}</div><p class="path">${ancestors(n).map(a=>`<button class="path-button" data-key="${a.key}">${esc(a.title)}</button>`).join(' → ')}</p><p>${n.type==='category'?`${n.leafKeys.length} Topics under this physical owner. ${n.scopeRole==='context'?'Included for taxonomy context only.':'Explicit Category membership.'}`:n.type==='context'?'View context only; this is not a Knowledge Category.':'Full title retained. Requirement and personal state are independent.'}</p>${exact?`<a id="global-link" target="_blank" href="global.html?key=${encodeURIComponent(ScopeProjection.globalTarget(projection,n.key))}">Show in Global ↗</a><p>Taxonomy memberships</p>${n.memberships.map(k=>`<button class="path-button" data-key="${k}">${esc(m.nodes.get(k)?.title||k)}</button>`).join('')}`:''}${n.type==='category'?`<p>Topics connected through taxonomy</p>${n.taxonomyTopicKeys.map(k=>`<button class="path-button" data-key="${k}">${esc(m.nodes.get(k).title)}</button>`).join('')}`:''}<div class="actions"><button id="read-selected">${n.type==='topic'?'Topic Focus':'Fit subtree'}</button></div>`;
 $('#inspector').querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>select(b.dataset.key));$('#read-selected').onclick=()=>n.type==='topic'?focusTopic(n.key):fitSubtree(n.key);
}
function render(){world.selectAll('*').remove();
 world.append('g').selectAll('path').data(L.connectorSegments).join('path').attr('class',d=>'taxonomy depth-'+d.depth).attr('d',d=>d.d);
 world.append('g').selectAll('rect').data(L.trays).join('rect').attr('class','tray-surface').attr('x',d=>d.x).attr('y',d=>d.y).attr('width',d=>d.width).attr('height',d=>d.height).attr('rx',4);
 const nodes=world.append('g').selectAll('g').data(L.nodes).join('g').attr('class',n=>`node ${n.data.type} depth-${n.depth} ${n.data.scopeRole==='context'?'context-category':''} ${n.data.is_learned?'learned':''}`).attr('data-key',n=>n.key).attr('transform',n=>`translate(${n.x-n.width/2},${n.y})`).attr('tabindex',0).attr('role','button').attr('aria-label',n=>n.data.title).on('click',(_,n)=>select(n.key)).on('dblclick',(_,n)=>n.data.type==='topic'?focusTopic(n.key):fitSubtree(n.key)).on('keydown',(e,n)=>{if(e.key==='Enter'){e.preventDefault();select(n.key);}if(e.key===' '){e.preventDefault();n.data.type==='topic'?focusTopic(n.key):fitSubtree(n.key);}});
 nodes.append('rect').attr('class','card').attr('width',n=>n.width).attr('height',n=>n.height).attr('rx',n=>n.data.type==='topic'?3:5);
 nodes.filter(n=>n.data.scopeRole==='explicit').append('rect').attr('class','scope-stripe').attr('x',0).attr('y',5).attr('width',2).attr('height',n=>n.height-10);
 nodes.each(function(n){const group=d3.select(this),topic=n.data.type==='topic';if(topic){group.append('circle').attr('class','core').attr('cx',12).attr('cy',n.height/2).attr('r',3.5);if(n.data.is_verified)group.append('circle').attr('class','ring').attr('cx',12).attr('cy',n.height/2).attr('r',6);}
  group.selectAll('text.label').data(n.lines).join('text').attr('class','label').attr('x',topic?24:22).attr('y',(_,i)=>(topic?6:8)+n.font+i*n.line).style('font-size',n.font+'px').text(s=>s);
  if(!topic)group.append('text').attr('class','category-coverage').attr('x',22).attr('y',n.height-7).text(`${n.data.taxonomyTopicKeys.length} Topics · ${n.data.type==='context'?'view':n.data.scopeRole}`);
 });
 const b=bounds(),k=Math.min(172/(b.x1-b.x0),104/(b.y1-b.y0));mini={k,x:90-(b.x0+b.x1)/2*k,y:56-(b.y0+b.y1)/2*k};const mm=d3.select('#minimap');mm.selectAll('*').remove();mm.selectAll('rect').data(L.nodes).join('rect').attr('x',n=>mini.x+(n.x-n.width/2)*k).attr('y',n=>mini.y+n.y*k).attr('width',n=>Math.max(1,n.width*k)).attr('height',n=>Math.max(1,n.height*k));mm.append('rect').attr('class','mini-viewport');
}
function updateMini(){if(!mini)return;const r=$('#graph').getBoundingClientRect();d3.select('.mini-viewport').attr('x',mini.x-transform.x/transform.k*mini.k).attr('y',mini.y-transform.y/transform.k*mini.k).attr('width',r.width/transform.k*mini.k).attr('height',r.height/transform.k*mini.k);}
function load(s){scope=s;selected=null;$('#inspector-drawer').hidden=true;const start=performance.now();({m,L,projection}=ScopePyramid(s.scope_type,s.scope_id,s.explicit_topic_ids,s.explicit_category_ids,catalog,measure));builds++;layoutMs=performance.now()-start;document.body.style.setProperty('--scope',({course:'#b7b0d9',project:'#f3bc4d',stage:'#85bddf'})[s.scope_type]||'#b7b0d9');$('#scope-title').textContent=s.title;$('#mode-summary').textContent=`${m.root.title} · ${projection.explicit_topic_ids.length} explicit Topics · ${projection.explicit_category_ids.length} explicit Categories · ${projection.context_category_ids.length} context Categories · ${projection.used_global_roots.length} used roots`;$('#scopes').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.scope===s.scope_type));render();fit();history.replaceState(null,'','?scope='+s.scope_type);}
async function init(){[catalog,scopes]=await Promise.all(['catalog.json','scopes.json'].map(async f=>(await fetch(f)).json()));for(const s of scopes){const b=document.createElement('button');b.textContent=`${s.scope_type[0].toUpperCase()+s.scope_type.slice(1)} ${s.scope_id}`;b.dataset.scope=s.scope_type;b.onclick=()=>load(s);$('#scopes').append(b);}load(scopes.find(s=>s.scope_type===new URLSearchParams(location.search).get('scope'))||scopes[0]);
 $('#fit').onclick=()=>{$('#inspector-drawer').hidden=true;fit();};$('#fit-subtree').onclick=()=>fitSubtree();$('#topic-focus').onclick=()=>focusTopic();$('#close').onclick=()=>$('#inspector-drawer').hidden=true;$('#inspector-toggle').onclick=inspect;$('#in').onclick=()=>svg.call(zoom.scaleBy,1.4);$('#out').onclick=()=>svg.call(zoom.scaleBy,1/1.4);
 $('#minimap').onclick=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left-mini.x)/mini.k,y=(e.clientY-r.top-mini.y)/mini.k,gr=$('#graph').getBoundingClientRect();svg.call(zoom.transform,d3.zoomIdentity.translate(gr.width/2-x*transform.k,gr.height/2-y*transform.k).scale(transform.k));};
 $('#search').oninput=()=>{const q=$('#search').value.trim().toLowerCase(),matches=q?[...m.registry.values()].filter(n=>n.title.toLowerCase().includes(q)||String(n.id)===q||n.key===q).sort((a,b)=>(String(b.id)===q?1:0)-(String(a.id)===q?1:0)||a.id-b.id):[];$('#results').innerHTML=matches.slice(0,20).map(n=>`<button data-key="${n.key}">${esc(n.title)} · ${n.key}</button>`).join('');$('#results').querySelectorAll('button').forEach(b=>b.onclick=()=>{const n=m.nodes.get(b.dataset.key);select(n.key);n.type==='topic'?focusTopic(n.key):fitSubtree(n.key);$('#results').replaceChildren();});};$('#search').onkeydown=e=>{if(e.key==='Enter')$('#results button')?.click();if(e.key==='Escape')$('#results').replaceChildren();};window.addEventListener('resize',fit);
 g.ScopeApp={state:()=>({catalog,scopes,m,L,projection,transform,layoutMs,builds,selected}),load,measure,fit,select,fitSubtree,focusTopic,bounds};
}
init().catch(e=>{$('#error').textContent=e.stack;console.error(e);});
})(globalThis);
