const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require('/home/anton/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url=process.argv[2]||'http://127.0.0.1:8779/hyperskill-projects/knowledge-atlas-preview/',publicRun=url.startsWith('https:'),checks=[];
(async()=>{const browser=await chromium.launch({executablePath:'/opt/google/chrome/chrome',args:publicRun?['--host-resolver-rules=MAP planton361.github.io 185.199.108.153']:[]});
for(const width of [430,390,320])for(const theme of ['dark','light']){const p=await browser.newPage({viewport:{width,height:844},hasTouch:true,isMobile:true});await p.goto(url);await p.waitForFunction(()=>window.AtlasV6);await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(t=>document.body.classList.toggle('light',t==='light'),theme);await p.fill('#search','For loop');await p.press('#search','Enter');const before=await p.evaluate(()=>{const s=AtlasV6.state();return {coords:s.L.nodes.map(n=>[n.key,n.x,n.y]),checkpoint:JSON.stringify(s.L.checkpoint),k:s.transform.k,x:s.transform.x,layout:s.metrics.layout}});const client=await p.context().newCDPSession(p),box=await p.locator('#graph').boundingBox(),cx=box.x+box.width/2,cy=box.y+box.height/2;
await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-30,y:cy,id:1},{x:cx+30,y:cy,id:2}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-60,y:cy,id:1},{x:cx+60,y:cy,id:2}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await p.evaluate(k=>AtlasV6.state().transform.k>k,before.k));
const x=await p.evaluate(()=>AtlasV6.state().transform.x);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy,id:3}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx+30,y:cy+20,id:3}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await p.evaluate(x=>AtlasV6.state().transform.x!==x,x));
assert(await p.evaluate(b=>{const s=AtlasV6.state();return JSON.stringify(s.L.nodes.map(n=>[n.key,n.x,n.y]))===JSON.stringify(b.coords)&&JSON.stringify(s.L.checkpoint)===b.checkpoint&&s.metrics.layout===b.layout},before));checks.push({width,theme,pinch:true,pan:true,geometry:true});await p.close()}
fs.writeFileSync(__dirname+'/'+(publicRun?'public-':'')+'touch-results.json',JSON.stringify(checks,null,2)+'\n');console.log('PASS: touch pinch/pan and immutable geometry in 6 emulated configurations');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
