const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const base=process.argv[2]||'http://127.0.0.1:8774/knowledge-map-preview/',report={runs:[]};
async function snapshot(p){return p.evaluate(()=>{const s=TreeV5.state(),full=TreeV5.layout(s.m,new Set(),'incremental',s.slots),visible=new Set([...document.querySelectorAll('.node')].map(n=>n.dataset.key)),projection=TreeV5.coverageProjection(s.m,visible,'project:113');return{checkpoint:TreeLayout.serialize(s.slots),canonical:Object.fromEntries(full.nodes.map(n=>[n.data.key,[n.x,n.y]])),view:Object.fromEntries([...document.querySelectorAll('.node')].map(n=>[n.dataset.key,n.getAttribute('transform')])),collapsed:[...s.collapsed].sort(),viewport:{x:s.transform.x,y:s.transform.y,k:s.transform.k},search:{query:document.querySelector('#search').value,results:document.querySelector('#results').innerHTML},selection:s.selected,knowledge:JSON.stringify(s.m.raw),overlay:s.coverage,indicators:[...document.querySelectorAll('[data-coverage-count]')].map(n=>({key:n.dataset.key,count:Number(n.dataset.coverageCount),kind:n.dataset.coverageKind})),assignment:[...projection.byKey].map(([key,v])=>({key,count:v.count,topics:[...v.topics].sort(),kind:v.kind})),required:[...projection.required].sort(),planCalls:window.__coveragePlanCalls};});}
function unchanged(a,b,keys){for(const key of keys)assert.deepEqual(b[key],a[key],key+' changed');}
const immutable=['checkpoint','canonical','view','collapsed','viewport','search','selection','knowledge','planCalls'];
function count(s){assert.equal(s.indicators.reduce((n,i)=>n+i.count,0),26);const topics=s.assignment.flatMap(i=>i.topics);assert.equal(topics.length,26);assert.equal(new Set(topics).size,26);assert.deepEqual(topics.sort(),s.required);for(const i of s.indicators){const assignment=s.assignment.find(a=>a.key===i.key);assert.equal(assignment.count,i.count);assert.equal(assignment.kind,i.kind);}}
async function project(p){await p.locator('#search').fill('Simple Chat Bot with Java');await p.locator('#results button').first().click();await p.mouse.move(0,0);}
(async()=>{const b=await chromium.launch();try{for(const width of [1920,1440,1280,1200,1024,768,430,390,320])for(const theme of ['dark','light']){const mobile=width<=430,ctx=await b.newContext({viewport:{width,height:1100},hasTouch:mobile,colorScheme:theme,reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{let value;window.__coveragePlanCalls=0;Object.defineProperty(window,'TreeLayout',{configurable:true,get:()=>value,set:v=>{value=v;const original=v.buildPlan;v.buildPlan=function(...args){window.__coveragePlanCalls++;return original.apply(this,args);};}});});await p.goto(base);await p.locator('#graph[data-ready=true]').waitFor();assert.equal(await p.locator('#error').innerText(),'');if(mobile)assert.equal(await p.locator('.node').count(),9);await project(p);assert.equal(await p.locator('.node.evidence').count(),0);await p.locator('#search').fill('For loop');const before=await snapshot(p);await p.locator('[data-action="coverage"]').click();const shown=await snapshot(p);unchanged(before,shown,immutable);count(shown);assert.equal(await p.locator('[data-action="coverage"]').getAttribute('aria-pressed'),'true');if(mobile){assert.equal(await p.locator('.node').count(),9);assert.equal(shown.indicators.filter(i=>i.kind==='topic').length,0);assert.equal(shown.indicators.filter(i=>i.kind==='rollup').reduce((n,i)=>n+i.count,0),26);await p.screenshot({path:path.join(__dirname,`coverage-${width}-${theme}.png`),fullPage:true});}
await p.locator('[data-action="coverage"]').click();const hidden=await snapshot(p);unchanged(shown,hidden,immutable);assert.equal(hidden.indicators.length,0);assert.equal(await p.locator('.coverage-marker:not([display="none"])').count(),0);
// Fit the still-collapsed representation without enabling coverage or revealing.
const preFit=await snapshot(p);await p.locator('[data-action="fit-coverage"]').click();const fitCollapsed=await snapshot(p);unchanged(preFit,fitCollapsed,immutable.filter(k=>k!=='viewport'));assert.equal(fitCollapsed.overlay.enabled,false);
await p.locator('[data-action="coverage"]').click();count(await snapshot(p));
// Selecting a category keeps project context; manual disclosure/zoom survives hide.
await p.locator('.node[data-key="category:252"]').dispatchEvent('click');assert((await p.locator('#details').innerText()).includes('Project Coverage'));const expected=await p.evaluate(()=>{const s=TreeV5.state(),required=TreeV5.projectRequirements(s.m,'project:113'),n=s.m.nodes.get('category:252');const keys=new Set();function visit(node){keys.add(node.key);node.children.forEach(visit);}visit(n);return[...required].filter(k=>keys.has(k)).length;});assert((await p.locator('#details').innerText()).includes(expected+' required topics in this subtree'));await p.locator('[data-action="Expand"]').click();count(await snapshot(p));await p.locator('#in').click();const manual=await snapshot(p);await p.locator('[data-action="coverage"]').click();const offAfterManual=await snapshot(p);unchanged(manual,offAfterManual,immutable);assert.equal(offAfterManual.selection,'category:252');assert.equal(offAfterManual.indicators.length,0);
await project(p);await p.locator('[data-action="coverage"]').click();const preReveal=await snapshot(p);await p.locator('[data-action="reveal-required"]').click();const revealed=await snapshot(p);unchanged(preReveal,revealed,['checkpoint','canonical','viewport','search','selection','knowledge']);count(revealed);assert.equal(revealed.indicators.filter(i=>i.kind==='topic').length,26);assert.equal(revealed.indicators.filter(i=>i.kind==='rollup').length,0);assert(revealed.collapsed.every(k=>preReveal.collapsed.includes(k)));assert.equal(await p.locator('.requires').count(),0);const beforeRevealedFit=await snapshot(p);await p.locator('[data-action="fit-coverage"]').click();const fitted=await snapshot(p);unchanged(beforeRevealedFit,fitted,immutable.filter(k=>k!=='viewport'));count(fitted);
const learning=await p.evaluate(()=>{const probe=document.createElement('span');probe.style.color=getComputedStyle(document.body).getPropertyValue('--mint');document.body.append(probe);const color=getComputedStyle(probe).color;probe.remove();return[...document.querySelectorAll('.node.topic.evidence')].every(n=>n.classList.contains('learned')&&getComputedStyle(n.querySelector('.core')).fill===color);});assert(learning);const rings=await p.evaluate(()=>{const s=TreeV5.state();return[...document.querySelectorAll('.node.topic.evidence')].every(n=>n.querySelector('.ring').getAttribute('display')===(s.m.nodes.get(n.dataset.key).is_verified?null:'none'));});assert(rings);
await p.locator('[data-action="connections"]').click();assert.equal(await p.locator('.requires').count(),26);const preStage=await snapshot(p);await p.locator('[data-stage="617"]').click();const staged=await snapshot(p);unchanged(preStage,staged,immutable);assert.equal(staged.indicators.reduce((n,i)=>n+i.count,0),12);await p.locator('.node[data-key="category:252"]').dispatchEvent('click');assert((await p.locator('#details').innerText()).includes('Project Coverage'));await project(p);assert.equal(await p.locator('[data-stage="617"]').getAttribute('aria-pressed'),'true');assert.equal((await snapshot(p)).indicators.reduce((n,i)=>n+i.count,0),12);await p.locator('[data-stage="618"]').click();assert.equal((await snapshot(p)).indicators.length,0);
await p.locator('#clear').click();assert.equal(await p.locator('.node.evidence').count(),0);assert.equal(await p.locator('.requires').count(),0);
// Search remains explicit navigation and disclosure, independently of coverage.
await project(p);await p.locator('[data-action="coverage"]').click();await p.locator('.node[data-key="category:252"]').dispatchEvent('click');await p.locator('[data-action="Collapse subtree"]').click();const beforeSearch=await snapshot(p);await p.locator('#search').fill('For loop');await p.locator('#results button').first().click();const searched=await snapshot(p);assert.equal(searched.selection,'topic:89');assert(searched.collapsed.length<beforeSearch.collapsed.length);assert.notDeepEqual(searched.viewport,beforeSearch.viewport);count(searched);assert.equal(searched.checkpoint,beforeSearch.checkpoint);assert.deepEqual(errors,[]);
report.runs.push({width,theme,showCoverage:{checkpointDiff:0,canonicalDisplacement:0,categoryDisplacement:0,expansionDiff:0,viewportDiff:0,searchDiff:0,layoutPlanningCalls:0,indicators:shown.indicators,total:26},hideCoverageInvariant:true,manualDisclosureAndViewportPreserved:true,categoryInspector:true,reveal:{requiredTopicsVisible:26,checkpointDiff:0,canonicalDisplacement:0,viewportDiff:0},fit:{collapsedRepresentation:true,expansionDiff:0,checkpointDiff:0,canonicalDisplacement:0},stageEvidenceCounts:[12,0],learningPreserved:true,verificationPreserved:true,searchNavigationPreserved:true,errors});await ctx.close();}fs.writeFileSync(path.join(__dirname,'coverage-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({runs:report.runs.length,mobile:report.runs.filter(r=>r.width<=430).map(r=>({width:r.width,theme:r.theme,indicators:r.showCoverage.indicators}))},null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
