const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),os=require('os'),assert=require('node:assert/strict');const base=process.argv[2]||'http://127.0.0.1:8774/knowledge-map-preview/';
(async()=>{const b=await chromium.launch(),report={browser:b.version(),cpu:os.cpus()[0].model,method:'Actual cold-context preview loads and a real For loop search/selection. Browser-only wrappers measure existing functions; shipped assets remain unmodified. Model JSON decode includes response-body read. Initial DOM render includes its route work and excludes first paint. Layout sums checkpoint planning + collapsed projection planning + hierarchy placement. No CPU/network throttling; local static hosting.',runs:[]};try{
 for(const width of [1920,1440,1280,1200,1024,768,430,390,320])for(const theme of ['dark','light']){const ctx=await b.newContext({viewport:{width,height:1100},colorScheme:theme,hasTouch:width<=430,reducedMotion:'reduce'}),p=await ctx.newPage();await p.addInitScript(()=>{
  const metrics=window.__previewPerformance={phase:'initial',decode:[],plan:[],layout:[],routes:[],search:[]};
  const originalJson=Response.prototype.json;Response.prototype.json=async function(...args){const start=performance.now();const result=await originalJson.apply(this,args);if(this.url.endsWith('/model.json'))metrics.decode.push(performance.now()-start);return result;};
  function capture(name,methods){let value;Object.defineProperty(window,name,{configurable:true,get:()=>value,set:next=>{value=next;for(const [method,bucket]of Object.entries(methods)){const original=next[method];next[method]=function(...args){const started=performance.now();try{return original.apply(this,args);}finally{const end=performance.now();metrics[bucket].push({ms:end-started,phase:metrics.phase});if(bucket==='layout')metrics.lastLayoutEnd=end;}};}}});}
  capture('TreeLayout',{buildPlan:'plan',layout:'layout'});capture('TreeRouting',{route:'routes'});
  const observer=new MutationObserver(()=>{if(metrics.initialRenderMs==null&&document.querySelector('#graph[data-ready=true]')){metrics.initialRenderMs=performance.now()-metrics.lastLayoutEnd;metrics.phase='ready';observer.disconnect();}});observer.observe(document,{subtree:true,attributes:true,attributeFilter:['data-ready']});
 });await p.goto(base);await p.locator('#graph[data-ready=true]').waitFor();assert.equal(await p.locator('#error').innerText(),'');await p.evaluate(()=>{const el=document.querySelector('#search'),original=el.oninput;el.oninput=function(e){const start=performance.now();const result=original.call(this,e);window.__previewPerformance.search.push(performance.now()-start);return result;};});await p.locator('#search').fill('For loop');await p.evaluate(()=>window.__previewPerformance.phase='selection');await p.locator('#results button').first().click();assert.equal(await p.locator('#details h2').innerText(),'For loop');await p.mouse.move(0,0);const metrics=await p.evaluate(()=>window.__previewPerformance),sum=(rows,phase)=>rows.filter(r=>r.phase===phase).reduce((a,b)=>a+b.ms,0);report.runs.push({width,theme,modelJsonDecodeMs:metrics.decode[0],initialLayoutMs:sum(metrics.plan,'initial')+sum(metrics.layout,'initial'),initialRenderMs:metrics.initialRenderMs,initialRouteMs:sum(metrics.routes,'initial'),initialRoutes:metrics.routes.filter(r=>r.phase==='initial').length,selectedRouteMs:sum(metrics.routes,'selection'),selectedRoutes:metrics.routes.filter(r=>r.phase==='selection').length,searchResponseMs:metrics.search[0]});await ctx.close();}
 const fields=['modelJsonDecodeMs','initialLayoutMs','initialRenderMs','initialRouteMs','selectedRouteMs','searchResponseMs'];report.summary=Object.fromEntries(fields.map(k=>{const xs=report.runs.map(r=>r[k]).sort((a,b)=>a-b);return[k,{median:xs[Math.ceil(xs.length*.5)-1],p90:xs[Math.ceil(xs.length*.9)-1],min:xs[0],max:xs.at(-1)}];}));assert(report.runs.every(r=>fields.every(k=>Number.isFinite(r[k]))));fs.writeFileSync(path.join(__dirname,'performance-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.summary,null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
