/* Same metrics oracle before/after; all distances are world units unless px. */
module.exports=()=>{
 const {m,L,transform,metrics}=AtlasV6.state(),k=transform.k;
 const dist=values=>{const a=values.slice().sort((a,b)=>a-b),q=p=>a[Math.min(a.length-1,Math.floor((a.length-1)*p))]??0;return{count:a.length,min:q(0),median:q(.5),p90:q(.9),p95:q(.95),max:q(1)};};
 const box=AtlasLayout.contentBounds(L,L.nodes),width=box.x1-box.x0,height=box.y1-box.y0;
 const roots=m.root.children.map(n=>{const node=L.byKey.get(n.key),p=L.plans.get(n.key);return{key:n.key,title:n.title,x0:node.x+p.left,x1:node.x+p.right,y0:node.y,y1:node.y+p.height,width:p.width,height:p.height,cardPx:{width:node.width*k,height:node.height*k}};});
 const connectors=L.branches.map(e=>{const a=L.byKey.get(e.parent),b=L.byKey.get(e.child);return{parent:e.parent,parentTitle:a.data.title,child:e.child,childTitle:b.data.title,span:Math.max(...e.points.map(p=>p.x))-Math.min(...e.points.map(p=>p.x)),centerDistance:Math.hypot(b.x-a.x,(b.y+b.height/2)-(a.y+a.height/2))};});
 for(const t of L.trays){const p=L.byKey.get(t.parent);connectors.push({parent:t.parent,parentTitle:p.data.title,child:'tray:'+t.parent,span:Math.abs(p.x-t.x-t.width/2),centerDistance:Math.hypot(p.x-t.x-t.width/2,p.y+p.height/2-t.y-t.height/2)});}
 const gaps=[];for(const n of m.nodes.values()){const cats=n.children.filter(c=>c.type==='category');for(let i=1;i<cats.length;i++){const a=L.byKey.get(cats[i-1].key),b=L.byKey.get(cats[i].key),pa=L.plans.get(a.key),pb=L.plans.get(b.key);gaps.push({parent:n.key,left:a.key,right:b.key,gap:b.x+pb.left-a.x-pa.right});}}
 const categories=L.nodes.filter(n=>n.data.type==='category'),trays=L.trays.map(t=>({parent:t.parent,title:m.nodes.get(t.parent).title,slots:t.topics.length,width:t.width,height:t.height,area:t.width*t.height,columns:L.bands.get(t.parent).columns.length}));
 const projected={};for(const depth of [...new Set(categories.map(n=>n.depth))]){const ns=categories.filter(n=>n.depth===depth);projected[depth]={widthPx:dist(ns.map(n=>n.width*k)),heightPx:dist(ns.map(n=>n.height*k))};}
 const markers=[...document.querySelectorAll('#graph .core')];
 return {bounds:{...box,width,height,aspect:width/height},roots,rootGaps:roots.slice(1).map((b,i)=>b.x0-roots[i].x1),connectorCount:L.connectorSegments.length,categoryRoutes:L.branches.length,trayRoutes:L.trays.length,horizontalSpan:dist(connectors.map(e=>e.span)),categoryHorizontalSpan:dist(connectors.filter(e=>!e.child.startsWith('tray:')).map(e=>e.span)),horizontalSegmentSpan:dist(L.connectorSegments.filter(e=>e.points[0].y===e.points[1].y).map(e=>Math.abs(e.points[0].x-e.points[1].x))),parentChildCenterDistance:dist(connectors.filter(e=>!e.child.startsWith('tray:')).map(e=>e.centerDistance)),largest20Connectors:connectors.sort((a,b)=>b.span-a.span).slice(0,20),largest20SiblingGaps:gaps.sort((a,b)=>b.gap-a.gap).slice(0,20),siblingGaps:dist(gaps.map(g=>g.gap)),trayCount:trays.length,trayWidth:dist(trays.map(t=>t.width)),trayHeight:dist(trays.map(t=>t.height)),trayArea:dist(trays.map(t=>t.area)),smallestTray:trays.slice().sort((a,b)=>a.area-b.area)[0],medianTray:trays.slice().sort((a,b)=>a.area-b.area)[Math.floor(trays.length/2)],largestTray:trays.slice().sort((a,b)=>b.area-a.area)[0],largestBySlots:trays.slice().sort((a,b)=>b.slots-a.slots)[0],multiColumnTrays:trays.filter(t=>t.columns>1),fitScale:k,projectedCategoryCards:projected,projectedTrayHeights:dist(trays.map(t=>t.height*k)),projectedTrayWidths:dist(trays.map(t=>t.width*k)),statusMarkerDiameterPx:dist(markers.map(el=>Number(el.getAttribute('r'))*2*k)),statusMarkerStrokePx:dist(markers.map(el=>parseFloat(getComputedStyle(el).strokeWidth))),slotCues:document.querySelectorAll('#graph .slot-cue').length,metrics};
};
