const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium,launchOptions}=require('../browser.cjs'),metrics=require('./layout-metrics.cjs');
const out=__dirname;const dist=a=>{a.sort((x,y)=>x-y);return Object.fromEntries(['min','median','p90','p95','max'].map((k,i)=>[k,a[Math.floor((a.length-1)*[0,.5,.9,.95,1][i])]]))};
(async()=>{const browser=await chromium.launch(launchOptions);try{const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:2,reducedMotion:'reduce'}),results={};
const settle=async()=>{await page.waitForFunction(()=>!AtlasV6.state().transitioning);await page.evaluate(()=>AtlasV6.state().renderer.settled())};
for(const [name,url]of [['before',process.env.BEFORE_URL||'http://127.0.0.1:8802'],['after',process.env.ATLAS_URL||'http://127.0.0.1:8801']]){await page.goto(url);await page.waitForFunction(()=>window.AtlasV6);await settle();results[name]=await page.evaluate(metrics);results[name].details=await page.evaluate(async()=>{
const {m,L,renderer:r,transform:t}=AtlasV6.state(),leaves=L.nodes.filter(n=>AtlasModel.isLeaf(n.data)),ctx=document.createElement('canvas').getContext('2d');ctx.font='14px system-ui';
const geometry={nodes:L.nodes.map(({data,...n})=>n),trays:L.trays,branches:L.branches,connectors:L.connectorSegments,checkpoint:L.checkpoint,plans:[...L.plans],routingGroups:[...L.routingGroups]},hash=async v=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(v))))].map(x=>x.toString(16).padStart(2,'0')).join('');
const cores=r.scene.inks.filter(c=>c.kind==='core'&&c.style==='learnedCore'),rings=r.scene.inks.filter(c=>c.kind==='ring'),progress=cores.map(c=>{const ring=rings.find(x=>x.entity===c.entity),o=AtlasTiled.markerOptics(ring||c,t.k,'overview'),e=r.byKey.get(c.entity);return{key:c.entity,x:c.x*t.k+t.x,y:c.y*t.k+t.y,outer:o.radius*t.k+o.width/2,anchorExact:c.x===e.x+12&&c.y===e.y+e.h/2,verified:!!ring}});let overlappingPairs=0;for(let i=0;i<progress.length;i++)for(let j=i+1;j<progress.length;j++){const a=progress[i],b=progress[j];if(Math.min(a.outer+b.outer-Math.abs(a.x-b.x),a.outer+b.outer-Math.abs(a.y-b.y))>1e-9)overlappingPairs++}
return{geometryHash:await hash(geometry),version:L.checkpoint.layout_algorithm_version,leaves:leaves.map(n=>({id:n.data.id,title:n.data.displayTitle,width:n.width,height:n.height,lines:n.lines.length,naturalWidth:ctx.measureText(n.data.displayTitle).width,chars:n.data.displayTitle.length,parent:n.parent})),owners:[...m.registry.values()].map(n=>[n.id,n.parentKey]),learned:[...m.registry.values()].filter(n=>n.is_learned).map(n=>n.id),verified:[...m.registry.values()].filter(n=>n.is_verified).map(n=>n.id),progress,overlappingPairs,layoutCalls:0};});}
const a=results.after.details,b=results.before.details;assert.deepEqual(a.owners,b.owners);assert.deepEqual(a.learned,b.learned);assert.deepEqual(a.verified,b.verified);assert.equal(a.overlappingPairs,0);assert(a.progress.every(p=>p.anchorExact));assert.notEqual(a.geometryHash,b.geometryHash);
for(const name of ['before','after']){const d=results[name].details;results[name].topicWidth=dist(d.leaves.map(n=>n.width));results[name].topicHeight=dist(d.leaves.map(n=>n.height));results[name].wrappedLines=d.leaves.reduce((acc,n)=>(acc[n.lines]=(acc[n.lines]||0)+1,acc),{});results[name].characters=dist(d.leaves.map(n=>n.chars));results[name].naturalWidth=dist(d.leaves.map(n=>n.naturalWidth));results[name].longest=d.leaves.slice().sort((a,b)=>b.chars-a.chars||a.id-b.id).slice(0,3);results[name].widest=d.leaves.slice().sort((a,b)=>b.naturalWidth-a.naturalWidth||a.id-b.id).slice(0,3);}
const compact=structuredClone(results);for(const phase of ['before','after']){delete compact[phase].details.leaves;delete compact[phase].details.owners;}fs.writeFileSync(path.join(out,'metrics.json'),JSON.stringify(compact,null,2)+'\n');
fs.mkdirSync(path.join(out,'review'),{recursive:true});const capture=async(name,key)=>{if(key)await page.evaluate(key=>AtlasV6.select(key,true),key);else await page.click('#fit');await settle();await page.screenshot({path:path.join(out,'review',name+'.png')});};
await capture('01-global-fit-all',null);await capture('02-computer-science','category:1162');await capture('03-natural-science','category:2148');await capture('04-programming-languages','category:1164');await capture('05-topic-3887','topic:3887');
const parents=new Map();for(const n of a.leaves){if(n.naturalWidth>230){parents.set(n.parent,(parents.get(n.parent)||0)+1)}}const longCategory=[...parents].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0];await capture('06-long-title-category',longCategory[0]);
await page.click('#fit');await settle();await page.evaluate(()=>AtlasV6.select('category:1164',false));await settle();await page.screenshot({path:path.join(out,'review','07-learned-verified-overview.png')});
fs.writeFileSync(path.join(out,'review-scenes.json'),JSON.stringify({viewport:[1440,900],dpr:2,longTitleCategory:longCategory,paths:fs.readdirSync(path.join(out,'review'))},null,2)+'\n');console.log(JSON.stringify({beforeHash:b.geometryHash,afterHash:a.geometryHash,before:results.before.bounds,after:results.after.bounds,wrap:results.after.wrappedLines,longCategory,progressOverlap:a.overlappingPairs}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
