const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),collision=require('../tests/collisions.cjs');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
try{const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1}),errors=[],external=[],results=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin==='http://127.0.0.1:8765')return r.continue();external.push(u.href);return r.abort();});
await page.goto('http://127.0.0.1:8765/docs/knowledge-map-adaptive-preview/');await page.waitForFunction(()=>window.KnowledgeAtlas);const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const shot=async name=>{await settle();await page.screenshot({path:path.join(__dirname,name+'.png')});};
const capture=async name=>{await settle();const row=await page.evaluate(name=>{const {views:v}=KnowledgeAtlas,b=GlobalAtlasCore.bounds(v.positions.values());return {name,mode:v.mode,topics:v.scope.topics.size,entities:v.positions.size,unknown:v.scope.unknown,width:b?.w||0,height:b?.h||0,area:(b?.w||0)*(b?.h||0),fitScale:v.camera.k,layoutMs:v.metrics.layoutMs,readableTopicLabels:v.metrics.readableTopicLabels,renderedCards:v.metrics.renderedCards,labels:v.metrics.labels,minimapSystem:v.metrics.minimapSystem};},name);results.push(row);return row;};
const validateLayout=async name=>{const row=await page.evaluate(()=>{const v=KnowledgeAtlas.views;return{positions:[...v.local.positions],routes:v.local.routes,visible:[...v.scope.visible],hidden:[...v.local.hidden]};});assert.deepEqual(new Set(row.positions.map(([k])=>k)),new Set(row.visible.filter(k=>!row.hidden.includes(k))));checks.push({name,...collision({positions:new Map(row.positions),routes:row.routes})});};
const initialCalls=await page.evaluate(()=>KnowledgeAtlas.views.metrics.layoutCalls);await page.locator('#global').click();assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.metrics.layoutCalls),initialCalls);assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.scope.visible.size),3955);await capture('global-complete');await shot('global-complete');
for(const [name,options]of [['my',{mode:'learned',id:8,stage:null,branch:null,onlyLearned:false}],['accepted',{mode:'accepted'}],['course8',{mode:'course',id:8}],['project113',{mode:'project',id:113}],['stage617',{mode:'project',id:113,stage:617}]]){
 await page.evaluate(o=>KnowledgeAtlas.confirm(o,'compact'),options);await capture(name+'-compact');await validateLayout(name);await shot(name+'-compact');const group=await page.evaluate(()=>[...KnowledgeAtlas.views.local.groups].sort((a,b)=>b.cards.length-a.cards.length)[0].parent);await page.evaluate(k=>KnowledgeAtlas.focus(k),group);await capture(name+'-compact-group');await shot(name+'-compact-group');
 await page.evaluate(()=>KnowledgeAtlas.confirm(KnowledgeAtlas.views.options,'mask'));await capture(name+'-strict');await shot(name+'-strict');await page.evaluate(k=>KnowledgeAtlas.focus(k),group);await capture(name+'-strict-group');await shot(name+'-strict-group');
 const before=await page.evaluate(()=>({calls:KnowledgeAtlas.views.metrics.layoutCalls,camera:{...KnowledgeAtlas.views.cameras.global}}));await page.locator('#highlight').click();await settle();assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.metrics.layoutCalls),before.calls);assert.deepEqual(await page.evaluate(()=>KnowledgeAtlas.views.cameras.global),before.camera);await capture(name+'-highlight');await shot(name+'-highlight');
}
await page.evaluate(()=>KnowledgeAtlas.confirm({mode:'project',id:113,stage:null},'compact'));await page.evaluate(()=>KnowledgeAtlas.focus('category:35'));await capture('project-group');await shot('project-group');
await page.evaluate(()=>KnowledgeAtlas.confirm({mode:'course',id:8,stage:null},'compact'));const calls=await page.evaluate(()=>KnowledgeAtlas.views.metrics.layoutCalls);await page.locator('#only-learned').check();assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.scope.topics.size),89);await page.locator('#compact').click();assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.scope.topics.size),31);assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.metrics.layoutCalls),calls+1);await capture('course8-learned');await shot('course8-learned');
await page.evaluate(()=>KnowledgeAtlas.confirm({mode:'project',id:380,stage:null,onlyLearned:false},'compact'));assert.match(await page.locator('#empty').innerText(),/UNKNOWN/);await shot('unknown');await page.evaluate(()=>KnowledgeAtlas.confirm({mode:'project',id:113,stage:618},'compact'));assert.match(await page.locator('#empty').innerText(),/Known empty/);
for(const fixture of ['load-100','load-300','load-1000','broad']){await page.evaluate(mode=>KnowledgeAtlas.confirm({mode,stage:null,onlyLearned:false,branch:null},'compact'),'fixture:'+fixture);await capture(fixture);await validateLayout(fixture);await shot(fixture);await page.locator('#summarize').click();await capture(fixture+'-summary');await shot(fixture+'-summary');const hidden=await page.evaluate(()=>[...KnowledgeAtlas.views.local.hidden].find(k=>!k.startsWith('category:')));assert(hidden);await page.locator('#search').fill(hidden);await page.locator('#search').press('Enter');assert(await page.evaluate(k=>KnowledgeAtlas.views.local.positions.has(k),hidden));await validateLayout(fixture+'-opened');}
// Complete search, explicit destinations and proven context, without learning.
await page.evaluate(()=>KnowledgeAtlas.confirm({mode:'learned',branch:null},'compact'));const semantic=await page.evaluate(()=>JSON.stringify(KnowledgeAtlas.views.m.raw.progress));await page.locator('#search').fill('reference:333');await page.locator('#search').press('Enter');assert.equal(await page.locator('#my-show').isDisabled(),true);await page.locator('#global-show').click();assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.selected),'reference:333');await shot('global-reference333');assert.equal(await page.evaluate(()=>JSON.stringify(KnowledgeAtlas.views.m.raw.progress)),semantic);
await page.locator('#search').fill('reference:36');await page.locator('#search').press('Enter');assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.selected),'topic:36');assert(await page.locator('#related button').count()>0);await page.locator('#my-show').click();assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.options.mode),'learned');await shot('my-topic36');
// One in-memory explicit learning-state fixture; authoritative files are untouched.
await page.evaluate(()=>{KnowledgeAtlas.confirm({mode:'learned',branch:null},'compact');const v=KnowledgeAtlas.views;window.initialSnapshot=v.m.raw;window.referenceSnapshot=JSON.stringify(v.m.geometry);window.referencePositions=[...v.m.reference].map(([k,p])=>[k,p.x,p.y,p.w,p.h]);window.addedID=v.m.raw.progress.find(r=>r.is_learned===false).topic_id;v.selected=[...v.scope.topics][0];window.priorLocal=v.local;window.priorCamera={...v.camera};});
const beforeLearning=await page.evaluate(()=>{const v=KnowledgeAtlas.views,p=v.local.positions.get(v.selected);return{selected:v.selected,x:p.x*v.camera.k+v.camera.x,y:p.y*v.camera.k+v.camera.y,calls:v.metrics.layoutCalls};});
await page.evaluate(()=>{const next=structuredClone(initialSnapshot);next.presentation_fixture=true;next.progress.find(r=>r.topic_id===addedID).is_learned=true;KnowledgeAtlas.refreshSnapshot(next);});await settle();
const learning=await page.evaluate(before=>{const v=KnowledgeAtlas.views,p=v.local.positions.get(v.selected),b=v.local.bounds;return{addedID,fixtureOnly:true,learned:v.scope.topics.size,verified:v.scope.verified.size,averageDisplacement:v.metrics.movement.average,maxDisplacement:v.metrics.movement.max,existing:v.metrics.movement.existing,anchorDelta:Math.hypot(p.x*v.camera.k+v.camera.x-before.x,p.y*v.camera.k+v.camera.y-before.y),layoutCalls:v.metrics.layoutCalls-before.calls,animationMs:v.metrics.animationMs,width:b.w,height:b.h};},beforeLearning);assert.equal(learning.learned,32);assert.equal(learning.verified,12);assert.equal(learning.layoutCalls,1);assert.equal(learning.animationMs,180);assert(learning.anchorDelta<.001);
const animation=await page.evaluate(()=>{const v=KnowledgeAtlas.views,t=v.transition||{before:priorLocal,after:v.local,start:0,duration:180,oldCamera:priorCamera,newCamera:v.camera};return [0,45,90,135,180].map(ms=>{const f=AtlasViews.interpolate(t,t.start+ms);return {ms,positions:[...f.positions].filter(([,p])=>p.opacity!==0)};});});for(const f of animation)collision({positions:new Map(f.positions),routes:[]});await page.waitForTimeout(200);await shot('learning-addition');
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>KnowledgeAtlas.refreshSnapshot(initialSnapshot));assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.metrics.animationMs),0);
const styleCalls=await page.evaluate(()=>KnowledgeAtlas.views.metrics.layoutCalls);await page.locator('#progress').uncheck();await page.locator('#search').fill('Java');await page.mouse.move(800,450);await page.locator('#zoom-in').click();await page.locator('#map').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>KnowledgeAtlas.views.metrics.layoutCalls),styleCalls);
const unchanged=await page.evaluate(()=>{const v=KnowledgeAtlas.views;if(JSON.stringify(v.m.geometry)!==referenceSnapshot)throw Error('Global geometry changed');let count=0;for(const [k,x,y,w,h]of referencePositions){const p=v.m.reference.get(k);if(p.x!==x||p.y!==y||p.w!==w||p.h!==h)throw Error('Reference displacement '+k);if('x' in v.m.entities.get(k))throw Error('Entity contains coordinates');count++;}return count;});assert.equal(unchanged,3955);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight));
fs.writeFileSync(__dirname+'/browser-results.json',JSON.stringify({viewport:[1440,900],scenes:results,checks,learning,animationSamples:animation.map(f=>f.ms),globalComparisons:unchanged,globalDisplacement:0,highlightLayoutCalls:0,stylingLayoutCalls:0,errors,external,checksSummary:'PASS selection/filter, collisions/routes, search destinations, UNKNOWN/empty, separate minimaps/cameras, learning tween/focus/reduced motion, unchanged global geometry/data'},null,2)+'\n');console.log(JSON.stringify({scenes:results,learning,checks:'PASS'},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
