const fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'../../..'),source=root+'/scripts/knowledge_atlas/presentation/',A=require(source+'adaptive.cjs'),R=require(source+'registry.cjs'),{Views,interpolate}=require(source+'views.cjs'),C=require(root+'/prototypes/global-pyramid/atlas.js'),original=require('../core.cjs'),collisions=require('../tests/collisions.cjs');
const raw=JSON.parse(fs.readFileSync(root+'/docs/knowledge-map-adaptive-preview/model.json')),geometry=JSON.parse(fs.readFileSync(root+'/docs/knowledge-map-adaptive-preview/global-reference.json')),m=R.index(raw,geometry),globalBefore=JSON.stringify(geometry),progressBefore=JSON.stringify(raw.progress);
const measure=(s,font)=>s.length*(font.includes('15px')?7.6:font.includes('14px')?7.1:5.5),scenes=[],legacy=C.index(raw,geometry);
const inputs=[{mode:'learned'},{mode:'accepted'},{mode:'course',id:8},{mode:'course',id:8,onlyLearned:true},{mode:'project',id:113},{mode:'project',id:113,stage:617},{mode:'project',id:113,stage:617,onlyLearned:true},{mode:'project',id:380},...['load-100','load-300','load-1000','broad'].map(n=>({mode:'fixture:'+n}))];
for(const options of inputs){const s=A.selection(m,options),l=A.layout(m,s,{measure}),second=A.layout(m,A.selection(m,options),{measure});assert.deepEqual([...l.positions],[...second.positions]);assert.deepEqual(l.routes,second.routes);assert.deepEqual(new Set(l.positions.keys()),s.visible);assert.equal(new Set([...l.positions.values()].map(p=>p.slot)).size,l.positions.size);
 for(const [k,p]of l.positions){assert.equal(p.parent,m.nodes.get(k).parent);assert(!('x' in m.entities.get(k)));assert(!('x' in m.nodes.get(k)));assert.notEqual(p,m.reference.get(k));}
 for(const n of m.nodes.values()){const cs=n.children.filter(c=>c.kind==='category'&&l.positions.has(c.key));for(let i=1;i<cs.length;i++)assert(l.positions.get(cs[i-1].key).x<l.positions.get(cs[i].key).x);}
 for(const group of l.groups)assert.deepEqual(group.cards.map(c=>c.key),m.nodes.get(group.parent).children.filter(n=>s.topics.has(n.key)).map(n=>n.key));
 if(!s.isFixture){const old=original.layout(legacy,original.selection(legacy,options),{measure});assert.deepEqual([...l.positions],[...old.positions]);assert.deepEqual(l.routes,old.routes);}
 const slotsVisible=new Set([...s.visible].map(C.slot));
 const strict=s.isFixture?null:collisions({positions:new Map([...s.visible].map(k=>[k,m.reference.get(k)])),routes:m.geometry.hierarchy_routes.filter(r=>slotsVisible.has(r.child))});
 scenes.push({options,topics:s.topics.size,visible:s.visible.size,unknown:s.unknown,...collisions(l),strictGlobalCollisions:strict});
}
assert.deepEqual(A.selection(m).explicit,new Set(raw.progress.filter(r=>r.is_learned===true).map(r=>'topic:'+r.topic_id)));assert.deepEqual(A.selection(m,{mode:'accepted'}).explicit,new Set(raw.personal));assert.equal(A.selection(m,{mode:'project',id:113,stage:618}).unknown,false);assert.equal(A.selection(m,{mode:'project',id:113,stage:999}).unknown,true);
const course=raw.courses.find(c=>c.id===8),project=raw.projects.find(p=>p.id===113),stage=project.stages.find(s=>s.id===617),semanticKey=id=>m.entities.has('topic:'+id)?'topic:'+id:'reference:'+id;
assert.deepEqual(A.selection(m,{mode:'course',id:8}).explicit,new Set([...course.category_ids.map(id=>'category:'+id),...course.topic_ids.map(semanticKey)]));
assert.deepEqual(A.selection(m,{mode:'project',id:113}).explicit,new Set(project.required));assert.deepEqual(A.selection(m,{mode:'project',id:113,stage:617}).explicit,new Set(stage.required_topic_ids.map(semanticKey)));
for(const key of A.selection(m).context)assert(!A.selection(m).learned.has(key),'Context is not learned');
const v=new Views(m,measure);v.confirm({mode:'learned'});const calls=v.metrics.layoutCalls,local=v.local;v.confirm({mode:'course',id:8},'reference');v.confirm({mode:'project',id:113,stage:617},'reference');assert.equal(v.metrics.layoutCalls,calls);assert.equal(v.local,local);assert.equal(v.positions,m.reference);
v.confirm({mode:'learned',stage:null},'compact');v.selected=[...v.scope.topics][0];const before=v.local,cam={...v.camera},p=before.positions.get(v.selected),key=raw.progress.find(r=>r.is_learned===false).topic_id;
// Entirely in-memory explicit-state fixture; it is never an observation/source write.
const next=structuredClone(raw);next.progress.find(r=>r.topic_id===key).is_learned=true;v.updateSnapshot(next);assert.equal(v.scope.topics.size,32);assert.equal(v.scope.verified.size,12);assert.equal(v.metrics.animationMs,180);const q=v.local.positions.get(v.selected);assert(Math.hypot(p.x*cam.k+cam.x-q.x*v.camera.k-v.camera.x,p.y*cam.k+cam.y-q.y*v.camera.k-v.camera.y)<.001);collisions(v.local);const learningMovement=v.metrics.movement;
const transition=interpolate(v.transition,v.transition.start+90);assert(Math.abs(transition.t-.5)<1e-9);assert.equal(transition.positions.size,v.local.positions.size);for(const ms of [0,45,90,135,180]){const f=interpolate(v.transition,v.transition.start+ms);collisions({positions:new Map([...f.positions].filter(([,p])=>p.opacity!==0)),routes:[]});}
v.updateSnapshot(raw,{reducedMotion:true});assert.equal(v.metrics.animationMs,0);const style=structuredClone(raw),verifiedRow=style.progress.find(r=>r.is_learned===true&&r.is_verified===false);verifiedRow.is_verified=true;verifiedRow.verification_status='verified';const styleCalls=v.metrics.layoutCalls;v.updateSnapshot(style);assert.equal(v.metrics.layoutCalls,styleCalls);assert.equal(v.scope.topics.size,31);v.updateSnapshot(raw);v.confirm({mode:'fixture:load-1000'});v.summarize();assert(v.local.positions.size<20);const hidden=[...v.local.hidden][0];v.open(hidden);assert(v.local.positions.has(hidden));
const slots=new Map(geometry.positions.map(p=>[p.key,p]));let globalComparisons=0;for(const [k,e]of m.entities){assert.equal(m.reference.get(k),slots.get(C.slot(k)));assert(!('x' in e));globalComparisons++;}assert.equal(JSON.stringify(geometry),globalBefore);assert.equal(JSON.stringify(raw.progress),progressBefore);
fs.writeFileSync(__dirname+'/core-results.json',JSON.stringify({scenes,semanticFixture:{addedTopic:key,learnedBefore:31,learnedAfter:32,verified:12,presentationOnly:true,movement:learningMovement},globalComparisons,checks:'PASS IDs, registry/geometry separation, original algorithm parity, hierarchy/order, overlaps/routes, highlight no layout, explicit learning flow, unchanged verified/global data, UNKNOWN, determinism, collapse/open, reduced motion'},null,2)+'\n');console.log(JSON.stringify({scenes,globalComparisons,checks:'PASS'}));
