const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),R=require('../../../scripts/knowledge_atlas/presentation/registry.cjs'),A=require('../../../scripts/knowledge_atlas/presentation/adaptive.cjs'),check=require('./invariants.cjs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});try{
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1}),errors=[],results=[],growth=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/docs/knowledge-map-adaptive-preview/');await page.waitForFunction(()=>window.KnowledgeAtlas);
const {raw,geometry}=await page.evaluate(()=>({raw:KnowledgeAtlas.views.m.raw,geometry:KnowledgeAtlas.views.m.geometry})),m=R.index(raw,geometry),settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function capture(name,screenshot=true){await settle();const row=await page.evaluate(()=>{const v=KnowledgeAtlas.views,l=v.local;return{positions:[...l.positions],subtrees:[...l.subtrees],bands:[...l.bands],groups:l.groups,routes:l.routes,hidden:[...l.hidden],bounds:l.bounds,siblingGap:l.siblingGap,options:v.options,raw:v.m.raw,layoutMs:v.metrics.layoutMs,cards:v.metrics.renderedCards,labels:v.metrics.labels,topicLabels:v.metrics.readableTopicLabels,fitScale:v.camera.k,camera:v.camera,labelBoxes:v.metrics.labelBoxes};});
 const l={...row,positions:new Map(row.positions),subtrees:new Map(row.subtrees),bands:new Map(row.bands),hidden:new Set(row.hidden)},live=R.replaceSnapshot(m,row.raw),s=A.selection(live,row.options);const checks=check(live,s,l);for(const box of row.labelBoxes){const region=l.subtrees.get(box.key),c=row.camera,project=p=>({x:p.x*c.k+c.x,y:p.y*c.k+c.y,w:p.w*c.k,h:p.h*c.k});const b=project(region);assert(box.x>=b.x-1e-9&&box.x+box.w<=b.x+b.w+1e-9&&box.y>=b.y-1e-9&&box.y+box.h<=b.y+b.h+1e-9,'Callout containment');for(const [key,p]of l.positions)if(key!==box.key){const q=project(p);assert(!(q.x<box.x+box.w+2&&q.x+q.w+2>box.x&&q.y<box.y+box.h+2&&q.y+q.h+2>box.y),'Callout obscures another card');}}results.push({name,topics:s.topics.size,width:row.bounds.w,height:row.bounds.h,layoutMs:row.layoutMs,cards:row.cards,labels:row.labels,readableTopicLabels:row.topicLabels,fitScale:row.fitScale,...checks});if(screenshot)await page.screenshot({path:path.join(__dirname,name+'.png')});
}
await capture('my-knowledge');
const java=await page.evaluate(()=>[...KnowledgeAtlas.views.m.nodes.values()].find(n=>n.kind==='category'&&n.title==='Java').key);await page.evaluate(k=>KnowledgeAtlas.focus(k),java);await capture('java-focus');
const group=await page.evaluate(()=>[...KnowledgeAtlas.views.local.groups].sort((a,b)=>b.cards.length-a.cards.length)[0].parent);await page.evaluate(k=>KnowledgeAtlas.focus(k),group);await capture('topic-group');
for(const [name,o]of [['course8',{mode:'course',id:8}],['project113',{mode:'project',id:113}],['stage617',{mode:'project',id:113,stage:617}],...['load-100','load-300','load-1000'].map(n=>[n,{mode:'fixture:'+n}])]){await page.evaluate(o=>KnowledgeAtlas.confirm(o,'compact'),o);await capture(name,['project113','stage617'].includes(name));}
const targets=await page.evaluate(()=>{const v=KnowledgeAtlas.views;return ['Computer science','Software development foundations','Programming languages','Java','Basics','Code organization','Errorless code'].map(title=>{const n=[...v.m.nodes.values()].find(n=>n.title===title&&n.kind==='category');return{title,key:n?.key,depth:n?.depth};});});
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>KnowledgeAtlas.confirm({mode:'learned',stage:null},'compact'));
for(let step=0;step<3;step++){
 const before=await page.evaluate(()=>{const v=KnowledgeAtlas.views;v.selected=[...v.scope.topics][0];return {positions:[...v.local.positions],progress:v.m.raw.progress,geometry:JSON.stringify(v.m.geometry),camera:{...v.camera},selected:v.selected};});
 const row=await page.evaluate(()=>{const v=KnowledgeAtlas.views,next=structuredClone(v.m.raw),r=next.progress.find(r=>r.is_learned===false);next.presentation_fixture=true;r.is_learned=true;KnowledgeAtlas.refreshSnapshot(next);return{added:r.topic_id,movement:v.metrics.movement,positions:[...v.local.positions],camera:{...v.camera},selected:v.selected};});
 const p=new Map(before.positions).get(before.selected),q=new Map(row.positions).get(row.selected),anchor=Math.hypot(p.x*before.camera.k+before.camera.x-q.x*row.camera.k-row.camera.x,p.y*before.camera.k+before.camera.y-q.y*row.camera.k-row.camera.y);assert(anchor<1e-8);assert.equal(await page.evaluate(()=>JSON.stringify(KnowledgeAtlas.views.m.geometry)),before.geometry);
 const mv=row.movement;growth.push({step:step+1,addedTopic:row.added,existing:mv.existing,average:mv.average,max:mv.max,maxDX:Math.max(...mv.entities.map(e=>Math.abs(e.dx))),maxDY:Math.max(...mv.entities.map(e=>Math.abs(e.dy))),maxCategoryDY:Math.max(...mv.entities.filter(e=>e.key.startsWith('category:')).map(e=>Math.abs(e.dy))),anchorDelta:anchor});await capture('learning-'+(step+1),false);
}
assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight),true);
fs.writeFileSync(__dirname+'/browser-results.json',JSON.stringify({viewport:[1440,900],scenes:results,targets,growth,errors,checks:'PASS depth/rank, subtree/card/routes, order, containment, learning additions, global invariance, focus anchor'},null,2)+'\n');console.log(JSON.stringify({scenes:results,growth,checks:'PASS'},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
