const fs=require('fs'),assert=require('node:assert/strict'),path=require('path'),root=path.resolve(__dirname,'../../..'),A=require(root+'/scripts/knowledge_atlas/presentation/adaptive.cjs'),R=require(root+'/scripts/knowledge_atlas/presentation/registry.cjs'),old=require('../core.cjs'),check=require('./invariants.cjs');
const raw=JSON.parse(fs.readFileSync(root+'/docs/knowledge-map-adaptive-preview/model.json')),geometry=JSON.parse(fs.readFileSync(root+'/docs/knowledge-map-adaptive-preview/global-reference.json')),m=R.index(raw,geometry),before=JSON.stringify(geometry),measure=(s,f)=>s.length*(f.includes('15px')?7.6:f.includes('14px')?7.1:5.5),results=[];
for(const o of [{mode:'learned'},{mode:'course',id:8},{mode:'project',id:113},{mode:'project',id:113,stage:617},...['load-100','load-300','load-1000'].map(n=>({mode:'fixture:'+n}))]){
 const s=A.selection(m,o),l=A.layout(m,s,{measure}),repeat=A.layout(m,s,{measure});assert.deepEqual([...l.positions],[...repeat.positions]);assert.deepEqual(l.routes,repeat.routes);assert.deepEqual([...l.subtrees],[...repeat.subtrees]);
 const r={options:o,topics:s.topics.size,cards:l.positions.size,width:l.bounds.w,height:l.bounds.h,layoutMs:l.durationMs,...check(m,s,l)};
 if(o.mode==='learned'){const prior=old.layout(m,s,{measure}),spread=new Map();for(const [k,p]of prior.positions)if(m.nodes.get(k).kind==='category'){const d=m.nodes.get(k).depth;if(!spread.has(d))spread.set(d,[]);spread.get(d).push(p.y);}r.priorRankSpread=[...spread].map(([depth,ys])=>({depth,spread:Math.max(...ys)-Math.min(...ys)}));}
 results.push(r);
}
const growth=[];for(const type of ['growth-branch','growth-wide']){let previous;for(let step=0;step<4;step++){const s=A.selection(m,{mode:'fixture:'+type,step}),l=A.layout(m,s,{measure});check(m,s,l);if(previous){const movement=A.movement(previous,l);growth.push({type,step,topics:s.topics.size,average:movement.average,max:movement.max,maxDX:Math.max(...movement.entities.map(e=>Math.abs(e.dx))),maxDY:Math.max(...movement.entities.map(e=>Math.abs(e.dy))),maxCategoryDY:Math.max(...movement.entities.filter(e=>e.key.startsWith('category:')).map(e=>Math.abs(e.dy))),existing:movement.existing});}previous=l;}}
const l=A.layout(m,A.selection(m),{measure,collapsed:new Set(['category:3'])});check(m,A.selection(m),l);
assert.equal(JSON.stringify(geometry),before);fs.writeFileSync(__dirname+'/layout-results.json',JSON.stringify({scenes:results,growth,globalGeometryUnchanged:true,invariants:'PASS SAME_DEPTH_SAME_RANK, PARENT_ABOVE_CHILD, NO_SIBLING_SUBTREE_OVERLAP, NO_CARD_OVERLAP, ORDER_PRESERVED, TOPIC_TRAY_CONTAINMENT, GLOBAL_GEOMETRY_UNCHANGED'},null,2)+'\n');console.log(JSON.stringify({scenes:results,growth,checks:'PASS'},null,2));
