const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const base=path.resolve(__dirname,'..'),out=__dirname,errors=[],shots=[];const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});
try{const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());assert.equal(u.origin,'http://global-atlas.invalid');const key=u.pathname.slice(1)||'index.html';return r.fulfill({body:fs.readFileSync(path.join(base,key)),contentType:key.endsWith('.json')?'application/json':key.endsWith('.js')?'application/javascript':key.endsWith('.css')?'text/css':'text/html'});});
await page.goto('http://global-atlas.invalid/');await page.waitForFunction(()=>window.GlobalAtlas);const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await settle();
await page.evaluate(()=>{window.masterBefore=JSON.stringify(GlobalAtlas.m.geometry);GlobalAtlas.switchScope('global');GlobalAtlas.fitScope();});await settle();
const overview=await page.evaluate(()=>({camera:GlobalAtlas.state().cam,labels:GlobalAtlas.metrics.labelBoxes,rootKeys:GlobalAtlas.m.roots.map(n=>n.key)}));const roots=overview.labels.filter(n=>overview.rootKeys.includes(n.key));assert.equal(roots.length,5);assert.equal(new Set(roots.map(n=>n.y)).size,1);for(let i=0;i<roots.length;i++)for(let j=i+1;j<roots.length;j++)assert(!((roots[i].x<roots[j].x+roots[j].w)&&(roots[i].x+roots[i].w>roots[j].x)));
const shot=async name=>{await settle();const filename=name+'.png';await page.screenshot({path:path.join(out,filename)});shots.push(filename);};await shot('global-overview');
for(const[key,name]of [['category:1162','computer-science'],['category:525','math'],['category:2148','natural-science'],['category:3051','product-development'],['category:4055','generative-ai']]){await page.evaluate(key=>GlobalAtlas.focus(key),key);await shot(name);assert.equal(await page.evaluate(()=>GlobalAtlas.state().selected),key);}
let comparisons=0;for(const mode of ['global','my','course','project']){await page.evaluate(mode=>GlobalAtlas.switchScope(mode,mode==='project'?113:8),mode);await settle();comparisons+=await page.evaluate(()=>{for(const n of GlobalAtlas.m.nodes.values())for(const k of ['x','y','w','h'])assertCoordinate(n[k],n.geometry[k]);return GlobalAtlas.m.nodes.size;function assertCoordinate(a,b){if(a!==b)throw Error('Scope coordinate changed');}});}
assert.equal(await page.evaluate(()=>JSON.stringify(GlobalAtlas.m.geometry)===masterBefore),true);assert.deepEqual(errors,[]);fs.writeFileSync(out+'/browser-results.json',JSON.stringify({viewport:[1440,900],status:'PASS',overview,shots,scopeCoordinateComparisons:comparisons,maximumDisplacementPx:0,errors},null,2)+'\n');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
