const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const{chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const root=process.argv[2],out=__dirname,manifest=JSON.parse(fs.readFileSync(path.join(root,'migration-manifest.json'))),errors=[];
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});
try{const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.route('**/*',r=>{const u=new URL(r.request().url());assert.equal(u.origin,'http://127.0.0.1:8931');let key=u.pathname.slice(1);if(key.endsWith('/'))key+='index.html';const f=path.join(root,key);return r.fulfill({body:fs.readFileSync(f),contentType:key.endsWith('.json')?'application/json':key.endsWith('.js')?'application/javascript':key.endsWith('.css')?'text/css':'text/html'});});
await page.goto('http://127.0.0.1:8931/view/');await page.waitForFunction(()=>window.SpatialReview&&window.MigrationPreview);assert.equal(await page.evaluate(()=>SpatialReview.packageVerified),true);assert.equal(await page.locator('#review-token').inputValue(),manifest.manifest_fingerprint);assert.match(await page.locator('#review-bindings').innerText(),/135 \/ 135 mapped.*46 Categories.*89 Topics/s);
for(const mode of ['current','target','split','overlay'])await page.locator('[data-mode='+mode+']').click();
await page.locator('[data-mode=target]').click();await page.locator('#world').click();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const labels=await page.evaluate(()=>MigrationPreview.performanceData.targetTopLevelLabels);assert.deepEqual(labels.map(b=>b.text),['Hyperskill','Computer science','Math','Natural science','Product development','Generative AI']);assert.ok(labels.every(b=>b.fontSize>=14&&b.lines.join(' ')===b.text));await page.screenshot({path:path.join(out,'target-five-root-overview.png')});assert.equal(await page.evaluate(()=>MigrationPreview.master.geometry_fingerprint),'0946f17af8229463757cda209a1307cd86449bfb5b54258d4aa5f14189310d29');await page.locator('#clear').click();await page.locator('[data-mode=split]').click();await page.locator('#branch').selectOption('category:73');await page.locator('#clear').click();for(const kind of ['category','topic']){await page.locator('#type').selectOption(kind);await page.locator('#largest').selectOption('1');assert.equal(await page.evaluate(()=>MigrationPreview.rows().length),1);await page.locator('#clear').click();}
await page.locator('#scope').selectOption('project');assert.equal(await page.evaluate(()=>MigrationPreview.rows().length),26);await page.locator('#scope').selectOption('stage');assert.equal(await page.evaluate(()=>MigrationPreview.rows().length),12);await page.locator('#clear').click();await page.locator('[data-mode=split]').click();await page.screenshot({path:path.join(out,'review-1440-split.png')});assert.deepEqual(errors,[]);
fs.writeFileSync(path.join(out,'browser-smoke.json'),JSON.stringify({status:'PASS',viewport:[1440,900],packageVerified:true,manifest_fingerprint:manifest.manifest_fingerprint,modes:['current','target','split','overlay'],topLevelLabels:labels,mapped:135,project113:26,stage617:12,errors},null,2)+'\n');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
