const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/home/anton/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict');
function geometry(L){
 const T=AtlasLayout.LAYOUT,rects=[...L.nodes.filter(n=>n.data.type==='category').map(n=>({key:n.key,x:n.x-n.width/2,y:n.y,w:n.width,h:n.height,safe:n.depth<2?24:16})),...L.trays.map(t=>({key:t.parent+' tray',parent:t.parent,x:t.x,y:t.y,w:t.width,h:t.height,safe:20}))];
 const overlaps=[],hits=[],safeHits=[],crossings=[];let clearance=Infinity,cardGap=Infinity,trayGap=Infinity;
 for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i],b=rects[j],dx=Math.max(a.x-b.x-b.w,b.x-a.x-a.w),dy=Math.max(a.y-b.y-b.h,b.y-a.y-a.h);if(dx<-.001&&dy<-.001)overlaps.push([a.key,b.key]);if(dy<0&&dx>=0){if(!a.parent&&!b.parent)cardGap=Math.min(cardGap,dx);if(a.parent&&b.parent)trayGap=Math.min(trayGap,dx);}}
 const segments=L.connectorSegments.flatMap(e=>e.points.slice(1).map((b,i)=>({a:e.points[i],b,parent:e.parent,children:e.children})));
 function distance(e,r){const ex0=Math.min(e.a.x,e.b.x),ex1=Math.max(e.a.x,e.b.x),ey0=Math.min(e.a.y,e.b.y),ey1=Math.max(e.a.y,e.b.y);return Math.hypot(Math.max(r.x-ex1,ex0-r.x-r.w,0),Math.max(r.y-ey1,ey0-r.y-r.h,0));}
 for(const e of segments)for(const r of rects){const interior={...r,x:r.x+.001,y:r.y+.001,w:r.w-.002,h:r.h-.002};if(TreeRouting.segmentHits(e.a,e.b,interior))hits.push([e.parent,r.key]);const own=r.key===e.parent||e.children.includes(r.key)||r.parent===e.parent&&e.children.some(k=>L.byKey.get(k)?.parent===r.parent);if(!own){const d=distance(e,r);clearance=Math.min(clearance,d);if(d<r.safe-.001)safeHits.push([e.parent,r.key,d,r.safe]);}}
 for(let i=0;i<segments.length;i++)for(let j=i+1;j<segments.length;j++){const a=segments[i],b=segments[j];if(a.parent===b.parent)continue;const r={x:Math.min(b.a.x,b.b.x),y:Math.min(b.a.y,b.b.y),w:Math.abs(b.a.x-b.b.x),h:Math.abs(b.a.y-b.b.y)};if(TreeRouting.segmentHits(a.a,a.b,r))crossings.push([a.parent,b.parent]);}
 const rows=L.nodes.filter(n=>n.data.type==='topic');
 for(const n of rows)for(const r of rects){if(r.parent===n.parent)continue;const a={x:n.x-n.width/2,y:n.y,w:n.width,h:n.height};if(a.x<r.x+r.w-.001&&a.x+a.w>r.x+.001&&a.y<r.y+r.h-.001&&a.y+a.h>r.y+.001)overlaps.push([n.key,r.key]);}
 const spacingErrors=[],regionErrors=[],trayPortErrors=[];
 for(const [parent,r]of Object.entries(L.checkpoint.categories)){const slots=r.sibling_order.map(k=>({key:k,...r.children[k],record:L.checkpoint.categories[k]}));for(let i=1;i<slots.length;i++){const a=slots[i-1],b=slots[i],gap=b.x-b.record.anchor-(a.x+a.record.width-a.record.anchor),minimum=L.byKey.get(parent).depth===0?T.majorSiblingGap:T.categorySiblingGap;if(gap<minimum-.001)regionErrors.push([parent,a.key,b.key,gap]);}}
 for(const e of L.branches){const a=L.byKey.get(e.parent),b=L.byKey.get(e.child),minimum=a.depth===0?72:a.depth===1?72:72;if(b.y-a.y-a.height<minimum-.001||b.y-(a.y+a.height+T.parentToBus)<T.busToChild-.001)spacingErrors.push([e.parent,e.child]);}
 for(const t of L.trays){const a=L.byKey.get(t.parent);if(t.y-a.y-a.height<64-.001)spacingErrors.push([t.parent,'tray']);if(!segments.some(e=>e.children.some(k=>t.topics.includes(k))&&[e.a,e.b].some(p=>Math.abs(p.x-t.x-t.width/2)<.001&&Math.abs(p.y-t.y)<.001)))trayPortErrors.push(t.parent);}
 const bounds=AtlasLayout.contentBounds(L,L.nodes);
 return{overlaps,hits,safeHits,crossings,spacingErrors,regionErrors,trayPortErrors,minimumCardGap:cardGap,minimumTrayGap:trayGap,minimumConnectorClearance:clearance,bounds:{width:bounds.x1-bounds.x0,height:bounds.y1-bounds.y0},ports:L.branches.every(e=>{const a=L.byKey.get(e.parent),b=L.byKey.get(e.child);return e.points[0].x===a.x&&e.points[0].y===a.y+a.height&&e.points.at(-1).x===b.x&&e.points.at(-1).y===b.y}),siblings:L.branches.every(e=>e.points.every(p=>p.y>=L.byKey.get(e.parent).y+L.byKey.get(e.parent).height))};
}
(async()=>{const browser=await chromium.launch({executablePath:'/opt/google/chrome/chrome'}),page=await browser.newPage({viewport:{width:1920,height:1080},reducedMotion:'reduce'});await page.goto('http://127.0.0.1:8776');await page.waitForFunction(()=>window.AtlasV6);const inspect=()=>page.evaluate(src=>eval('('+src+')')(AtlasV6.state().L),geometry.toString());const baseline=await inspect();console.log(JSON.stringify(baseline,null,2));
const fixtures=['basics-growth','advanced-oop','databases'].map(name=>({name,raw:JSON.parse(fs.readFileSync(__dirname+'/'+name+'.fixture.json'))}));const growth=await page.evaluate(({fixtures,src})=>{const s=AtlasV6.state();return fixtures.map(({name,raw})=>{const m=AtlasModel.model(raw),L=AtlasLayout.build(m,AtlasV6.measure,s.L.checkpoint);return{name,...eval('('+src+')')(L),moves:s.L.nodes.filter(n=>n.x!==L.byKey.get(n.key).x||n.y!==L.byKey.get(n.key).y).map(n=>n.key),stable:JSON.stringify(L.checkpoint)===JSON.stringify(AtlasLayout.build(m,AtlasV6.measure,L.checkpoint).checkpoint)}})},{fixtures,src:geometry.toString()});console.log(JSON.stringify(growth,null,2));
for(const r of [baseline,...growth]){assert.equal(r.overlaps.length,0);assert.equal(r.hits.length,0);assert.equal(r.safeHits.length,0);assert.equal(r.crossings.length,0);assert.equal(r.spacingErrors.length,0);assert.equal(r.regionErrors.length,0);assert.equal(r.trayPortErrors.length,0);assert.ok(r.ports&&r.siblings);assert.ok(r.minimumCardGap>=56&&r.minimumTrayGap>=48&&r.minimumConnectorClearance>=12);}assert.ok(growth.every(r=>r.stable));
const viewports=[],review=__dirname+'/review/v6.6/spatial';fs.mkdirSync(review,{recursive:true});
for(const width of [1920,1440,1280,1200,1024,768,430,390,320])for(const theme of ['dark','light']){
 await page.setViewportSize({width,height:width===1920?1080:width<500?844:900});await page.evaluate(theme=>{document.body.classList.toggle('light',theme==='light');document.querySelector('#clear').click();AtlasV6.fit();},theme);
 const result=await page.evaluate(()=>{const s=AtlasV6.state(),r=document.querySelector('#graph').getBoundingClientRect(),labels=[...document.querySelectorAll('.node .label')];return{scale:s.transform.k,effectiveTopicFont:14*s.transform.k,topics:document.querySelectorAll('.node.topic').length,categories:document.querySelectorAll('.node.category').length,allLabels:labels.every(t=>t.textContent&&getComputedStyle(t).display!=='none'),allFit:labels.every(t=>{const b=t.getBoundingClientRect();return b.left>=r.left&&b.right<=r.right&&b.top>=r.top&&b.bottom<=r.bottom}),overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(result.allLabels&&result.allFit&&!result.overflow&&result.topics===89&&result.categories===46);viewports.push({width,theme,...result,...baseline});
 if(width===1920&&theme==='dark'||width===1440&&theme==='light'||width===390&&theme==='dark')await page.screenshot({path:review+'/'+width+'-'+theme+'-fit-all.png'});
 if(width===1920&&theme==='dark'){const before=await page.evaluate(()=>{const s=AtlasV6.state();return JSON.stringify({coords:s.L.nodes.map(n=>[n.key,n.x,n.y]),checkpoint:s.L.checkpoint,collapsed:[...s.collapsed],layout:s.metrics.layout})});await page.evaluate(()=>AtlasV6.select('project:113'));assert.equal(await page.locator('.node.topic.covered').count(),26);await page.screenshot({path:review+'/1920-dark-project-113.png'});await page.locator('[data-stage]').filter({hasText:'Stage 4'}).click();assert.equal(await page.locator('.node.topic.covered').count(),12);await page.click('#roadmap');await page.click('#my');assert.equal(await page.evaluate(()=>{const s=AtlasV6.state();return JSON.stringify({coords:s.L.nodes.map(n=>[n.key,n.x,n.y]),checkpoint:s.L.checkpoint,collapsed:[...s.collapsed],layout:s.metrics.layout})}),before);}
 if((width===1920||width===390)&&theme==='dark'){await page.evaluate(()=>{document.querySelector('#clear').click();const s=AtlasV6.state(),n=[...s.m.nodes.values()].find(n=>n.type==='category'&&n.title===(innerWidth<500?'Control flow statements':'Basics'));AtlasV6.select(n.key,true);});await page.click('#fit-subtree');if(width===390){await page.click('#in');await page.mouse.move(195,350);await page.mouse.down();await page.mouse.move(195,430,{steps:5});await page.mouse.up();}await page.screenshot({path:review+'/'+width+'-dark-java-zoom.png'});}
}
fs.writeFileSync(__dirname+'/spatial-results.json',JSON.stringify({baseline,growth,viewports,overviewPrinciple:'Fit-All is an orientation view; the former 10 px Topic-font acceptance is obsolete'},null,2)+'\n');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
