const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/home/anton/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),crypto=require('crypto'),assert=require('assert/strict');
const base=__dirname+'/..',review=__dirname+'/review/v6.6';fs.mkdirSync(review,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:'/opt/google/chrome/chrome'}),checks=[],results={views:[],checks,performance:[]};
 const check=(name,ok)=>{assert.ok(ok,name);checks.push(name)};
 const frozen=await browser.newPage();await frozen.route('**/app.js',r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync(__dirname+'/review/v6.5/frozen/app.js','utf8')}));await frozen.goto('http://127.0.0.1:8776');await frozen.waitForFunction(()=>window.AtlasV6);const coordinates=await frozen.evaluate(()=>AtlasV6.state().L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]));await frozen.close();
 const preserved=fs.readFileSync(__dirname+'/v6.6-preserved-sha256.txt','utf8').trim().split('\n');for(const line of preserved){const [hash,file]=line.split(/\s+/);check('frozen file '+file,crypto.createHash('sha256').update(fs.readFileSync(base+'/'+file)).digest('hex')===hash)}
 for(const width of [1920,1440,1280,1200,1024,768,430,390,320]){
  const page=await browser.newPage({viewport:{width,height:width===1920?1080:width<=430?844:900},isMobile:width<=430,hasTouch:width<=430}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8776');await page.waitForFunction(()=>window.AtlasV6);await page.waitForFunction(()=>!AtlasV6.state().transitioning);
  const stable=await page.evaluate(()=>{const s=AtlasV6.state();return{coordinates:s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]),checkpoint:JSON.stringify(s.L.checkpoint),layout:s.metrics.layout}});assert.deepEqual(stable.coordinates,coordinates);check('V6.5 geometry '+width,true);
  const wait=()=>page.waitForFunction(()=>!AtlasV6.state().transitioning);
  const measure=async(view,title)=>{const row=await page.evaluate(({view,title})=>{
   const s=AtlasV6.state(),r=document.querySelector('#graph').getBoundingClientRect(),key=[...s.m.nodes.values()].find(n=>n.title===title)?.key;const walk=n=>[n.key,...n.children.flatMap(walk)],keys=view==='overview'?new Set(s.visible.map(n=>n.key)):view==='project'?new Set(s.fitIntent.keys):new Set(key?walk(s.m.nodes.get(key)):[]),ns=s.visible.filter(n=>keys.has(n.key));
   const localTray=view==='subtree'&&innerWidth<=700?s.L.trays.find(t=>keys.has(t.parent)):null,localKeys=new Set(localTray?[localTray.parent,...localTray.topics]:[]);
   const b=AtlasLayout.contentBounds(s.L,ns),bounds={left:r.left+b.x0*s.transform.k+s.transform.x,right:r.left+b.x1*s.transform.k+s.transform.x,top:r.top+b.y0*s.transform.k+s.transform.y,bottom:r.top+b.y1*s.transform.k+s.transform.y};const clipped=ns.filter(n=>n.x*s.transform.k+s.transform.x-n.width/2*s.transform.k<0||n.x*s.transform.k+s.transform.x+n.width/2*s.transform.k>r.width||n.y*s.transform.k+s.transform.y<0||(n.y+n.height)*s.transform.k+s.transform.y>r.height).map(n=>n.key);
   return{view,title,scale:s.transform.k,rootFont:28*s.transform.k,majorFont:21*s.transform.k,categoryFont:17*s.transform.k,topicFont:14*s.transform.k,visibleBounds:bounds,mapBounds:{left:r.left,right:r.right,top:r.top,bottom:r.bottom},targetNodes:ns.length,clipped,localReadingClipped:clipped.filter(k=>localKeys.has(k)),topics:document.querySelectorAll('.node.topic').length,categories:document.querySelectorAll('.node.category').length,labels:[...document.querySelectorAll('.node .label')].every(t=>t.textContent&&getComputedStyle(t).display!=='none'&&Number(getComputedStyle(t).opacity)>0),relations:document.querySelectorAll('.knowledge').length,relationsVisible:!!document.querySelector('.knowledge')&&getComputedStyle(document.querySelector('.knowledge').parentNode).display!=='none',overflow:document.documentElement.scrollWidth>innerWidth,viewportState:s.viewState,guideVisible:!document.querySelector('#overview-guide').hidden};
  },{view,title});check('full content '+width+' '+view+' '+title,row.topics===89&&row.categories===46&&row.labels&&!row.overflow);if(view==='overview'||view==='project'||width>700&&view==='subtree')check('complete target bounds '+width+' '+view+' '+title,!row.clipped.length);if(view==='subtree'&&width<=700)check('mobile local reading group fits '+width+' '+title,row.topicFont>=10&&!row.localReadingClipped.length);if(view==='topic')check('readable topic '+width,row.topicFont>=13&&!row.clipped.length);results.views.push({width,theme:await page.evaluate(()=>document.body.classList.contains('light')?'light':'dark'),...row});return row;};
  for(const theme of ['dark','light']){
   await page.evaluate(t=>{document.body.classList.toggle('light',t==='light');document.querySelector('#clear').click();AtlasV6.fit(null,false);},theme);await wait();await measure('overview');if(theme==='dark'||width===1440)await page.screenshot({path:review+'/'+width+'-'+theme+'-overview.png'});
   check('overview relations hidden '+width,await page.evaluate(()=>!document.querySelector('.knowledge')||getComputedStyle(document.querySelector('.knowledge').parentNode).display==='none'));
   for(const title of ['Java','Basics']){await page.evaluate(title=>{const n=[...AtlasV6.state().m.nodes.values()].find(n=>n.type==='category'&&n.title===title);AtlasV6.select(n.key,true);},title);await wait();await measure('subtree',title);if(theme==='dark')await page.screenshot({path:review+'/'+width+'-'+theme+'-'+title.toLowerCase()+'.png'});}
   const started=Date.now();await page.fill('#search','For loop');await page.press('#search','Enter');await wait();await measure('topic','For loop');results.performance.push({width,theme,searchNavigationElapsed:Date.now()-started});check('search no mode change '+width,await page.evaluate(()=>AtlasV6.state().mode==='my'));check('direct relations '+width,await page.evaluate(()=>{const s=AtlasV6.state();return document.querySelectorAll('.knowledge').length===s.m.connections.filter(e=>e.source===s.selected||e.target===s.selected).length&&document.querySelectorAll('.knowledge').length>0}));if(theme==='dark')await page.screenshot({path:review+'/'+width+'-'+theme+'-for-loop.png'});
   const camera=await page.evaluate(()=>[AtlasV6.state().transform.x,AtlasV6.state().transform.y,AtlasV6.state().transform.k]);await page.click('#roadmap');await page.click('#my');await page.click('#theme');await page.click('#theme');assert.deepEqual(await page.evaluate(()=>[AtlasV6.state().transform.x,AtlasV6.state().transform.y,AtlasV6.state().transform.k]),camera);check('mode/theme preserve viewport '+width,true);
   await page.evaluate(()=>{AtlasV6.fit(null,false);AtlasV6.select('project:113')});check('coverage 26 '+width,await page.locator('.node.topic.covered').count()===26);if(theme==='dark'&&width===1920)await page.screenshot({path:review+'/1920-dark-project-overview.png'});const projectCamera=await page.evaluate(()=>[AtlasV6.state().transform.x,AtlasV6.state().transform.y,AtlasV6.state().transform.k]);await page.click('#coverage');await page.click('#coverage');assert.deepEqual(await page.evaluate(()=>[AtlasV6.state().transform.x,AtlasV6.state().transform.y,AtlasV6.state().transform.k]),projectCamera);await page.click('#fit-coverage');await wait();await measure('project');if(theme==='dark')await page.screenshot({path:review+'/'+width+'-'+theme+'-project-fit.png'});await page.locator('[data-stage]').filter({hasText:'Stage 4'}).click();check('stage 4 = 12 '+width,await page.locator('.node.topic.covered').count()===12);
  }
  check('navigation never recomputes layout '+width,await page.evaluate(stable=>{const s=AtlasV6.state();return JSON.stringify(s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]))===JSON.stringify(stable.coordinates)&&JSON.stringify(s.L.checkpoint)===stable.checkpoint&&s.metrics.layout===stable.layout},stable));
  await page.evaluate(()=>document.querySelector('#clear').click());const basics=await page.evaluate(()=>[...AtlasV6.state().m.nodes.values()].find(n=>n.type==='category'&&n.title==='Basics').key);await page.evaluate(k=>AtlasV6.toggle(k),basics);await page.fill('#search','For loop');await page.press('#search','Enter');await wait();check('search reveals manual collapse '+width,await page.evaluate(k=>!AtlasV6.state().collapsed.has(k)&&document.querySelectorAll('.node.topic').length===89,basics));
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>AtlasV6.fit());check('reduced motion instant '+width,await page.evaluate(()=>!AtlasV6.state().transitioning&&AtlasV6.state().viewState==='overview'));
  await page.fill('#search','Basics');await page.press('#search','Enter');await wait();check('category search fits subtree '+width,await page.evaluate(()=>AtlasV6.state().fitIntent?.kind==='subtree'&&AtlasV6.state().m.nodes.get(AtlasV6.state().selected).title==='Basics'));
  results.performance.push({width,metrics:await page.evaluate(()=>AtlasV6.state().metrics)});assert.equal(errors.length,0,errors.join('\n'));await page.close();
 }
 fs.writeFileSync(__dirname+'/viewport-results.json',JSON.stringify(results,null,2)+'\n');console.log({checks:checks.length,views:results.views.length,reading:results.views.filter(x=>x.theme==='dark').map(x=>({width:x.width,view:x.view,title:x.title,font:x.topicFont,clipped:x.clipped.length}))});await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
