/* Final read-only UI QA, using the existing offline Playwright route harness. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),crypto=require('crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const base=path.resolve(__dirname,'..'),out=path.join(__dirname,'final-ux');fs.mkdirSync(out,{recursive:true});
 const baseline=JSON.parse(fs.readFileSync(__dirname+'/final-ux-baseline.json')),hash=()=>crypto.createHash('sha256').update(fs.readFileSync(base+'/generated/global-geometry.json')).digest('hex');assert.equal(hash(),baseline.geometry_sha256);
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})}),results=[];
 try{for(const [width,height]of [[1440,900],[1920,1080],[1024,768]]){
 const page=await browser.newPage({viewport:{width,height},deviceScaleFactor:1}),errors=[],external=[],screens=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url()),key=u.pathname.slice(1)||'index.html';if(u.origin!=='http://global-atlas.invalid'||key.includes('..')){external.push(u.href);return r.abort();}const file=path.join(base,key);if(!fs.existsSync(file))return r.abort();return r.fulfill({body:fs.readFileSync(file),contentType:key.endsWith('.json')?'application/json':key.endsWith('.js')?'application/javascript':key.endsWith('.css')?'text/css':'text/html'});});
 await page.goto('http://global-atlas.invalid/');await page.waitForFunction(()=>window.GlobalAtlas);const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await settle();
 await page.evaluate(()=>{window.finalOriginal=JSON.stringify(GlobalAtlas.m.geometry);window.finalNodeSnapshot=JSON.stringify([...GlobalAtlas.m.nodes.values()].map(n=>[n.key,n.slot,n.x,n.y,n.w,n.h,n.parent,n.sibling_order]));window.finalOperations={};window.finalComparisons=0;});
 const verify=async operation=>{await settle();await page.evaluate(operation=>{const A=GlobalAtlas;if(JSON.stringify(A.m.geometry)!==finalOriginal)throw Error('Master mutated: '+operation);if(JSON.stringify([...A.m.nodes.values()].map(n=>[n.key,n.slot,n.x,n.y,n.w,n.h,n.parent,n.sibling_order]))!==finalNodeSnapshot)throw Error('Node geometry mutated: '+operation);for(const n of A.m.nodes.values()){if(n.x!==n.geometry.x||n.y!==n.geometry.y||n.w!==n.geometry.w||n.h!==n.geometry.h)throw Error('Coordinates differ');finalComparisons++;}finalOperations[operation]=(finalOperations[operation]||0)+1;
 const boxes=A.metrics.labelBoxes;for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)if(PyramidLabels.overlaps(boxes[i],boxes[j],0))throw Error('Overlapping labels');},operation);};
 const shot=async name=>{await verify(name);await page.screenshot({path:path.join(out,`${width}-${name}.png`)});screens.push(`${width}-${name}.png`);};
 const global=await page.evaluate(()=>({...GlobalAtlas.metrics}));assert.equal(global.labelKeys.filter(k=>['category:525','category:1162','category:2148','category:3051','category:4055'].includes(k)).length,5);await shot('global');
 // Tab order and native keyboard activation.
 await page.locator('[data-mode=global]').focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.dataset.mode),'my');await page.keyboard.press('Enter');await verify('keyboard-scope');await page.locator('#fit-scope').focus();await page.keyboard.press('Enter');await shot('my-overview');
 assert.equal(await page.evaluate(()=>GlobalAtlas.state().explicit.length),135);assert.match(await page.locator('#branches').innerText(),/Java.*69 scope Topics.*26 learned.*11 verified/s);assert.equal(await page.locator('#roots .relevant-root').count(),1);
 const my=await page.evaluate(()=>({...GlobalAtlas.metrics}));await page.locator('#region-select').selectOption('category:73');await shot('my-java');assert.equal(await page.locator('#breadcrumbs [aria-current=page]').innerText(),'Java');
 await page.locator('#next-region').focus();await page.keyboard.press('Enter');await shot('my-region-navigation');const region=await page.evaluate(()=>GlobalAtlas.state().regionIndex);await page.keyboard.press('Alt+ArrowLeft');assert.notEqual(await page.evaluate(()=>GlobalAtlas.state().regionIndex),region);await verify('keyboard-region');
 await page.locator('#search').fill('topic:78');await page.locator('#search').press('ArrowDown');assert.match(await page.evaluate(()=>document.activeElement.innerText),/Topic.*active.*Course relevant/s);await page.keyboard.press('Enter');await shot('my-deep-topic');
 await shot('deep-breadcrumb');assert.equal(await page.locator('#breadcrumbs button').count(),4);assert.equal(await page.locator('#breadcrumbs').evaluate(e=>e.scrollWidth<=e.clientWidth),true);await page.locator('#breadcrumbs button[aria-expanded]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#ancestor-jump').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#ancestor-jump').isVisible(),false);await verify('breadcrumb-menu');
 await page.locator('#breadcrumbs button[aria-expanded]').click();await page.locator('#ancestor-jump button').first().focus();await page.keyboard.press('Enter');await verify('breadcrumb-jump');await page.locator('#back').click();assert.equal(await page.evaluate(()=>GlobalAtlas.state().selected),'topic:78');await verify('back-focus');
 await page.locator('#details button').filter({hasText:'category:1265'}).first().focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>GlobalAtlas.state().selected),'category:1265');await verify('inspector-parent');await page.locator('#back').click();assert.equal(await page.evaluate(()=>GlobalAtlas.state().selected),'topic:78');await verify('inspector-back');
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>GlobalAtlas.state().selected),null);await verify('escape-focus');
 await page.locator('[data-mode=course]').click();await page.locator('#fit-scope').click();await shot('course-8');assert.match(await page.locator('#scope-semantics').innerText(),/explicit Course membership.*ancestor context.*learned/);
 await page.locator('[data-mode=project]').click();await page.locator('#fit-scope').click();await shot('project-113');assert.equal(await page.evaluate(()=>GlobalAtlas.state().explicit.length),26);
 await page.locator('#stage').selectOption('617');await page.locator('#fit-scope').click();await shot('stage-617');assert.equal(await page.evaluate(()=>GlobalAtlas.state().explicit.length),12);assert.equal(await page.locator('#stage').getAttribute('class'),'stage-selected');
 await page.locator('#topic-groups').selectOption('category:35');await shot('minimap-narrow');assert.equal(await page.evaluate(()=>GlobalAtlas.metrics.minimap.focus),'category:35');
 await page.locator('#context').selectOption('380');assert.match(await page.locator('#scope-info').innerText(),/UNKNOWN/);assert.equal(await page.locator('#fit-scope').isDisabled(),true);assert.equal(await page.locator('#next-region').isDisabled(),true);await verify('unknown-project');
 await page.locator('[data-mode=my]').click();await page.locator('#search').fill('reference:333');await page.locator('#search').press('Enter');await shot('dormant-reference');assert.equal(await page.evaluate(()=>GlobalAtlas.state().explicit.includes('reference:333')),false);assert.match(await page.locator('#details').innerText(),/does not activate/);
 await page.locator('[data-mode=global]').click();await page.evaluate(()=>{GlobalAtlas.focus('category:3101');GlobalAtlas.zoom(.8/GlobalAtlas.state().cam.k);});await shot('long-label');const long=await page.evaluate(()=>GlobalAtlas.metrics.labelBoxes.find(b=>b.key==='category:3101'));assert(long&&!long.truncated&&long.lines.length>=2);assert.equal(long.lines.join(' '),'Fundamentals of data analysis and business analytics');
 await page.locator('[data-mode=my]').click();await page.locator('#search').fill('topic:147');await verify('search');await page.locator('#search').press('Enter');await verify('long-topic-focus');assert.match(await page.locator('#details h2').innerText(),/Basic literals: numbers, strings and characters/);
 await page.locator('#ghost').selectOption('none');await verify('ghost-none');await page.locator('#ghost').selectOption('local');await verify('ghost-local');await page.locator('#progress').uncheck();await verify('progress-off');await page.locator('#progress').check();await verify('progress-on');
 await page.setViewportSize({width:width-80,height:height-40});await verify('viewport-resize');await page.setViewportSize({width,height});await verify('viewport-restore');
 const perf=await page.evaluate(async()=>{const A=GlobalAtlas,samples={draw:[],scope:[],fit:[],search:[],navigation:[],labels:[]},frame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
 for(let i=0;i<60;i++){A.switchScope(['global','my','course','project'][i%4],i%4===3?113:8,i%8===7?617:null);samples.scope.push(A.metrics.scopeMs);A.fitScope();samples.fit.push(A.metrics.fitScopeMs);A.search(['Java','leaf:333','topic:78'][i%3]);samples.search.push(A.metrics.searchMs);A.navigateRegion(i%2?1:-1);samples.navigation.push(A.metrics.navigationMs);await frame();samples.draw.push(A.metrics.drawMs);samples.labels.push(A.metrics.labelMs);
 if(JSON.stringify(A.m.geometry)!==finalOriginal||JSON.stringify([...A.m.nodes.values()].map(n=>[n.key,n.slot,n.x,n.y,n.w,n.h,n.parent,n.sibling_order]))!==finalNodeSnapshot)throw Error('Repeated operation mutated world');finalComparisons+=A.m.nodes.size;finalOperations.repeated=(finalOperations.repeated||0)+1;}
 const summary=a=>{a.sort((a,b)=>a-b);return{median:a[Math.floor(a.length/2)],p95:a[Math.floor(a.length*.95)]};};return Object.fromEntries(Object.entries(samples).map(([k,a])=>[k+'Ms',summary(a)]));});
 await verify('final');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight),true);assert(perf.drawMs.p95<100);assert(perf.navigationMs.p95<50);
 results.push({viewport:[width,height],global,my,longLabel:long,screenshots:screens,...perf,...await page.evaluate(()=>({comparisons:finalComparisons,operations:finalOperations,heapBytes:performance.memory?.usedJSHeapSize??null,domElements:document.querySelectorAll('*').length})),maximumDisplacementPx:0,keyboardChecks:'PASS native Tab/Enter, search ArrowDown/Enter, breadcrumb menu/jump, Escape, Previous/Next and Alt+arrows',geometryUnchanged:true});await page.close();
 }}finally{await browser.close();}
 assert.equal(hash(),baseline.geometry_sha256);fs.writeFileSync(out+'/browser-results.json',JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results,null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
