const fs=require('fs'),crypto=require('crypto'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||path.resolve('scripts/knowledge_atlas/node_modules/playwright'));
const base=process.env.ATLAS_PREVIEW||'http://127.0.0.1:8807/hyperskill-projects/knowledge-map/';
const canonical=process.env.CANONICAL_METRICS?JSON.parse(fs.readFileSync(process.env.CANONICAL_METRICS)):null;
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.ATLAS_BROWSER_EXECUTABLE?{executablePath:process.env.ATLAS_BROWSER_EXECUTABLE}:{})});const result={browser:browser.version(),source:'335e8ff214886f697ce40ba54f485292f72903c2',canonical:!!canonical,runs:[]};
for(let round=0;round<2;round++){
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(({canonical})=>{window.__measurements={};window.__missing=[];const native=CanvasRenderingContext2D.prototype.measureText;CanvasRenderingContext2D.prototype.measureText=function(text){const m=native.call(this,text),k=JSON.stringify([this.font,String(text)]);window.__measurements[k]=m.width;if(!canonical)return m;if(!(k in canonical)){window.__missing.push(k);return m;}return new Proxy(m,{get:(target,p)=>p==='width'?canonical[k]:Reflect.get(target,p,target)});};},{canonical});
 await context.addInitScript(()=>{const NativeWorker=Worker;window.Worker=class extends NativeWorker{constructor(...args){super(...args);this.addEventListener('message',e=>{if(e.data.__metrics)Object.assign(window.__measurements,e.data.__metrics);if(e.data.__missing)window.__missing.push(...e.data.__missing);});}};});
 await context.route('**/layout-worker.js',async route=>{const response=await route.fetch();const hook=`const __canonical=${JSON.stringify(canonical)},__metrics={},__missing=[];const __native=OffscreenCanvasRenderingContext2D.prototype.measureText;OffscreenCanvasRenderingContext2D.prototype.measureText=function(text){const m=__native.call(this,text),k=JSON.stringify([this.font,String(text)]);__metrics[k]=m.width;if(!__canonical)return m;if(!(k in __canonical)){__missing.push(k);return m;}return new Proxy(m,{get:(target,p)=>p==='width'?__canonical[k]:Reflect.get(target,p,target)});};const __post=self.postMessage.bind(self);self.postMessage=(data)=>__post({...data,__metrics,__missing});\n`;await route.fulfill({response,body:hook+await response.text()});});
 const page=await context.newPage(),runs={};
 for(const [name,query] of [['global',''],['personal','?view=skill-tree'],['course8','?course=8'],['project113','?project=113'],['stage617','?project=113&stage=617']]){
 await page.goto(base+query);await page.waitForFunction(()=>window.AtlasShell&&document.querySelector('#loading').hidden&&AtlasShell.state().activeFrame?.contentWindow.PublicProgress);
 runs[name]=await page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow,L=(w.ScopeApp||w.AtlasV6).state().L;return{geometry:[L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height,n.lines]),L.connectorSegments,L.trays,L.checkpoint],measurements:w.__measurements,missing:w.__missing,environment:{userAgent:w.navigator.userAgent,platform:w.navigator.platform,language:w.navigator.language,viewport:[w.innerWidth,w.innerHeight],dpr:w.devicePixelRatio}};});
 runs[name].hash=crypto.createHash('sha256').update(JSON.stringify(runs[name].geometry)).digest('hex');
 }
 const frame=page.frames().find(f=>f.url().includes('scope-pyramid'));await frame.evaluate(()=>{const s=document.createElement('span');s.id='font-diagnostic';s.textContent='Global Atlas Introduction to Java 123';s.style.font='600 17px system-ui';document.body.appendChild(s);});const client=await context.newCDPSession(page);await client.send('DOM.enable');await client.send('CSS.enable');const doc=await client.send('DOM.getDocument',{depth:-1,pierce:true});function find(n){if(n.attributes?.includes('font-diagnostic'))return n;for(const c of [...n.children||[],...n.contentDocument?[n.contentDocument]:[],...n.shadowRoots||[]]){const r=find(c);if(r)return r;}}const node=find(doc.root);if(node)result.fonts=await client.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});result.runs.push(runs);await context.close();
}await browser.close();fs.mkdirSync(path.dirname(process.env.CAPTURE_OUTPUT),{recursive:true});fs.writeFileSync(process.env.CAPTURE_OUTPUT,JSON.stringify(result)+'\n');console.log(JSON.stringify({browser:result.browser,fonts:result.fonts,runs:result.runs.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,{hash:v.hash,nodes:v.geometry[0].length,measurements:Object.keys(v.measurements).length,missing:v.missing.length}])))}));})().catch(e=>{console.error(e);process.exit(1)});
