/* Current local geometry contract. Same-depth Y and frozen-X assertions from
   the former vertical-composition test are replaced by local row alignment,
   stable canonical order, full contour containment and collision checks. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium,launchOptions}=require('../browser.cjs');
fs.mkdirSync(path.join(__dirname,'../generated'),{recursive:true});
const root=path.resolve(__dirname,'../../../..'),checks=[];const check=(name,ok)=>{assert.ok(ok,name);checks.push(name)};
(async()=>{const browser=await chromium.launch(launchOptions);try{
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.ATLAS_URL||'http://127.0.0.1:8791');await page.waitForFunction(()=>window.AtlasV6);
const result=await page.evaluate(()=>{
 const {m,L,renderer}=AtlasV6.state(),eps=.001,rect=n=>({x:n.x-n.width/2,y:n.y,w:n.width,h:n.height,key:n.key}),overlap=(a,b)=>Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>eps&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>eps;
 const rectangles=L.nodes.map(rect),cards=[],trayHits=[],trayPairs=[],envelopes=[],routes=[],endpoints=[],order=[],alignment=[],textOverflow=[],textOverlap=[],duplicates=[],contourInterlocks=[];
 for(let i=0;i<rectangles.length;i++)for(let j=i+1;j<rectangles.length;j++)if(overlap(rectangles[i],rectangles[j]))cards.push([rectangles[i].key,rectangles[j].key]);
 for(const t of L.trays){const r={x:t.x,y:t.y,w:t.width,h:t.height};for(const c of rectangles)if(!t.topics.includes(c.key)&&overlap(r,c))trayHits.push([t.parent,c.key]);for(const key of t.topics){const c=rect(L.byKey.get(key));if(c.x<r.x||c.x+c.w>r.x+r.w+eps||c.y<r.y||c.y+c.h>r.y+r.h+eps)envelopes.push(['tray',key]);}}
 for(let i=0;i<L.trays.length;i++)for(let j=i+1;j<L.trays.length;j++){const a=L.trays[i],b=L.trays[j];if(overlap({x:a.x,y:a.y,w:a.width,h:a.height},{x:b.x,y:b.y,w:b.width,h:b.height}))trayPairs.push([a.parent,b.parent]);}
 for(const [key,p]of L.plans){for(const r of p.rects)if(r.x<p.left-eps||r.x+r.w>p.right+eps||r.y<0||r.y+r.h>p.height+eps)envelopes.push([key,r.key]);const n=m.nodes.get(key),rec=L.checkpoint.categories[key],cats=n.children.filter(c=>c.type==='category'),actual=rec.routes.rows.flatMap(row=>row.keys).filter(k=>k!=='tray');if(JSON.stringify(actual)!==JSON.stringify(cats.map(c=>c.key)))order.push(key);
  for(const row of rec.routes.rows){const cs=row.keys.filter(k=>k!=='tray').map(k=>L.byKey.get(k));if(cs.some(c=>c.y!==cs[0].y))alignment.push(key);for(let i=1;i<cs.length;i++){if(cs[i].x<=cs[i-1].x)order.push(key);const a=cs[i-1].subtreeBounds,b=cs[i].subtreeBounds;if(a.x1>b.x0+eps)contourInterlocks.push([cs[i-1].key,cs[i].key]);}}
  if(cats.some(c=>L.byKey.get(c.key).y<L.byKey.get(key).y+L.byKey.get(key).height+58-eps))alignment.push(key);
  if(n.children.some(AtlasModel.isLeaf)){const band=L.bands.get(key),expected=n.children.filter(AtlasModel.isLeaf).map(c=>c.key);if(JSON.stringify(band.columns.flatMap(c=>c.keys))!==JSON.stringify(expected))order.push(key);}
 }
 const obstacles=[...rectangles,...L.trays.map(t=>({x:t.x,y:t.y,w:t.width,h:t.height,key:'tray:'+t.parent}))];
 for(const e of L.connectorSegments)for(const r of obstacles){const inner={x:r.x+eps,y:r.y+eps,w:r.w-2*eps,h:r.h-2*eps};if(TreeRouting.polylineHits(e.points,[inner]).length)routes.push([e.parent,r.key]);}
 for(const e of L.branches){const a=L.byKey.get(e.parent),b=L.byKey.get(e.child);if(e.points[0].x!==a.x||Math.abs(e.points[0].y-a.y-a.height)>eps||e.points.at(-1).x!==b.x||e.points.at(-1).y!==b.y)endpoints.push(e.child);}
 for(const t of L.trays){const p=L.byKey.get(t.parent),source={x:p.x,y:p.y+p.height},target={x:t.x+t.width/2,y:t.y},segments=L.connectorSegments.filter(e=>e.parent===t.parent&&e.children.includes(t.topics[0])),has=p=>segments.some(e=>e.points.some(q=>Math.abs(q.x-p.x)<eps&&Math.abs(q.y-p.y)<eps));if(!has(source)||!has(target))endpoints.push(t.parent);}
 const segs=L.connectorSegments;for(let i=0;i<segs.length;i++){const [a,b]=segs[i].points;for(let j=i+1;j<segs.length;j++){const[c,d]=segs[j].points;if(a.x===b.x&&c.x===d.x&&Math.abs(a.x-c.x)<eps&&Math.min(b.y,d.y)-Math.max(a.y,c.y)>eps||a.y===b.y&&c.y===d.y&&Math.abs(a.y-c.y)<eps&&Math.min(b.x,d.x)-Math.max(a.x,c.x)>eps)duplicates.push([i,j]);}}
 for(const e of renderer.scene.entities){for(const c of e.labels){const b=c.bounds;if(b.x0<e.x-eps||b.x1>e.x+e.w+eps||b.y0<e.y-eps||b.y1>e.y+e.h+eps)textOverflow.push({key:e.key,text:c.text,card:e.bounds,textBounds:b});}for(let i=1;i<e.labels.length;i++){const a=e.labels[i-1].bounds,b=e.labels[i].bounds;if(overlap({x:a.x0,y:a.y0,w:a.x1-a.x0,h:a.y1-a.y0},{x:b.x0,y:b.y0,w:b.x1-b.x0,h:b.y1-b.y0}))textOverlap.push(e.key);}}
 const hitFailures=renderer.scene.entities.filter(e=>renderer.hit(e.x+e.w/2,e.y+e.h/2)!==e.key).map(e=>e.key),depthYs={};for(const n of L.nodes.filter(n=>n.data.type==='category'))(depthYs[n.depth]??=new Set()).add(n.y);
 window.validationLayout=L;window.validationScene=renderer.scene;window.validationGeometry=JSON.stringify([L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]),L.connectorSegments]);window.layoutCalls=0;for(const name of ['build','buildOnce','optimize']){const fn=AtlasLayout[name];AtlasLayout[name]=(...args)=>{layoutCalls++;return fn(...args)}}
 return{cards,trayHits,trayPairs,envelopes,routes,endpoints,order,alignment,textOverflow,textOverlap,duplicates,hitFailures,interlocks:contourInterlocks.length,depthYs:Object.fromEntries(Object.entries(depthYs).map(([d,s])=>[d,s.size])),roots:m.root.children.map(n=>L.byKey.get(n.key).y),modelIds:[...m.nodes.keys()].sort(),entityIds:renderer.scene.entities.map(e=>e.key).sort(),learned:[...m.registry.values()].filter(n=>n.is_learned).map(n=>n.key),verified:[...m.registry.values()].filter(n=>n.is_verified).map(n=>n.key),columns:L.trays.reduce((acc,t)=>{const c=L.bands.get(t.parent).columns.length;acc[c]=(acc[c]||0)+1;return acc},{}),modules:[...L.plans].filter(([k,p])=>p.rows.length>1).map(([key,p])=>({key,rows:p.rows.length,width:p.width,height:p.height})),categoryCards:L.nodes.filter(n=>n.data.type==='category').length,leafRows:L.nodes.filter(n=>AtlasModel.isLeaf(n.data)).length,geometryVersion:L.checkpoint.layout_algorithm_version,metrics:AtlasV6.state().metrics,sceneBounds:renderer.scene.bounds,contentBounds:AtlasLayout.contentBounds(L,L.nodes)};
});
fs.writeFileSync(path.join(__dirname,'../generated/local-geometry.json'),JSON.stringify(result,null,2));
for(const field of ['cards','trayHits','trayPairs','envelopes','routes','endpoints','order','alignment','textOverflow','textOverlap','duplicates','hitFailures'])check(field+' empty',result[field].length===0);
assert.deepEqual(result.entityIds,result.modelIds);check('all identities once; 849 categories and 3106 leaf rows',result.categoryCards===849&&result.leafRows===3106&&new Set(result.entityIds).size===3956);check('five roots aligned',result.roots.length===5&&new Set(result.roots).size===1);check('local same-row Y; independent branches may differ at same depth',Object.entries(result.depthYs).some(([d,n])=>+d>1&&n>1));check('real contour interlocking used',result.interlocks>0);check('bounded tray columns',Object.keys(result.columns).every(c=>+c<=3));check('31 learned; 12 verified',result.learned.length===31&&result.verified.length===12);assert.deepEqual(result.sceneBounds,result.contentBounds);check('minimap and scene use current complete bounds',true);
// A tall tray in Bioinformatics must not stretch the independent Biology
// branch. The fixture is an in-memory clone; no catalog/progress file changes.
const isolation=await page.evaluate(()=>{
 const {m,L,renderer}=AtlasV6.state(),raw=structuredClone(m.raw),before=JSON.stringify(m.raw),parent=2263;
 for(let i=0;i<100;i++){const id=900000+i;raw.references.push({id,parent_id:parent,resolution:'UNRESOLVED_REFERENCE'});raw.memberships[id]=[parent];}
 const expanded=AtlasModel.model(raw),probe=AtlasLayout.buildOnce(expanded,AtlasV6.measure),descend=n=>[n,...n.children.flatMap(descend)],biology=descend(m.nodes.get('category:2784')).map(n=>n.key),natural=L.byKey.get('category:2148'),next=probe.byKey.get(natural.key);
 return{grew:probe.bands.get('category:2263').height>L.bands.get('category:2263').height,independent:biology.every(k=>probe.byKey.get(k).y===L.byKey.get(k).y),parentCardUnchanged:natural.width===next.width&&natural.height===next.height&&natural.font===next.font,dataUnchanged:before===JSON.stringify(m.raw),version:renderer.scene.geometryVersion===L.checkpoint.layout_algorithm_version,cacheKeys:[...renderer.cache.keys()].every(k=>k.startsWith(renderer.scene.geometryVersion+':')),indexFailures:renderer.scene.commands.filter((c,i)=>!AtlasTilePaint.query(renderer.scene.tree,c.bounds).includes(i)).length};
});
check('large local tray leaves independent Biology Y unchanged',isolation.grew&&isolation.independent);check('descendant count does not inflate Natural science card',isolation.parentCardUnchanged);check('in-memory fixture leaves catalog unchanged',isolation.dataUnchanged);check('geometry-versioned tiles and rebuilt complete command index',isolation.version&&isolation.cacheKeys&&isolation.indexFailures===0);
await page.evaluate(()=>{window.layoutCalls=0});
const settled=async()=>{await page.waitForFunction(()=>!AtlasV6.state().transitioning);await page.evaluate(()=>AtlasV6.state().renderer.settled())};
for(const key of ['category:2148','category:2180','category:1164']){await page.evaluate(key=>AtlasV6.select(key,true),key);await settled();check('complete subtree fits '+key,await page.evaluate(()=>{const s=AtlasV6.state(),ns=s.L.nodes.filter(n=>s.fitIntent.keys.has(n.key)),b=AtlasLayout.contentBounds(s.L,ns),t=s.transform,r=document.querySelector('#graph');return b.x0*t.k+t.x>=0&&b.x1*t.k+t.x<=r.clientWidth&&b.y0*t.k+t.y>=0&&b.y1*t.k+t.y<=r.clientHeight}));}
await page.evaluate(()=>AtlasV6.focusTopic('topic:518',false));await settled();check('topic focus readable and exact',await page.evaluate(()=>AtlasV6.state().transform.k*14>=15.9));
await page.mouse.move(550,450);await page.mouse.down();await page.mouse.move(690,490,{steps:12});await page.mouse.up();await page.mouse.wheel(0,150);await page.waitForTimeout(250);await settled();
check('pan/zoom preserves layout, scene and indices',await page.evaluate(()=>{const s=AtlasV6.state();return layoutCalls===0&&s.L===validationLayout&&s.renderer.scene===validationScene&&validationGeometry===JSON.stringify([s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]),s.L.connectorSegments])}));check('cache bounded',await page.evaluate(()=>AtlasV6.state().renderer.bytes<=AtlasTiled.memoryCap));check('no browser errors',errors.length===0);
const protectedBefore=JSON.parse(fs.readFileSync(path.join(__dirname,'../protected-source.json')));for(const[file,sha]of Object.entries(protectedBefore))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),sha,file);check('frozen Global runtime and tracked protected source/data files byte-identical',Object.keys(protectedBefore).length>0);
fs.writeFileSync(path.join(__dirname,'../generated/local-geometry.json'),JSON.stringify({...result,isolation,checks,errors},null,2));console.log(checks.length+' focused checks passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
