/* One viewport, label-only QA. No layout generation, approval or apply. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const base=path.resolve(__dirname,'../..'),out=__dirname,errors=[],browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});
try{const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.route('**/*',r=>{const u=new URL(r.request().url());assert.equal(u.origin,'http://global-atlas.invalid');const key=u.pathname.slice(1)||'index.html';return r.fulfill({body:fs.readFileSync(path.join(base,key)),contentType:key.endsWith('.json')?'application/json':key.endsWith('.js')?'application/javascript':key.endsWith('.css')?'text/css':'text/html'});});await page.goto('http://global-atlas.invalid/');await page.waitForFunction(()=>window.GlobalAtlas);
const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await settle();const before=await page.evaluate(()=>JSON.stringify(GlobalAtlas.m.geometry));
const check=async()=>{await settle();const boxes=await page.evaluate(()=>GlobalAtlas.metrics.topLevelLabels);assert.deepEqual(boxes.map(b=>b.text),['Hyperskill','Computer science','Math','Natural science','Product development','Generative AI']);assert.equal(boxes.length,6);assert(boxes.every(b=>b.lines.join(' ')===b.text));assert.equal(new Set(boxes.map(b=>b.key)).size,6);assert(boxes.every(b=>b.fontSize>=14&&b.x>=0&&b.y>=0&&b.x+b.w<=1120));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)assert(!(boxes[i].x<boxes[j].x+boxes[j].w&&boxes[i].x+boxes[i].w>boxes[j].x&&boxes[i].y<boxes[j].y+boxes[j].h&&boxes[i].y+boxes[i].h>boxes[j].y));return boxes;};
await page.evaluate(()=>GlobalAtlas.fitGlobal());await check();await page.evaluate(()=>{GlobalAtlas.focus('category:525');GlobalAtlas.fitGlobal();});await check();await page.evaluate(()=>GlobalAtlas.clearFocus());const labels=await check();assert.equal(await page.evaluate(()=>JSON.stringify(GlobalAtlas.m.geometry)),before);assert.equal(await page.evaluate(()=>GlobalAtlas.m.nodes.has('presentation:hyperskill')),false);
await page.screenshot({path:path.join(base,'root-layout/global-overview-labeled.png')});assert.deepEqual(errors,[]);fs.writeFileSync(out+'/browser-results.json',JSON.stringify({status:'PASS',viewport:[1440,900],labels,fitGlobalSurvivesFocus:true,geometryUnchanged:true,presentationOnly:true,errors},null,2)+'\n');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
