/* One desktop + narrow smoke: persistent Atlas filters and frozen renderers. */
'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{chromium,launchOptions}=require('./browser.cjs');
const base=process.env.ATLAS_SHELL_URL||'http://127.0.0.1:8813/prototypes/knowledge-atlas-navigation/index.html',out=process.env.ATLAS_UNIFIED_AUDIT_DIR||'/tmp/atlas-final-chrome';fs.mkdirSync(out,{recursive:true});
const index=JSON.parse(fs.readFileSync(path.join(__dirname,'../scope-index.json'))),allProjects=index.projects.map(p=>p.scope_id),association=id=>index.course_project_associations.courses.find(c=>c.course_id===id).project_ids;
const hashes={global:'1306993ec8a1b7a80edda4f620fb96ba5d4803c0d81ded334b92efa85cdf1174',personal:'a60fc22e272079c91f39cfed9c01af5865bae29120e6d6f7801b02da96cd6348',course2:'0dcc2984b65d27f08a46d11a9b7fa2b6afb72d127796c4016c6dc3a8299cff6b',course8:'ab8e05971ca8fb9d077b491a766554f5b84118e068433afe4c17faa7e91fb89b',project113:'33dc51873bcbd33fa6ad2de854dd719e525706bdb764a50578570d1f73e89034',stage617:'24edf473c9e97b7ccbb287464302a4bbf6ffadff33efdc265076b5ae6b51455e'};
const ready=(page,type='global',id=null)=>page.waitForFunction(([type,id])=>{const shell=window.AtlasShell?.state();if(!shell?.activeFrame||!document.querySelector('#loading').hidden)return false;const w=shell.activeFrame.contentWindow;if(type==='global')return shell.route.view==='atlas'&&!shell.route.course&&!shell.route.project&&!shell.route.stage&&!!w.AtlasV6?.state().renderer;if(type==='personal')return shell.route.view==='skill-tree'&&!!w.AtlasV6&&!w.AtlasV6.state().renderer;return shell.route.view==='atlas'&&w.ScopeApp?.state().scope?.scope_type===type&&w.ScopeApp.state().scope?.scope_id===id&&!w.ScopeApp.state().busy;},[type,id],{timeout:60000});
const active=page=>page.frameLocator('iframe[data-active=true]');
const options=(page,type)=>page.locator('#'+type+'-choice').evaluate(el=>[...el.options].filter(o=>o.value).map(o=>Number(o.value)));
const geometry=async(page,label)=>{const data=await page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow,L=(w.ScopeApp||w.AtlasV6).state().L;return[L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height,n.lines]),L.connectorSegments,L.trays,L.checkpoint];});const result=crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex');assert.equal(result,hashes[label],label+' frozen geometry');return result;};
const fitSize=page=>page.evaluate(()=>{const f=AtlasShell.state().activeFrame,r=f.getBoundingClientRect(),d=f.contentDocument;return{header:d.querySelector('header').getBoundingClientRect().toJSON(),fit:d.querySelector('#fit').getBoundingClientRect().toJSON(),canvas:d.querySelector('#canvas').getBoundingClientRect().toJSON(),frame:r.toJSON()};});
(async()=>{const browser=await chromium.launch(launchOptions);try{
 const context=await browser.newContext({viewport:{width:1440,height:900}}),errors=[],external=[];
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==new URL(base).origin){external.push(u.origin);return r.abort();}if(u.pathname.endsWith('/favicon.ico'))return r.fulfill({status:204});return r.continue();});
 context.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+new URL(r.url()).pathname);});});
 const page=await context.newPage(),checks=[],measurements=[],geo={};let fixed,globalControl;
 await page.goto(base+'?view=atlas');await ready(page);await page.evaluate(()=>{window.originalNav=document.querySelector('#application-nav');window.originalFilters=document.querySelector('#atlas-filters');window.originalSelectors=['course','project','stage'].map(type=>document.querySelector('#'+type+'-choice'));});
 async function chrome(label){
  const m=await page.evaluate(()=>({nav:document.querySelector('#application-nav').getBoundingClientRect().toJSON(),filters:document.querySelector('#atlas-filters').getBoundingClientRect().toJSON(),fields:['course','project','stage'].map(type=>document.querySelector('#'+type+'-filter').getBoundingClientRect().toJSON()),reset:document.querySelector('#reset-filters').getBoundingClientRect().toJSON(),labels:[...document.querySelectorAll('#application-nav a')].map(a=>a.textContent),persistent:window.originalNav===document.querySelector('#application-nav')&&window.originalFilters===document.querySelector('#atlas-filters')&&window.originalSelectors.every((el,i)=>el===document.querySelector('#'+['course','project','stage'][i]+'-choice')),active:document.querySelector('#application-nav [aria-current=page]')?.dataset.view,visibleMaps:document.querySelectorAll('iframe[data-active=true]').length,duplicateControls:[...document.querySelectorAll('iframe')].reduce((count,f)=>count+f.contentDocument.querySelectorAll('#course-choice,#project-choice,#stage-choice,#application-nav,#top-nav').length,0)}));
  assert(m.persistent);assert.deepEqual(m.labels,['Atlas','My Skill Tree']);assert.equal(m.active,'atlas');assert.equal(m.visibleMaps,1);assert.equal(m.duplicateControls,0);assert.equal(await page.locator('#application-nav [aria-current=page]').count(),1);
  const rects={nav:m.nav,filters:m.filters,fields:m.fields,reset:m.reset};if(!fixed)fixed=rects;else assert.deepEqual(rects,fixed,'fixed Atlas chrome '+label);assert.equal(m.filters.y,44);assert.equal(m.filters.height,64);
  const size=await fitSize(page);assert.equal(size.header.height,0);assert.equal(size.frame.y,108);assert.equal(size.canvas.y,0);
  const button={x:size.frame.x+size.fit.x,y:size.frame.y+size.fit.y,width:size.fit.width,height:size.fit.height};if(!globalControl)globalControl=button;else assert.equal(button.y,globalControl.y,'consistent Fit All baseline');
  measurements.push({label,...m,view:size});
 }
 await chrome('A complete Global');geo.global=await geometry(page,'global');
 const globalData=await page.evaluate(()=>{const s=AtlasShell.state().activeFrame.contentWindow.AtlasV6.state(),entries=[...s.m.registry.values()];return{categories:entries.filter(n=>n.type==='category').length,topics:entries.filter(n=>n.type==='topic').length,keys:entries.map(n=>n.key),globalCounts:s.m.raw.counts,learned:entries.filter(n=>n.is_learned).length,verified:entries.filter(n=>n.is_verified).length};});
 assert.equal(globalData.categories,849);assert.equal(globalData.topics,3106);assert.equal(new Set(globalData.keys).size,3955);assert.equal(globalData.learned,31);assert.equal(globalData.verified,12);assert.deepEqual(await options(page,'project'),allProjects);assert.equal(await page.locator('#course-choice').inputValue(),'');assert(await page.locator('#stage-filter').isHidden());assert.equal(await page.evaluate(()=>[...document.querySelectorAll('iframe')].find(f=>f.contentWindow.ScopeApp).contentWindow.ScopeApp.state().builds),0);checks.push('A: no filters → full 849/3106 Global; 31/12 progress; zero local startup layouts; all 391 Projects');
 await page.locator('#course-search').fill('8');await page.locator('#course-search').press('Enter');await ready(page,'course',8);await chrome('B Course 8');geo.course8=await geometry(page,'course8');assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.ScopeApp.state().scope.explicit_topic_ids.length),89);assert.deepEqual(await options(page,'project'),association(8));checks.push('B: Course 8 → 89 Topics and exact 11 associated Projects');
 await page.locator('#course-choice').selectOption('2');await ready(page,'course',2);await chrome('C Course 2');geo.course2=await geometry(page,'course2');assert.deepEqual(await options(page,'project'),association(2));assert.equal((await options(page,'project')).length,43);checks.push('C: Course 2 local pyramid and exact 43 Projects');
 await page.locator('#course-choice').selectOption('8');await ready(page,'course',8);await page.locator('#project-search').fill('113');await page.locator('#project-search').press('Enter');await ready(page,'project',113);await chrome('D Course 8 + Project 113');geo.project113=await geometry(page,'project113');assert.equal(await page.locator('#course-choice').inputValue(),'8');checks.push('D: Course 8 + Project 113 local scope');
 await page.locator('#course-choice').selectOption('');await ready(page,'project',113);assert.equal(await page.locator('#project-choice').inputValue(),'113');assert.deepEqual(await options(page,'project'),allProjects);await chrome('E direct Project 113');checks.push('E/G: clear Course retains selected Project; unfiltered 391 access');
 const stages=index.stages.filter(s=>s.project_id===113).sort((a,b)=>a.order-b.order||a.scope_id-b.scope_id).map(s=>s.scope_id);assert.deepEqual(await options(page,'stage'),stages);
 await page.locator('#stage-choice').selectOption('617');await ready(page,'stage',617);await chrome('F Stage 617');geo.stage617=await geometry(page,'stage617');checks.push('F: declared Stage 617 scope, exact containment/order');
 const beforeVisit=await page.evaluate(()=>{const s=AtlasShell.state().activeFrame.contentWindow.ScopeApp.state();return{builds:s.builds,geometry:s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]),camera:{x:s.transform.x,y:s.transform.y,k:s.transform.k}};});
 await page.locator('#nav-skill-tree').click();await ready(page,'personal');assert(await page.locator('#course-filter').isHidden());assert(await page.locator('#knowledge-query').isVisible());geo.personal=await geometry(page,'personal');assert.equal(await page.locator('#application-nav [aria-current=page]').getAttribute('data-view'),'skill-tree');
 await page.locator('#nav-atlas').click();await ready(page,'stage',617);await chrome('I return from Skill Tree');assert.deepEqual(await page.evaluate(()=>{const s=AtlasShell.state().activeFrame.contentWindow.ScopeApp.state();return{builds:s.builds,geometry:s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]),camera:{x:s.transform.x,y:s.transform.y,k:s.transform.k}};}),beforeVisit);checks.push('I: Skill Tree return retains Stage selection, camera and cached geometry/build count');
 await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.ScopeApp.select('topic:36'));await active(page).locator('#global-link').click();await ready(page);await chrome('J exact Global identity');assert.equal(new URL(page.url()).searchParams.get('key'),'topic:36');for(const type of ['course','project','stage'])assert.equal(await page.locator('#'+type+'-choice').inputValue(),'');assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().selected),'topic:36');
 await page.goBack();await ready(page,'stage',617);assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.ScopeApp.state().selected),'topic:36');assert(await active(page).locator('#inspector-drawer').isVisible());await page.goForward();await ready(page);assert.equal(new URL(page.url()).searchParams.get('key'),'topic:36');await page.goBack();await ready(page,'stage',617);checks.push('J/K: Show in Global clears scope filters, selects exact Topic ID; Back/Forward restores local Inspector/Topic');
 await page.locator('#stage-choice').selectOption('');await ready(page,'project',113);await page.locator('#project-choice').selectOption('');await ready(page);assert.equal(new URL(page.url()).searchParams.get('view'),'atlas');assert.equal((await page.evaluate(()=>AtlasShell.state().route)).project,undefined);
 await page.locator('#course-choice').selectOption('8');await ready(page,'course',8);await page.locator('#project-choice').selectOption('113');await ready(page,'project',113);await page.locator('#stage-choice').selectOption('617');await ready(page,'stage',617);await page.locator('#project-choice').selectOption('');await ready(page,'course',8);assert.equal(await page.locator('#stage-choice').inputValue(),'');
 await page.locator('#project-choice').selectOption('113');await ready(page,'project',113);await page.locator('#stage-choice').selectOption('617');await ready(page,'stage',617);await page.locator('#course-choice').selectOption('2');await ready(page,'course',2);assert.equal(await page.locator('#project-choice').inputValue(),'');checks.push('G: deepest valid selection, clear Stage/Project/Course, incompatible Course cascading');
 const fitNav=await page.evaluate(()=>AtlasShell.state().nav);await active(page).locator('#fit').click();assert.deepEqual(await page.evaluate(()=>AtlasShell.state().nav),fitNav);await page.locator('#reset-filters').click();await ready(page);await chrome('H Reset full Global');assert.equal((await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().m.registry.size)),3955);checks.push('H: reset filters returns complete Global; Fit All remains camera-only');
 await page.locator('#course-choice').selectOption('31');await ready(page,'course',31);assert.deepEqual(await options(page,'project'),[]);assert.equal(await page.locator('#project-choice option').innerText(),'No projects in this course');
 await page.locator('#reset-filters').click();await ready(page);
 for(const [pid,message] of [[95,'Requirements not established'],[405,'Known empty · No Project study-plan Topics listed']]){await page.locator('#project-choice').selectOption(String(pid));await ready(page,'project',pid);assert.equal(await active(page).locator('#scope-message').innerText(),message);if(pid===95)assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.ScopeApp.state().L),null);await chrome('L Project '+pid);}
 await page.locator('#project-choice').selectOption('113');await ready(page,'project',113);await page.locator('#stage-choice').selectOption('618');await ready(page,'stage',618);assert.equal(await active(page).locator('#scope-message').innerText(),'Known empty · No Stage-local Topics listed');checks.push('L: Course 31 empty associations, UNKNOWN Project 95, empty Project 405 and Stage 618 remain distinct');
 // One desktop visual set: Global + a representative selected local scope.
 await page.locator('#reset-filters').click();await ready(page);await page.screenshot({path:path.join(out,'global.png')});await page.locator('#project-choice').selectOption('113');await ready(page,'project',113);await page.locator('#stage-choice').selectOption('617');await ready(page,'stage',617);await page.screenshot({path:path.join(out,'stage617.png')});

 const drawers=[];
 for(const [label,url,type,id,key] of [['global','?view=atlas','global',null,'topic:36'],['course2','?view=atlas&course=2','course',2,'category:35'],['personal','?view=skill-tree','personal',null,'topic:36']]){
  await page.goto(base+url);await ready(page,type,id);
  const dimensions=()=>page.evaluate(()=>{const f=AtlasShell.state().activeFrame,d=f.contentDocument,w=f.contentWindow,s=(w.ScopeApp||w.AtlasV6).state(),r=e=>e.getBoundingClientRect().toJSON();return{canvas:r(d.querySelector('#canvas')),drawer:r(d.querySelector('aside')),scale:s.transform.k,builds:s.builds,geometry:s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height])};});
  const closed=await dimensions();assert.equal(closed.canvas.width,1440);assert(await active(page).locator('aside').isHidden());
  await page.evaluate(key=>{const w=AtlasShell.state().activeFrame.contentWindow;(w.ScopeApp||w.AtlasV6).select(key);},key);
  await active(page).locator('#fit').click();await active(page).locator('#inspector-toggle').evaluate(el=>{if(getComputedStyle(el).display!=='none')el.click();});
  await page.waitForTimeout(100);const overlay=await dimensions();assert.equal(overlay.canvas.width,1440);assert.equal(overlay.drawer.width,280);assert(await active(page).locator('aside').isVisible());assert.deepEqual(overlay.geometry,closed.geometry);
  await page.screenshot({path:path.join(out,label+'-overlay.png')});await active(page).locator('#inspector-pin').click();await page.waitForTimeout(100);
  const pinned=await dimensions();assert.equal(pinned.canvas.width,1160);assert.equal(pinned.drawer.width,280);assert.deepEqual(pinned.geometry,closed.geometry);assert.equal(pinned.builds,closed.builds);await page.screenshot({path:path.join(out,label+'-pinned.png')});
  await active(page).locator(label==='course2'?'#close':'#inspector-close').click();assert(await active(page).locator('aside').isHidden());assert.equal((await dimensions()).canvas.width,1440);
  await page.evaluate(key=>{const w=AtlasShell.state().activeFrame.contentWindow;const api=w.ScopeApp||w.AtlasV6,s=api.state();api.select([...s.m.nodes.keys()].find(k=>k!==s.selected&&k.startsWith('topic:')));},key);
  await page.waitForTimeout(100);assert(await active(page).locator('aside').isVisible());assert.equal(await active(page).locator('#inspector-pin').getAttribute('aria-pressed'),'true','pin preference retained');
  drawers.push({label,closed,overlay,pinned});
 }
 // Search is grouped in parent chrome and delegates the original result/keyboard contract.
 await page.goto(base+'?view=atlas');await ready(page);assert.equal(await active(page).locator('#overview-guide>div>button').count(),5);assert(await active(page).locator('#overview-guide>span').isHidden());
 await page.locator('#knowledge-query').fill('36');await page.waitForFunction(()=>document.querySelector('#knowledge-results button'));const sourceLabels=await active(page).locator('#results button').allTextContents();assert.deepEqual(await page.locator('#knowledge-results button').allTextContents(),sourceLabels);
 await page.locator('#knowledge-query').press('ArrowDown');assert.equal(await page.locator('#knowledge-results button').first().evaluate(e=>document.activeElement===e),true);await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().selected),'topic:36');assert(await active(page).locator('aside').isVisible());
 await page.locator('#knowledge-query').fill('Java');await page.locator('#knowledge-query').press('Escape');assert.equal(await page.locator('#knowledge-results button').count(),0);
 for(const [url,type,id] of [['?view=skill-tree','personal',null],['?view=atlas&project=113&stage=617','stage',617]]){
  await page.goto(base+url);await ready(page,type,id);await page.locator('#knowledge-query').fill('36');await page.waitForFunction(()=>document.querySelector('#knowledge-results button'));
  assert.deepEqual(await page.locator('#knowledge-results button').allTextContents(),await active(page).locator('#results button').allTextContents());await page.locator('#knowledge-query').press('Enter');assert.equal(await page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow;return(w.ScopeApp||w.AtlasV6).state().selected;}),'topic:36');assert(await active(page).locator('aside').isVisible());
 }
 checks.push('Chrome: hidden embedded headers; one knowledge search preserving source results/keyboard; five compact Global root shortcuts; closed/overlay/pinned Inspector and pin preference; no layout rebuilds');
 fs.writeFileSync(path.join(out,'inspector-results.json'),JSON.stringify(drawers,null,2));
 assert.equal(context.pages().length,1);assert.equal(await page.locator('iframe[data-active=true]').count(),1);assert.equal(await page.locator('iframe').count(),1);
 // Canonical routes and all previous entrypoint/route families normalize safely.
 for(const [url,type,id,key] of [['?view=atlas&course=8','course',8],['?view=atlas&course=8&project=113&stage=617','stage',617],['?view=atlas&project=113','project',113],['?view=global','global'],['?view=courses&scope=course&id=2','course',2],['?view=projects&scope=stage&id=617','stage',617],['?scope=project&id=113','project',113],['?view=personal','personal'],['?view=skill-tree','personal'],['../knowledge-atlas-scope-pyramid/?scope=stage&id=617','stage',617],['../knowledge-atlas-v6-global/','global'],['../knowledge-atlas-v6-skill-tree/','personal'],['../knowledge-atlas-scope-pyramid/global.html?key=category%3A35','global',null,'category:35']]){
  await page.goto(new URL(url,base).href);await ready(page,type,id);assert.equal(new URL(page.url()).pathname,new URL(base).pathname);assert.equal(new URL(page.url()).searchParams.get('view'),type==='personal'?'skill-tree':'atlas');assert.equal(await page.locator('#application-nav a').count(),2);if(key)assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().selected),key);
 }
 checks.push('K: canonical and legacy Global/Course/Project/Stage/Skill Tree/exact Category routes normalize without loops');
 // One narrow viewport, checking fixed rectangles across Global/local changes.
 await page.goto(base+'?view=atlas&project=113&stage=617');await ready(page,'stage',617);await page.setViewportSize({width:480,height:900});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const mobile=await page.evaluate(()=>({nav:document.querySelector('#application-nav').getBoundingClientRect().toJSON(),filters:document.querySelector('#atlas-filters').getBoundingClientRect().toJSON(),fields:['course','project','stage'].map(type=>document.querySelector('#'+type+'-filter').getBoundingClientRect().toJSON())}));assert.equal(mobile.filters.y,44);assert.equal(mobile.filters.height,166);assert(mobile.nav.right<=480);
 await page.locator('#reset-filters').click();await ready(page);assert.deepEqual(await page.evaluate(()=>({nav:document.querySelector('#application-nav').getBoundingClientRect().toJSON(),filters:document.querySelector('#atlas-filters').getBoundingClientRect().toJSON(),fields:['course','project','stage'].map(type=>document.querySelector('#'+type+'-filter').getBoundingClientRect().toJSON())})),mobile);
 await page.locator('#project-choice').selectOption('113');await ready(page,'project',113);await page.locator('#stage-choice').selectOption('617');await ready(page,'stage',617);await active(page).locator('#fit').click();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(out,'narrow.png')});
 const containment=await page.evaluate(()=>{const nodes=[...document.querySelectorAll('#filter-controls input,#filter-controls select,#filter-controls button')].filter(e=>getComputedStyle(e).visibility!=='hidden'&&e.getBoundingClientRect().width);return nodes.every(e=>{const r=e.getBoundingClientRect(),p=e.closest('#filter-controls').getBoundingClientRect();return r.x>=p.x&&r.right<=p.right+1&&r.y>=p.y&&r.bottom<=p.bottom+1;});});assert(containment,'narrow toolbar controls contained without clipping');
 assert.equal(await page.locator('#application-nav a').count(),2);assert.equal(await page.locator('iframe[data-active=true]').count(),1);checks.push('Narrow: persistent two-tab/filter rectangles, conditional Stage slot, no overlap and one active renderer');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 const result={status:'PASS',checks,measurements,geometry_sha256:geo,global_inventory:{categories:globalData.categories,topics:globalData.topics,learned:globalData.learned,verified:globalData.verified},mobile,browser_errors:errors,external_requests:external};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,checks,geometry_sha256:geo,global_inventory:result.global_inventory,browser_errors:errors},null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
