/* Same strict alpha-mask check as the accepted relation review. Bounding-box
   intersections alone do not establish collisions; every shared ink pixel fails. */
module.exports=async function paintedGlyphAudit(){
 const {L}=ScopeApp.state();if(!L)return{labels:0,envelope_intersections:0,shared_ink_pairs:0,positive_control:null,failures:[]};
 const failures=[],check=(v,msg)=>{if(!v)failures.push(msg);},rect=b=>({x:b.x,y:b.y,width:b.width,height:b.height}),over=(a,b)=>Math.min(a.x+a.width,b.x+b.width)>Math.max(a.x,b.x)+.01&&Math.min(a.y+a.height,b.y+b.height)>Math.max(a.y,b.y)+.01;
 const allText=()=>[...document.querySelectorAll('#world .node')].flatMap(el=>{const n=L.byKey.get(el.dataset.key);return[...el.querySelectorAll('text')].map((t,i)=>{const b=t.getBBox(),screen=t.getBoundingClientRect(),ctm=t.getScreenCTM(),style=getComputedStyle(t);return{entity_id:n.key,slot:t.classList.contains('category-coverage')?'category-coverage':'title-line:'+i,text:t.textContent,local_rect:rect(b),world_rect:{x:n.x-n.width/2+b.x,y:n.y+b.y,width:b.width,height:b.height},screen_rect:rect(screen),matrix:{a:ctm.a,b:ctm.b,c:ctm.c,d:ctm.d,e:ctm.e,f:ctm.f},x:t.getAttribute('x'),y:t.getAttribute('y'),style:{font_family:style.fontFamily,font_size:style.fontSize,font_weight:style.fontWeight,letter_spacing:style.letterSpacing,fill:style.fill,text_anchor:style.textAnchor,display:style.display,visibility:style.visibility,opacity:style.opacity},element_id:n.key+'#'+(t.classList.contains('category-coverage')?'category-coverage':'title-line:'+i)};});});
 const fitLabels=allText(),pairs=[];for(let i=0;i<fitLabels.length;i++)for(let j=i+1;j<fitLabels.length;j++)if(over(fitLabels[i].screen_rect,fitLabels[j].screen_rect))pairs.push({a:fitLabels[i],b:fitLabels[j]});
 // Glyph silhouettes use the exact label font/style, effective screen CTM,
 // device-grid-aligned crop, and original fractional positioning. No layout
 // measurement is used as an ink envelope. White is only an alpha mask.
 const enc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 async function ink(label,box){const dpr=devicePixelRatio,c=document.createElement('canvas');c.width=Math.ceil(box.width*dpr);c.height=Math.ceil(box.height*dpr);const ctx=c.getContext('2d',{willReadFrequently:true}),s=label.style,m=label.matrix;
  const markup=`<svg xmlns="http://www.w3.org/2000/svg" width="${box.width}" height="${box.height}" viewBox="0 0 ${box.width} ${box.height}"><g transform="matrix(${m.a} ${m.b} ${m.c} ${m.d} ${m.e-box.x} ${m.f-box.y})"><text x="${label.x}" y="${label.y}" style="font-family:${enc(s.font_family)};font-size:${s.font_size};font-weight:${s.font_weight};letter-spacing:${s.letter_spacing};text-anchor:${s.text_anchor};fill:white">${enc(label.text)}</text></g></svg>`;
  const url=URL.createObjectURL(new Blob([markup],{type:'image/svg+xml'})),image=new Image();try{await new Promise((res,rej)=>{image.onload=res;image.onerror=rej;image.src=url;});ctx.drawImage(image,0,0,c.width,c.height);const data=ctx.getImageData(0,0,c.width,c.height).data;return{data,w:c.width,h:c.height};}finally{URL.revokeObjectURL(url);}}
 for(const pair of pairs){const a=pair.a.screen_rect,b=pair.b.screen_rect,dpr=devicePixelRatio,left=Math.floor((Math.min(a.x,b.x)-2)*dpr)/dpr,top=Math.floor((Math.min(a.y,b.y)-2)*dpr)/dpr,box={x:left,y:top,width:Math.ceil((Math.max(a.x+a.width,b.x+b.width)+2-left)*dpr)/dpr,height:Math.ceil((Math.max(a.y+a.height,b.y+b.height)+2-top)*dpr)/dpr};
  const aa=await ink(pair.a,box),bb=await ink(pair.b,box);if(pair===pairs[0]){const control=await ink(pair.a,box);check(aa.data.some((v,i)=>i%4===3&&v&&control.data[i]),'positive glyph-overlap control');}let shared=0,shared32=0,shared64=0,countA=0,countB=0,maxSharedAlpha=0;for(let i=3;i<aa.data.length;i+=4){const av=aa.data[i],bv=bb.data[i];if(av)countA++;if(bv)countB++;if(av&&bv){shared++;maxSharedAlpha=Math.max(maxSharedAlpha,Math.min(av,bv));if(av>=32&&bv>=32)shared32++;if(av>=64&&bv>=64)shared64++;}}
  pair.ink={shared_nonzero_pixels:shared,shared_pixels_alpha_at_least_32:shared32,shared_pixels_alpha_at_least_64:shared64,min_shared_alpha_peak:maxSharedAlpha,label_a_ink_pixels:countA,label_b_ink_pixels:countB,raster_crop:box};
 }

 check(pairs.every(p=>p.ink.label_a_ink_pixels>0&&p.ink.label_b_ink_pixels>0),'raster labels actually painted');
 check(pairs.every(p=>p.ink.shared_nonzero_pixels===0),'painted-glyph collision');
 return{labels:fitLabels.length,envelope_intersections:pairs.length,shared_ink_pairs:pairs.filter(p=>p.ink.shared_nonzero_pixels).length,positive_control:pairs.length?'PASS':'NO_INTERSECTION',failures};
};
