(function(g){
'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let m,L,selected=null,mode='my',collapsed=new Set(),transform=d3.zoomIdentity,coverage={projectKey:null,enabled:false,stageId:null},visible=[],fitIntent=null;const metrics={},samples={};
const svg=d3.select('#graph'),scene=svg.append('g'),taxonomy=scene.append('g'),relations=scene.append('g'),nodes=scene.append('g'),evidence=scene.append('g');
const zoom=d3.zoom().scaleExtent([.0001,4]).on('zoom',e=>{transform=e.transform;if(e.sourceEvent)fitIntent=null;scene.attr('transform',transform);$('#zoom-value').textContent=(transform.k*100).toFixed(transform.k<.1?1:0)+'%';});svg.call(zoom).on('dblclick.zoom',null);
function timed(name,fn){const t=performance.now(),v=fn();metrics[name]=performance.now()-t;(samples[name]??=[]).push(metrics[name]);return v;}
function descendants(n){return[n,...n.children.flatMap(descendants)];}
function path(n){const out=[];while(n){out.unshift(n.title);n=m.nodes.get('category:'+n.canonical_parent_id);}return out;}
function listButton(key,title){return `<button data-select="${esc(key)}">${esc(title)}</button>`;}
function list(title,items,open=true){return `<details ${open?'open':''}><summary>${esc(title)} (${items.length})</summary><div class="inspector-list">${items.join('')||'<p>None recorded.</p>'}</div></details>`;}
function provenance(ids){return list('Advanced / Evidence',[...new Set(ids||[])].map(id=>{const e=m.raw.evidence.find(e=>e.id===id);return e?`<p>${esc(id)}<br>${esc(e.method)} · ${esc(e.observed_on)}<br>${esc(e.note)}${e.url?`<br><a href="${esc(e.url)}" target="_blank" rel="noopener">Source</a>`:''}</p>`:'';}),false);}
function projection(){return AtlasModel.coverageProjection(m,new Set(visible.map(n=>n.key)),coverage.projectKey,coverage.stageId);}
function paintCoverage(){
 evidence.selectAll('*').remove();const active=coverage.enabled&&coverage.projectKey;scene.classed('coverage-active',!!active);nodes.selectAll('.node,.disclosure').classed('covered',false);nodes.selectAll('.node').attr('aria-label',function(){return this.dataset.baseName;});taxonomy.selectAll('path').classed('covered',false);if(!active)return;
 const p=projection(),ancestors=new Set();for(const key of p.required){let n=m.nodes.get(key);while(n){ancestors.add(n.key);n=m.nodes.get('category:'+n.canonical_parent_id);}}
 nodes.selectAll('.node,.disclosure').classed('covered',function(){return ancestors.has(this.dataset.key);});nodes.selectAll('.node').filter(function(){return p.required.has(this.dataset.key);}).attr('aria-label',function(){return this.dataset.baseName+'; required by selected project';});taxonomy.selectAll('.taxonomy').classed('covered',function(){return ancestors.has(this.dataset.child);});taxonomy.selectAll('.membership').classed('covered',e=>(e.topics||[]).some(key=>p.required.has(key)));
 for(const [key,item] of p.byKey){const n=L.byKey.get(key),group=evidence.append('g').attr('class','evidence').attr('data-key',key).attr('data-count',item.count).attr('transform',`translate(${n.x},${n.y})`);group.append('text').attr('text-anchor','end').attr('x',n.width/2-10).attr('y',item.kind==='topic'?n.height/2+4:n.height-12).text(item.kind==='topic'?'◇':'◇ '+item.count);}
}
function measureObstacles(){return visible.map(n=>({x:n.x-n.width/2,y:n.y,w:n.width,h:n.height,key:n.key,kind:'card'}));}
function renderRelations(){timed('knowledge relation routing',()=>{relations.selectAll('*').remove();if(!selected?.startsWith('topic:'))return;const obstacles=measureObstacles(),ids=new Set(visible.map(n=>n.key)),edges=m.connections.filter(e=>(e.source===selected||e.target===selected)&&ids.has(e.source)&&ids.has(e.target));edges.forEach((e,i)=>relations.append('path').attr('class','knowledge').attr('data-source',e.source).attr('data-target',e.target).attr('d',AtlasRouting.route(L.byKey.get(e.source),L.byKey.get(e.target),i,obstacles.filter(r=>r.kind!=='node'||(r.key!==e.source&&r.key!==e.target)))).attr('marker-end','url(#arrow)').append('title').text(m.nodes.get(e.source).title+' → '+m.nodes.get(e.target).title));});}
function inspect(){let html='',n=m.nodes.get(selected);if(!selected){const course=m.raw.courses[0],topics=[...m.nodes.values()].filter(n=>n.type==='topic');html=`<p>Course</p><h2>${esc(course.title)}</h2><p class="stat">${topics.length} topics</p><p>${topics.filter(n=>n.is_learned).length} learned · ${topics.filter(n=>n.is_verified).length} verified</p><h3>Project Evidence</h3><div class="inspector-list">${m.raw.projects.filter(p=>m.raw.progress.projects.some(v=>v.project_id===p.id)).map(p=>listButton('project:'+p.id,'◇ '+p.title)).join('')}</div>${list('Course project catalogue',m.raw.projects.filter(p=>!m.raw.progress.projects.some(v=>v.project_id===p.id)).map(p=>listButton('project:'+p.id,'◇ '+p.title)),false)}<p class="legend">● Learned · ◎ Verified<br>○ Not learned · ◌ Unknown<br>◇ Project evidence / requirement<br>Slate branches: taxonomy<br>Mint arrows: prerequisite → dependent</p><p>Complete taxonomy. Zoom in to read; select to inspect.</p>`;}
else if(n){html=`<h2>${esc(n.title)}</h2><p class="path">${path(n).map(esc).join(' &gt; ')}</p>`;if(n.type==='category'){const ts=descendants(n).filter(n=>n.type==='topic'),cats=n.children.filter(n=>n.type==='category');html+=`<p>${cats.length} child categories<br>${n.children.filter(n=>n.type==='topic').length} direct topics<br>${ts.length} descendant topics<br>${ts.filter(n=>n.is_learned).length} learned · ${ts.filter(n=>n.is_verified).length} verified<br>${ts.filter(n=>m.raw.courses[0].topic_ids.includes(n.id)).length} course topics</p>`;if(coverage.enabled)html+=`<p>◇ ${ts.filter(t=>projection().required.has(t.key)).length} required topics in this subtree</p>`;html+=list('Child Categories',cats.map(c=>listButton(c.key,c.title)))+provenance(n.evidence_ids);}
else{const edges=m.connections.filter(e=>e.source===n.key||e.target===n.key),req=m.raw.edges.filter(e=>e.type==='project_requires'&&e.target===n.key);html+=`<p>${n.is_learned===true?'● Learned':n.is_learned===false?'○ Not learned':'◌ Unknown'}${n.is_verified?' · ◎ Verified':''}<br>Verification: ${n.observations.map(o=>esc(o.verification_status)).join(', ')||'unknown'}</p>`+list('Prerequisites',edges.filter(e=>e.target===n.key).map(e=>listButton(e.source,m.nodes.get(e.source).title)))+list('Dependents',edges.filter(e=>e.source===n.key).map(e=>listButton(e.target,m.nodes.get(e.target).title)))+list('Project Evidence',req.map(e=>{const p=m.raw.projects.find(p=>'project:'+p.id===e.source),s=m.raw.stages.find(s=>s.id===e.stage_id);return listButton(e.source,p.title)+`<p>Required by project${s?' · Stage '+s.position+' — '+esc(s.title):''}</p>`;}))+`<p><a href="${esc(n.url)}" target="_blank" rel="noopener">Open in Hyperskill ↗</a></p>`+list('Additional taxonomy memberships',m.raw.edges.filter(e=>e.type==='hierarchy'&&e.target===n.key&&e.source!=='category:'+n.canonical_parent_id).map(e=>listButton(e.source,m.nodes.get(e.source).title)),false)+provenance([...n.evidence_ids,...n.observations.flatMap(o=>o.evidence_ids),...edges.flatMap(e=>e.evidence.flatMap(v=>v.evidence_ids)),...req.flatMap(e=>e.evidence_ids)]);}}
else{const p=m.raw.projects.find(p=>'project:'+p.id===selected),pr=m.raw.progress.projects.find(v=>v.project_id===p.id),ss=m.raw.stages.filter(s=>s.project_id===p.id).sort((a,b)=>a.position-b.position),req=AtlasModel.projectRequirements(m,selected),known=ss.length>0,completed=pr?.completed_stage_ids;html=`<h2>${esc(p.title)}</h2><p>Status: ${esc(pr?.status||'available')}<br>Stage count: ${p.stage_ids.length}<br>Required topic count: ${known?req.size:'unknown'}<br>Completed stage state: ${completed==null?'unknown':completed.length?completed.map(esc).join(', '):'[] — no completed stages recorded'}</p>${p.description?`<p>${esc(p.description)}</p>`:''}`;if(known){html+=`<div class="actions"><button id="coverage" aria-pressed="${coverage.enabled}">${coverage.enabled?'Hide':'Show'} project coverage</button><button id="fit-coverage">Fit project coverage</button>${[...req].some(key=>!visible.some(n=>n.key===key))?'<button id="reveal">Reveal required topics</button>':''}</div><h3>Stages · explicit new requirements</h3><div class="actions"><button data-stage="all" aria-pressed="${coverage.stageId==null}">All project requirements (${req.size})</button>${ss.map(s=>`<button data-stage="${s.id}" aria-pressed="${coverage.stageId===s.id}">Stage ${s.position} · ${esc(s.title)} (${AtlasModel.projectRequirements(m,selected,s.id).size})</button>`).join('')}</div>`+list('Required Topics',[...req].map(key=>listButton(key,m.nodes.get(key).title)),false);}else html+='<p>Stage requirements have not been loaded.</p>';html+=`<p><a href="${esc(p.url)}" target="_blank" rel="noopener">Open in Hyperskill ↗</a></p>`+provenance(p.evidence_ids);}
$('#inspector').innerHTML=html;$('#inspector').querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>select(b.dataset.select,true));$('#coverage')?.addEventListener('click',()=>{coverage.enabled=!coverage.enabled;paintCoverage();inspect();});$('#fit-coverage')?.addEventListener('click',()=>fit(new Set(projection().byKey.keys())));$('#reveal')?.addEventListener('click',()=>{for(const key of AtlasModel.projectRequirements(m,selected))reveal(key);draw();});$('#inspector').querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{coverage.stageId=b.dataset.stage==='all'?null:Number(b.dataset.stage);coverage.enabled=true;paintCoverage();inspect();});}
function draw(){
 visible=AtlasLayout.visible(L,m,collapsed);const keys=new Set(visible.map(n=>n.key)),neighbors=new Set(m.connections.filter(e=>e.source===selected||e.target===selected).flatMap(e=>[e.source,e.target]));taxonomy.selectAll('*').remove();
 for(const e of L.branches.filter(e=>keys.has(e.parent)&&keys.has(e.child)))taxonomy.append('path').attr('class','taxonomy').attr('data-child',e.child).attr('d',e.d);
 for(const e of L.buses.filter(e=>keys.has(e.parent)&&!collapsed.has(e.parent)&&(!e.topic||keys.has(e.topic))))taxonomy.append('path').attr('class','membership').attr('data-parent',e.parent).datum(e).attr('d',e.d);
 nodes.selectAll('*').remove();for(const n of visible){const d=n.data,isTopic=d.type==='topic',baseName=d.title+'; '+d.type+'; '+path(d).join(' > ')+(isTopic?'; '+(d.is_learned?'learned':d.is_learned===false?'not learned':'unknown')+(d.is_verified?'; verified':''):''),group=nodes.append('g').attr('class',`node ${d.type} depth-${n.depth} ${d.is_learned?'learned':d.is_learned==null?'unknown':''} ${selected===d.key?'selected':''} ${neighbors.has(d.key)?'neighbor':''}`).attr('data-key',d.key).attr('data-x',n.x).attr('data-y',n.y).attr('data-base-name',baseName).attr('transform',`translate(${n.x},${n.y})`).attr('tabindex',0).attr('role','button').attr('aria-pressed',selected===d.key).attr('aria-label',baseName);
 group.on('click',e=>{e.stopPropagation();select(d.key);}).on('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(d.key);}});
 group.append('rect').attr('class','card').attr('x',-n.width/2).attr('y',0).attr('width',n.width).attr('height',n.height).attr('rx',isTopic?4:5);
 if(isTopic){group.append('circle').attr('class','core').attr('cx',-n.width/2+14).attr('cy',n.height/2).attr('r',4);if(d.is_verified)group.append('circle').attr('class','ring').attr('cx',-n.width/2+14).attr('cy',n.height/2).attr('r',7);}
 const tx=-n.width/2+(isTopic?28:34),ty=isTopic?n.height/2-(n.lines.length-1)*n.line/2+n.font*.35:(n.depth>=2?5:8)+n.font,label=group.append('text').attr('class','label').attr('x',tx).attr('y',ty).style('font-size',n.font+'px');n.lines.forEach((l,i)=>label.append('tspan').attr('x',tx).attr('dy',i?n.line:0).text(l));
 if(!isTopic){const ts=descendants(d).filter(t=>t.type==='topic');group.append('text').attr('class','category-coverage').attr('x',tx).attr('y',n.height-7).text(ts.filter(t=>t.is_learned).length+' / '+ts.length+' learned');if(d.children.length){const disclosure=nodes.append('g').attr('class','disclosure').attr('data-key',d.key).attr('transform',`translate(${n.x-n.width/2+15},${n.y+n.height/2})`).attr('tabindex',0).attr('role','button').attr('aria-label',(collapsed.has(d.key)?'Expand ':'Collapse ')+d.title).attr('aria-expanded',!collapsed.has(d.key)).on('click',e=>{e.stopPropagation();toggle(d.key);}).on('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();toggle(d.key);}});disclosure.append('rect').attr('x',-13).attr('y',-16).attr('width',26).attr('height',32).attr('rx',3).attr('fill','transparent');disclosure.append('text').attr('text-anchor','middle').attr('y',5).text(collapsed.has(d.key)?'▸':'▾');}}
 }
 $('#canvas').classList.toggle('roadmap',mode==='roadmap');paintCoverage();renderRelations();inspect();}
function reveal(key){let n=m.nodes.get(key);while(n){collapsed.delete(n.key);n=m.nodes.get('category:'+n.canonical_parent_id);}}
function select(key,navigate=false){const restoreFocus=document.activeElement?.classList.contains('node');timed('topic selection',()=>{if(key.startsWith('project:'))coverage={projectKey:key,enabled:AtlasModel.projectRequirements(m,key).size>0,stageId:null};selected=key;if(navigate&&m.nodes.has(key))reveal(key);draw();if(restoreFocus)nodes.selectAll('.node').filter(function(){return this.dataset.key===key;}).node()?.focus();if(navigate&&m.nodes.has(key)){fitIntent=null;const n=L.byKey.get(key),r=$('#graph').getBoundingClientRect(),k=Math.min(1.6,(n.data.type==='topic'?17:24)/n.font,(r.width-60)/n.width,(r.height-120)/n.height);svg.call(zoom.transform,d3.zoomIdentity.translate(r.width/2-(n.x)*k,r.height/2-(n.y+n.height/2)*k).scale(k));}$('#announcement').textContent='Selected '+(m.nodes.get(key)?.title||m.raw.projects.find(p=>'project:'+p.id===key)?.title);});}
function toggle(key){const focus=document.activeElement?.classList.contains('disclosure');collapsed.has(key)?collapsed.delete(key):collapsed.add(key);draw();if(focus)nodes.selectAll('.disclosure').filter(function(){return this.dataset.key===key;}).node()?.focus();}
function fit(keys){timed('Fit all',()=>{const ns=visible.filter(n=>!keys||keys.has(n.key));if(!ns.length)return;const b=AtlasLayout.contentBounds(L,ns),r=$('#graph').getBoundingClientRect(),k=Math.min(1.3,(r.width-30)/(b.x1-b.x0),(r.height-84)/(b.y1-b.y0));svg.call(zoom.transform,d3.zoomIdentity.translate(r.width/2-(b.x0+b.x1)/2*k,(r.height+32)/2-(b.y0+b.y1)/2*k).scale(k));fitIntent={keys:keys?new Set(keys):null};});}
function setMode(v){mode=v;$('#my').setAttribute('aria-pressed',v==='my');$('#roadmap').setAttribute('aria-pressed',v==='roadmap');const ts=m.raw.topics,learned=[...m.nodes.values()].filter(n=>n.type==='topic'&&n.is_learned).length,verified=[...m.nodes.values()].filter(n=>n.type==='topic'&&n.is_verified).length;$('#mode-summary').textContent=`${v==='my'?'My Knowledge':'Course Roadmap'} · ${ts.length} topics · ${learned} learned · ${v==='my'?verified+' verified':(ts.length-learned)+' to learn'}`;$('#canvas').classList.toggle('roadmap',v==='roadmap');}
async function init(){const text=await(await fetch('model.json')).text();let raw;m=timed('model parse',()=>{raw=JSON.parse(text);return AtlasModel.model(raw);});const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.font=AtlasLayout.FONT;const measure=(t,font=14,weight=400)=>{ctx.font=weight+' '+font+'px system-ui';return ctx.measureText(t).width;};let checkpoint=null;const response=await fetch('layout-checkpoint.json');if(response.ok)checkpoint=await response.json();L=timed('layout',()=>AtlasLayout.build(m,measure,checkpoint));svg.append('defs').append('marker').attr('id','arrow').attr('viewBox','0 -4 10 8').attr('refX',10).attr('markerWidth',7).attr('markerHeight',7).attr('orient','auto').append('path').attr('d','M0,-4L10,0L0,4').attr('fill','var(--mint)');$('#counts').textContent=`${raw.topics.length} topics · ${raw.categories.length} categories · ${m.connections.length} knowledge relations`;setMode('my');timed('initial render',draw);fit();$('#my').onclick=()=>setMode('my');$('#roadmap').onclick=()=>setMode('roadmap');$('#fit').onclick=()=>fit();$('#fit-subtree').onclick=()=>fit(m.nodes.has(selected)?new Set(descendants(m.nodes.get(selected)).map(n=>n.key)):null);$('#in').onclick=()=>{fitIntent=null;svg.call(zoom.scaleBy,1.4);};$('#out').onclick=()=>{fitIntent=null;svg.call(zoom.scaleBy,1/1.4);};$('#theme').onclick=()=>document.body.classList.toggle('light');$('#clear').onclick=()=>{selected=null;coverage={projectKey:null,enabled:false,stageId:null};draw();};$('#search').oninput=()=>timed('search',()=>{const q=$('#search').value.trim().toLowerCase(),all=[...m.nodes.values(),...m.raw.projects.map(p=>({...p,key:'project:'+p.id}))],matches=q?all.filter(n=>n.title.toLowerCase().includes(q)).sort((a,b)=>(a.title.toLowerCase()===q?-1:0)-(b.title.toLowerCase()===q?-1:0)||a.id-b.id).slice(0,12):[];$('#results').innerHTML=matches.map(n=>listButton(n.key,n.title)).join('')||(q?'<p>No matching knowledge.</p>':'');$('#results').querySelectorAll('button').forEach(b=>b.onclick=()=>{select(b.dataset.select,true);$('#results').replaceChildren();});});$('#search').onkeydown=e=>{if(e.key==='Enter')$('#results button')?.click();if(e.key==='ArrowDown'){e.preventDefault();$('#results button')?.focus();}if(e.key==='Escape')$('#results').replaceChildren();};let first=true;new ResizeObserver(()=>{if(first){first=false;return;}if(fitIntent)fit(fitIntent.keys);}).observe($('#canvas'));
 g.AtlasV6={setCoverage:(enabled)=>{coverage.enabled=enabled;paintCoverage();inspect();},state:()=>({m,L,selected,mode,collapsed,transform,coverage,metrics,samples,visible}),select,toggle,fit,setMode,projection,measure,draw};}
init().catch(e=>{$('#error').textContent='Could not load prototype: '+e.message;console.error(e);});
})(globalThis);
