/* Phase 1: exact real review bytes only. No approval or publication API. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const[reviewRoot]=process.argv.slice(2),out=__dirname,results=[],browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/opt/google/chrome/chrome'});const manifest=JSON.parse(fs.readFileSync(path.join(reviewRoot,'migration-manifest.json')));
async function pageFor(base,width,height,corrupt=false){const page=await browser.newPage({viewport:{width,height},deviceScaleFactor:1}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.route('**/*',r=>{const u=new URL(r.request().url()),key=(u.pathname.endsWith('/')?u.pathname+'index.html':u.pathname).slice(1)||'index.html';if(u.origin!=='http://127.0.0.1:8931'||key.includes('..')){external.push(u.href);return r.abort();}const file=path.join(base,key);if(!fs.existsSync(file))return r.abort();let body=fs.readFileSync(file);if(corrupt&&key==='target-geometry.json')body=Buffer.concat([body,Buffer.from(' ')]);return r.fulfill({body,contentType:key.endsWith('.json')?'application/json':key.endsWith('.js')?'application/javascript':key.endsWith('.css')?'text/css':'text/html'});});return{page,errors,external};}
const settle=page=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
try{for(const[width,height]of [[1440,900],[1920,1080],[1024,768]]){
 const {page,errors,external}=await pageFor(reviewRoot,width,height);await page.goto('http://127.0.0.1:8931/view/');await page.waitForFunction(()=>window.SpatialReview&&window.MigrationPreview);await settle(page);assert.equal(await page.locator('#review-token').inputValue(),manifest.manifest_fingerprint);assert.match(await page.locator('#review-bindings').innerText(),/135 \/ 135 mapped.*46 Categories.*89 Topics/s);assert.equal(await page.evaluate(()=>SpatialReview.packageVerified),true);
 const original=await page.evaluate(()=>JSON.stringify([MigrationPreview.current,MigrationPreview.target,MigrationPreview.master,MigrationPreview.semantic]));let comparisons=0;const screenshots=[];
 const verify=async()=>{await settle(page);assert.equal(await page.evaluate(()=>JSON.stringify([MigrationPreview.current,MigrationPreview.target,MigrationPreview.master,MigrationPreview.semantic])),original);comparisons+=await page.evaluate(()=>{const slots=new Map(MigrationPreview.master.positions.map(p=>[p.key,p]));for(const n of MigrationPreview.target.positions)for(const k of['x','y','w','h'])if(n[k]!==slots.get(n.slot)[k])throw Error('Canonical coordinate mismatch');return MigrationPreview.target.positions.length;});};
 const shot=async scene=>{await verify();const name=`review-${width}-${scene}.png`;await page.screenshot({path:path.join(out,name)});screenshots.push(name);};
 for(const mode of ['current','target','split','overlay']){await page.locator('[data-mode='+mode+']').click();await shot(mode);}await page.locator('[data-mode=split]').click();await page.locator('#branch').selectOption('category:73');await shot('java');await page.locator('#clear').click();await page.locator('#scope').selectOption('project');assert.equal(await page.evaluate(()=>MigrationPreview.rows().length),26);await verify();await page.locator('#scope').selectOption('stage');assert.equal(await page.evaluate(()=>MigrationPreview.rows().length),12);await shot('stage-617');
 await page.locator('#clear').click();for(const type of ['category','topic']){await page.locator('#type').selectOption(type);await page.locator('#largest').selectOption('1');const key=await page.evaluate(()=>MigrationPreview.rows()[0].key);await page.locator('#entity').selectOption(key);await shot('largest-'+type);await page.locator('#clear').click();}
 await page.locator('#entity').selectOption('topic:36');await page.locator('[data-mode=overlay]').focus();await page.keyboard.press('Enter');await shot('vector');await page.keyboard.press('Escape');await verify();await page.locator('#copy-token').click();assert.equal(await page.locator('#review-token').inputValue(),manifest.manifest_fingerprint);await shot('token');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);results.push({kind:'exact-review',viewport:[width,height],comparisons,packageVerified:true,fingerprint:manifest.manifest_fingerprint,screenshots,errors,external});await page.close();

 }
 const {page}=await pageFor(reviewRoot,1440,900,true);await page.goto('http://127.0.0.1:8931/view/');await page.waitForFunction(()=>document.querySelector('.ready').textContent==='STALE_SPATIAL_MIGRATION_PREVIEW');assert.equal(await page.evaluate(()=>Boolean(window.MigrationPreview)),false);results.push({kind:'corrupt-review-artifact',status:'BLOCKED_BEFORE_COMPARISON'});await page.close();
}finally{await browser.close();}fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results.map(r=>({kind:r.kind,viewport:r.viewport,status:r.status||'PASS'}))));})().catch(e=>{console.error(e);process.exitCode=1;});
