'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium,launchOptions}=require('../../knowledge-atlas-scope-pyramid/tests/browser.cjs');
const out=path.join(__dirname,'progress-review');fs.mkdirSync(out,{recursive:true});
const base='http://127.0.0.1:8798/prototypes/knowledge-atlas-navigation/index.html?view=skill-tree';
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
(async()=>{const browser=await chromium.launch(launchOptions);
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[],external=[],checks=[];
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==new URL(base).origin){external.push(u.href);return r.abort();}if(u.pathname.endsWith('/favicon.ico'))return r.fulfill({status:204});return r.continue();});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);
 await page.waitForFunction(()=>AtlasShell.state().activeFrame?.contentWindow.SkillProgress&&document.querySelector('#loading').hidden);
 const frame=page.frameLocator('iframe[data-active=true]');
 const geometry=()=>page.evaluate(()=>{const s=AtlasShell.state().activeFrame.contentWindow.AtlasV6.state(),L=s.L;return[L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height,n.lines]),L.connectorSegments,L.trays,L.checkpoint];});
 const original=hash(await geometry());assert.equal(original,'a60fc22e272079c91f39cfed9c01af5865bae29120e6d6f7801b02da96cd6348');
 await page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow;w.progressBuilds=0;const build=w.AtlasLayout.build;w.AtlasLayout.build=(...args)=>{w.progressBuilds++;return build(...args)};w.progressNodes=[...w.document.querySelectorAll('#graph .node')];});
 assert.deepEqual(await page.locator('#application-nav a').allTextContents(),['Atlas','My Skill Tree']);
 await frame.locator('#progress-overview').getByText('31 / 3,106').waitFor();await page.screenshot({path:path.join(out,'1-overview.png')});
 await frame.locator('#progress-expand').click();await frame.locator('#progress-panel details[data-progress-details] > summary').click();assert.match(await frame.locator('#progress-panel').innerText(),/3,017 unknown/);assert.match(await frame.locator('#progress-panel').innerText(),/58 explicitly not learned/);
 await page.screenshot({path:path.join(out,'3-course-progress.png')});
 await frame.locator('#progress-project').selectOption('113');await frame.locator('#progress-stage').selectOption('617');
 const text=await frame.locator('#progress-panel').innerText();assert.match(text,/26 \/ 26 learned/);assert.match(text,/12 \/ 12 learned/);assert.match(text,/10 verified/);assert.match(text,/7 verified/);assert.match(text,/Completed/);assert.doesNotMatch(text,/Not recorded/);
 await page.screenshot({path:path.join(out,'4-project-stage-progress.png')});
 await frame.locator('#progress-project').selectOption('229');assert.match(await frame.locator('#progress-panel').innerText(),/Requirements unknown/);
 await frame.locator('#progress-project').selectOption('405');assert.match(await frame.locator('#progress-panel').innerText(),/No required Topics/);
 await frame.locator('#progress-project').selectOption('33');await frame.locator('#progress-stage').selectOption('179');assert.match(await frame.locator('#progress-panel').innerText(),/No required Topics/);
 await frame.locator('#progress-course').selectOption('2');await frame.locator('#progress-panel details[data-progress-details] > summary').click();assert.match(await frame.locator('#progress-panel').innerText(),/Official Hyperskill: No complete Course snapshot/);
 await frame.locator('#progress-course').selectOption('8');await frame.locator('#progress-close').click();
 await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.select('category:73',false));
 await frame.locator('.category-progress').getByText('26 / 297 learned').waitFor();assert.match(await frame.locator('.category-progress').innerText(),/26 \/ 69 learned/);
 await frame.locator('#progress-expand').click();
 const emptyCourse=await page.evaluate(()=>{const a=AtlasShell.state().activeFrame.contentWindow.SkillProgress.analytics;return [...a.scopeMaps.course.keys()].find(id=>a.category(73,id).eligible===0);});
 assert(emptyCourse);await frame.locator('#progress-course').selectOption(String(emptyCourse));
 assert.match(await frame.locator('.category-progress').innerText(),/No Topics/);
 await frame.locator('#progress-course').selectOption('8');await frame.locator('#progress-close').click();
 await frame.locator('.category-progress').getByText('26 / 69 learned').waitFor();
 await page.screenshot({path:path.join(out,'2-java-inspector.png')});
 await frame.locator('#inspector-pin').click();await frame.locator('#inspector-pin').click();
 const child='252';
 await frame.locator('[data-progress-category="252"]').click();await page.waitForFunction(id=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().selected==='category:'+id,child);
 assert.equal(hash(await geometry()),original);assert.equal(await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.progressBuilds),0);
 assert(await page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow;return [...w.document.querySelectorAll('#graph .node')].every((n,i)=>n===w.progressNodes[i]);}));
 await frame.locator('#inspector-close').click();await frame.locator('#progress-expand').click();await frame.locator('#progress-project').selectOption('');
 await page.screenshot({path:path.join(out,'5-global-personal-comparison.png')});
 await frame.locator('#progress-close').click();
 await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.select('category:73',false));
 const globalChild=await frame.locator('[data-progress-category]').first().getAttribute('data-progress-category');
 await frame.locator('[data-progress-category]').first().click();
 await page.waitForFunction(id=>AtlasShell.state().route.view==='atlas'&&AtlasShell.state().activeFrame.contentWindow.AtlasV6.state().selected==='category:'+id,globalChild);
 await page.evaluate(()=>AtlasShell.navigate({view:'skill-tree'}));
 await frame.locator('#inspector-close').click();await frame.locator('#progress-expand').click();
 checks.push('Two persistent tabs; Global/Course segmented counts and personal date','Project/Stage coverage and separate explicit statuses','UNKNOWN Project, empty Project/Stage, unobserved Course and Category with no eligible Course Topics presentation','Java global and Course denominators; exact personal child and absent-personal Global child navigation','Inspector close/Pin; same graph DOM; zero layout builds; accepted personal geometry fingerprint');
 // Only frozen geometry checks on the existing Atlas routes; no broad suite.
 const expected={global:'1306993ec8a1b7a80edda4f620fb96ba5d4803c0d81ded334b92efa85cdf1174',course8:'ab8e05971ca8fb9d077b491a766554f5b84118e068433afe4c17faa7e91fb89b',project113:'33dc51873bcbd33fa6ad2de854dd719e525706bdb764a50578570d1f73e89034',stage617:'24edf473c9e97b7ccbb287464302a4bbf6ffadff33efdc265076b5ae6b51455e'};
 const geometryHashes={personal:original};
 for(const [name,route]of[['global',{view:'atlas'}],['course8',{view:'atlas',course:'8'}],['project113',{view:'atlas',project:'113'}],['stage617',{view:'atlas',project:'113',stage:'617'}]]){
  await page.evaluate(r=>AtlasShell.navigate(r),route);await page.waitForFunction(()=>document.querySelector('#loading').hidden);
  const data=await page.evaluate(()=>{const w=AtlasShell.state().activeFrame.contentWindow,L=(w.ScopeApp||w.AtlasV6).state().L;return[L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height,n.lines]),L.connectorSegments,L.trays,L.checkpoint];});
  geometryHashes[name]=hash(data);assert.equal(geometryHashes[name],expected[name]);
 }
 checks.push('Global/Course8/Project113/Stage617 accepted geometry fingerprints unchanged');
 await page.evaluate(()=>AtlasShell.navigate({view:'skill-tree'}));await frame.locator('#progress-close').click();
 await page.evaluate(()=>AtlasShell.state().activeFrame.contentWindow.AtlasV6.select('category:73',false));
 await frame.locator('#inspector-toggle').click();await frame.locator('.category-progress a').click();await page.waitForFunction(()=>AtlasShell.state().activeFrame?.contentWindow.AtlasV6?.state().selected==='category:73'&&AtlasShell.state().route.view==='atlas');checks.push('Show Java in Global preserves exact category:73');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(__dirname,'progress-browser-results.json'),JSON.stringify({checks,geometryHashes,errors,external,previewURL:base},null,2)+'\n');console.log(checks);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
