/* Offline preview QA. Authoritative Production browser regression is separate. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const base=path.resolve(__dirname,'../..'),out=__dirname,results=[],browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/opt/google/chrome/chrome'});try{for(const [width,height]of [[1440,900],[1920,1080],[1024,768]]){
 const page=await browser.newPage({viewport:{width,height},deviceScaleFactor:1}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.route('**/*',r=>{const u=new URL(r.request().url()),rel=u.pathname.slice(1);if(u.origin!=='http://preview.invalid'||rel.includes('..')){external.push(u.href);return r.abort();}const file=path.join(base,rel);if(!fs.existsSync(file))return r.abort();return r.fulfill({body:fs.readFileSync(file),contentType:rel.endsWith('.js')?'application/javascript':rel.endsWith('.json')?'application/json':rel.endsWith('.css')?'text/css':'text/html'});});
 await page.goto('http://preview.invalid/migration-preview/view/index.html');await page.waitForFunction(()=>window.MigrationPreview);const frame=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await frame();await page.evaluate(()=>{window.original=JSON.stringify([MigrationPreview.current,MigrationPreview.target,MigrationPreview.master,MigrationPreview.semantic]);window.comparisons=0;});const images=[];
 const verify=async()=>{await frame();await page.evaluate(()=>{const a=MigrationPreview;if(JSON.stringify([a.current,a.target,a.master,a.semantic])!==original)throw Error('Preview geometry/semantics mutated');const map=new Map(a.master.positions.map(n=>[n.key,n]));for(const n of a.target.positions){const p=map.get(n.slot);for(const k of ['x','y','w','h'])if(n[k]!==p[k])throw Error('Target mismatch');comparisons++;}});};
 const shot=async name=>{await verify();const file=`${width}-${name}.png`;await page.screenshot({path:path.join(out,file)});images.push(file);};
 await page.locator('[data-mode=current]').click();await shot('current-overview');await page.locator('[data-mode=target]').click();await page.locator('#world').click();await shot('target-overview');await page.locator('#fit').click();await page.locator('[data-mode=split]').click();await shot('split-overview');await shot('my-atlas');
 await page.locator('#branch').selectOption('category:73');await shot('java');await page.locator('#entity').selectOption('topic:78');await shot('deep-topic');
 await page.locator('#clear').click();await page.locator('#scope').selectOption('project');assert.equal(await page.evaluate(()=>MigrationPreview.rows().length),26);await shot('project-113');await page.locator('#scope').selectOption('stage');assert.equal(await page.evaluate(()=>MigrationPreview.rows().length),12);await shot('stage-617');
 await page.locator('#clear').click();await page.locator('#type').selectOption('category');await page.locator('#largest').selectOption('1');const cat=await page.evaluate(()=>MigrationPreview.rows()[0].key);await page.locator('#entity').selectOption(cat);await shot('largest-category');
 await page.locator('#clear').click();await page.locator('#type').selectOption('topic');await page.locator('#largest').selectOption('1');const topic=await page.evaluate(()=>MigrationPreview.rows()[0].key);await page.locator('#entity').selectOption(topic);await shot('largest-topic');await page.locator('#clear').click();await shot('bounds-minimap');
 await page.locator('#entity').selectOption('topic:36');await page.locator('[data-mode=overlay]').focus();await page.keyboard.press('Enter');await shot('selected-vector');assert.equal(await page.evaluate(()=>MigrationPreview.performanceData.vectors),1);
 await page.keyboard.press('Escape');await verify();await page.locator('#largest').selectOption('10');await verify();await page.locator('#type').selectOption('category');await verify();await page.setViewportSize({width:width-50,height:height-30});await verify();await page.setViewportSize({width,height});
 const perf=await page.evaluate(async()=>{const a=MigrationPreview,samples={overlay:[],selectedVector:[],fit:[]},frame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));for(let i=0;i<30;i++){document.querySelector('#clear').click();a.setMode('overlay');await frame();samples.overlay.push(a.performanceData.drawMs);document.querySelector('#entity').value='topic:36';document.querySelector('#entity').dispatchEvent(new Event('change'));await frame();samples.selectedVector.push(a.performanceData.drawMs);a.fit();samples.fit.push(a.performanceData.fitMs);if(JSON.stringify([a.current,a.target,a.master,a.semantic])!==original)throw Error('Repeated mutation');comparisons+=135;}return Object.fromEntries(Object.entries(samples).map(([k,v])=>{v.sort((a,b)=>a-b);return[k,{median:v[15],p95:v[28]}];}));});await verify();assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 results.push({viewport:[width,height],screenshots:images,performance:perf,...await page.evaluate(()=>({initMs:MigrationPreview.performanceData.initMs,heapBytes:performance.memory?.usedJSHeapSize??null,comparisons,geometryAndSemanticsUnchanged:true,matched:MigrationPreview.target.positions.length})),errors,external});await page.close();
 }}finally{await browser.close();}fs.writeFileSync(out+'/browser-results.json',JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results.map(r=>({viewport:r.viewport,comparisons:r.comparisons,performance:r.performance})),null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
