/* Lean live freeze check: one viewport, no screenshots or performance matrix. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium,launchOptions}=require('./browser.cjs');
const expectedGeometry='b38b9c7a692c27be27db7e4500b1a5b3abec85eac2ab0bf0c07852f0f8f1a6d9';
const checks=[],check=(name,ok)=>{assert.ok(ok,name);checks.push(name)};
(async()=>{const browser=await chromium.launch(launchOptions);try{
 const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:2}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const load=async()=>{await page.goto(process.env.ATLAS_URL||'http://127.0.0.1:8791');await page.waitForFunction(()=>window.AtlasV6);await page.evaluate(()=>AtlasV6.state().renderer.settled())};
 const facts=()=>page.evaluate(async()=>{
  const {L,m,renderer:r,transform:t}=AtlasV6.state(),geometry={nodes:L.nodes.map(({data,...n})=>n),trays:L.trays,branches:L.branches,connectors:L.connectorSegments,checkpoint:L.checkpoint,plans:[...L.plans],routingGroups:[...L.routingGroups]};
  const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(geometry))),geometryHash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');
  const learned=[...m.registry.values()].filter(n=>n.is_learned).map(n=>n.key),verified=[...m.registry.values()].filter(n=>n.is_verified).map(n=>n.key),cores=r.scene.inks.filter(c=>c.kind==='core'&&c.style==='learnedCore'),rings=r.scene.inks.filter(c=>c.kind==='ring'),rows=r.scene.inks.filter(c=>c.kind==='progress-row');
  const progress=cores.map(c=>{const ring=rings.find(x=>x.entity===c.entity),o=AtlasTiled.markerOptics(ring||c,t.k,'overview'),e=r.byKey.get(c.entity);return{key:c.entity,x:c.x*t.k+t.x,y:c.y*t.k+t.y,outer:o.radius*t.k+o.width/2,anchorExact:c.x===e.x+12&&c.y===e.y+e.h/2,verified:!!ring,compositeExact:!ring||ring.x===c.x&&ring.y===c.y}});
  let maxOverlap=0,overlappingPairs=0;for(let i=0;i<progress.length;i++)for(let j=i+1;j<progress.length;j++){const a=progress[i],b=progress[j],depth=Math.max(0,Math.min(a.outer+b.outer-Math.abs(a.x-b.x),a.outer+b.outer-Math.abs(a.y-b.y)));maxOverlap=Math.max(maxOverlap,depth);if(depth>1e-9)overlappingPairs++;}
  const ids=r.scene.entities.map(e=>e.key),modelIds=[...m.nodes.keys()];
  return{geometryHash,version:L.checkpoint.layout_algorithm_version,categories:L.nodes.filter(n=>n.data.type==='category').length,leaves:L.nodes.filter(n=>AtlasModel.isLeaf(n.data)).length,roots:m.root.children.length,learned,verified,ids,modelIds,progress,maxOverlap,overlappingPairs,rowCount:rows.length,rowsExact:rows.every(c=>{const e=r.byKey.get(c.entity);return c.x===e.x&&c.y===e.y&&c.w===e.w&&c.h===e.h}),labels:r.scene.commands.filter(c=>c.kind==='text').length,edges:L.connectorSegments.length,allTileInventories:AtlasTiled.levels.every(rank=>r.inventoryForLevel(rank).semantic_entity_ids===r.entityIds),cacheVersioned:[...r.cache.keys()].every(k=>k.startsWith(r.scene.geometryVersion+':'+AtlasTiled.opticsVersion+':')),cacheBounded:r.bytes<=AtlasTiled.memoryCap,minimapPresent:document.querySelector('#minimap').width>0,rendererMode:r.metrics.mode,fitScale:t.k};
 });
 await load();const before=await facts();check('accepted geometry fingerprint unchanged',before.geometryHash===expectedGeometry);check('849 Categories / 3106 leaf slots / five roots',before.categories===849&&before.leaves===3106&&before.roots===5);
 assert.deepEqual(before.ids.slice().sort(),before.modelIds.slice().sort());check('complete unique model identity inventory',new Set(before.ids).size===3956);
 check('31 learned / 12 verified exact composite anchors',before.learned.length===31&&before.verified.length===12&&before.progress.every(p=>p.anchorExact&&p.compositeExact&&p.outer>0)&&before.progress.filter(p=>p.verified).length===12);
 check('zero distinct progress-glyph outer-AABB overlap',before.maxOverlap===0&&before.overlappingPairs===0);check('31 learned cues occupy original exact rows',before.rowCount===31&&before.rowsExact);
 check('complete tile inventories, versioned bounded cache, minimap',before.allTileInventories&&before.cacheVersioned&&before.cacheBounded&&before.minimapPresent);
 await page.evaluate(()=>{const s=AtlasV6.state();window.freezeScene=s.renderer.scene;window.freezeLayout=s.L;window.freezeCommands=s.renderer.commandIds;window.freezeBuilds=0;const build=AtlasLayout.build;AtlasLayout.build=(...args)=>{freezeBuilds++;return build(...args)}});
 await page.evaluate(()=>AtlasV6.select('category:1164',false));await page.evaluate(()=>AtlasV6.state().renderer.settled());
 check('Inspector overlays full-width canvas and overview path uses fixed geometry',await page.evaluate(()=>{const s=AtlasV6.state(),p=[...document.querySelectorAll('#orientation-world path')];return s.viewState==='overview'&&s.inspectorState.open&&!s.inspectorState.pinned&&document.querySelector('#graph').clientWidth===1440&&p.length===30&&p.every(p=>p.getAttribute('d')===s.L.connectorSegments[+p.dataset.segment].d)}));
 const overlay=await facts();check('zero progress overlap with Inspector overlay',overlay.maxOverlap===0&&overlay.overlappingPairs===0);
 await page.mouse.move(550,480);await page.mouse.down();await page.mouse.move(610,500,{steps:6});await page.mouse.up();await page.mouse.wheel(0,100);await page.waitForTimeout(220);await page.evaluate(()=>AtlasV6.state().renderer.settled());
 check('navigation preserves world, commands, complete inventory and explicit view state',await page.evaluate(()=>{const s=AtlasV6.state();return s.L===freezeLayout&&s.renderer.scene===freezeScene&&s.renderer.commandIds===freezeCommands&&freezeBuilds===0&&s.viewState==='overview'&&s.renderer.scene.entities.length===3956}));
 await page.click('#inspector-pin');check('optional pin reserves the accepted side-by-side width',await page.evaluate(()=>AtlasV6.state().inspectorState.pinned&&document.querySelector('#graph').clientWidth===1190));await page.click('#inspector-pin');await page.click('#inspector-close');
 check('closed Inspector immediately restores full canvas',await page.evaluate(()=>!AtlasV6.state().inspectorState.open&&document.querySelector('#graph').clientWidth===1440));
 for(const [key,view]of [['category:2148','subtree'],['topic:518','topic']]){await page.evaluate(key=>AtlasV6.select(key,true),key);await page.waitForFunction(()=>!AtlasV6.state().transitioning);await page.evaluate(()=>AtlasV6.state().renderer.settled());check(view+' retains normal markers and full scene',await page.evaluate(view=>{const s=AtlasV6.state(),c=s.renderer.scene.inks.find(c=>c.kind==='core'&&c.style==='learnedCore'),o=AtlasTiled.markerOptics(c,s.transform.k,view);return s.viewState===view&&document.querySelector('#orientation').hasAttribute('hidden')&&o.radius===Math.min(7,Math.max(4,1.2/s.transform.k))&&s.renderer.scene===freezeScene&&freezeBuilds===0},view));}
 await load();const again=await facts();check('geometry deterministic across fresh initialization',again.geometryHash===before.geometryHash);assert.deepEqual(again.learned,before.learned);assert.deepEqual(again.verified,before.verified);check('progress identities stable across fresh initialization',true);check('no browser errors',errors.length===0);
 const safari=JSON.parse(fs.readFileSync(path.join(__dirname,'viewport-polish/safari.json')));check('accepted Safari DPR2 frame-cadence evidence retained',safari.dpr===2&&['overview','dense'].every(k=>safari.runs.after[k].frames.p95===17&&safari.runs.after[k].frames.over50===0));
 fs.mkdirSync(path.join(__dirname,'generated'),{recursive:true});fs.writeFileSync(path.join(__dirname,'generated/accepted.json'),JSON.stringify({status:'GLOBAL_V66_ACCEPTED',checks,geometryHash:before.geometryHash,geometryVersion:before.version,categories:before.categories,leaves:before.leaves,labels:before.labels,edges:before.edges,learned:before.learned,verified:before.verified,fitScale:before.fitScale,progressMaxOverlapPx:before.maxOverlap,progressOverlappingPairs:before.overlappingPairs,rendererMode:before.rendererMode,errors},null,2)+'\n');console.log(checks.length+' focused accepted-milestone checks passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
