(async()=>{
'use strict';
const $=s=>document.querySelector(s),A=AdaptiveCore,C=GlobalAtlasCore,U=GlobalPyramidUX,L=PyramidLabels;
const [raw,geometry]=await Promise.all(['model.json','global-reference.json'].map(async n=>(await fetch(n)).json()));
const model=AtlasRegistry.index(raw,geometry),ctx=$('#map').getContext('2d'),mini=$('#mini').getContext('2d'),measureCanvas=document.createElement('canvas').getContext('2d');
const measure=(text,font)=>{measureCanvas.font=font;return measureCanvas.measureText(text).width;},v=new AtlasViews.Views(model,measure),history=[];
let width=0,height=0,frame=null,hover=null,drag=null;const colors=['#63c7e3','#b39cf4','#e2be77','#e690b9','#87d7a4'],names={learned:'My Knowledge',accepted:'Accepted Landscape',course:'Course',project:'Project',global:'Global reference'};
const color=n=>colors[Math.max(0,geometry.root_sectors.findIndex(r=>r.root===n.root))],label=n=>A.title(n,v.scope),screen=(p,c=v.camera)=>({x:p.x*c.k+c.x,y:p.y*c.k+c.y,w:p.w*c.k,h:p.h*c.k});
function schedule(){if(frame===null)frame=requestAnimationFrame(()=>{frame=null;draw();});}
function fitBounds(b){const c=U.camera(b,width,height,{left:30,right:30,top:25,bottom:135});if(c){c.k=Math.min(c.k,1.25);c.x=width/2-(b.x+b.w/2)*c.k;c.y=(height-110)/2-(b.y+b.h/2)*c.k;v.camera=c;}schedule();}
function fit(){fitBounds(v.mode==='reference'?geometry.bounds:C.bounds(v.positions.values()));}
function save(){history.push({options:{...v.options},mode:v.mode,selected:v.selected,camera:{...v.camera}});}
function focus(key,{saveHistory=true}={}){
 const start=performance.now();if(!v.m.nodes.has(key))return;if(saveHistory)save();
 if(v.mode==='compact'&&v.local.hidden.has(key))v.open(key);v.selected=key;
 const p=v.positions.get(key);if(p){const ns=v.m.nodes.get(key).kind==='category'?[...v.positions].filter(([k])=>A.inside(v.m,k,key)).map(([,p])=>p):[p];fitBounds(C.bounds(ns));}
 refresh();v.metrics.focusMs=performance.now()-start;schedule();
}
function inspector(){
 const box=$('#details');box.replaceChildren();$('#related').replaceChildren();$('#global-show').disabled=!v.selected;
 const knowledge=A.selection(v.m,{mode:'learned'});$('#my-show').disabled=!v.selected||!knowledge.visible.has(v.selected);
 if(!v.selected){box.textContent='Select a card or search result. Hidden details remain searchable.';return;}
 const n=v.m.nodes.get(v.selected),add=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;box.append(e);return e;};
 add('h2',label(n));add('p',n.key+' → '+n.slot);add('p',v.scope.explicit.has(n.key)?'Explicit scope content':v.scope.visible.has(n.key)?'Hierarchy context; no learning or membership inference':'Outside scope; inspection only');
 const state=v.m.raw.progress.filter(r=>r.topic_id===n.id);if(n.kind!=='category')add('p',v.scope.isFixture?'Presentation fixture · no personal assertion':state.length?state.map(r=>'learned='+r.is_learned+' · verified='+r.is_verified+' · '+r.verification_status).join(' | '):'Personal state UNKNOWN');
 const r=v.m.reference.get(n.key);add('p','Reference: '+r.x+', '+r.y);const local=v.local?.positions.get(n.key);if(local)add('p','Local: '+local.x.toFixed(1)+', '+local.y.toFixed(1));
 if(n.kind==='category'){const s=A.stats(v.m,v.scope,n.key);add('p',s.topics+' distinct relevant '+(v.scope.isFixture?'slots':'Topics')+' · '+s.learned+' learned · '+s.verified+' verified');}
 add('p','Structural memberships:');for(const k of n.parents){const b=add('button',v.m.nodes.get(k).title+(k===n.parent?' · primary layout parent':' · secondary membership'));b.onclick=()=>focus(k);}
 const more=add('details',''),title=document.createElement('summary');title.textContent='Relations / evidence';more.append(title);const pre=document.createElement('pre');pre.textContent=JSON.stringify({relations:v.m.raw.relations.filter(e=>e.source===n.key||e.target===n.key),fact_sources:n.fact_sources,evidence_ids:n.evidence_ids},null,2);more.append(pre);
 const related=$('#related');for(const course of v.m.raw.courses.filter(c=>(n.kind==='category'?c.category_ids:c.topic_ids).includes(n.id))){const b=document.createElement('button');b.textContent='Open Course '+course.id;b.onclick=()=>confirm({mode:'course',id:course.id,stage:null,branch:null},'compact',true);related.append(b);}
 for(const project of v.m.raw.projects.filter(p=>p.required.includes(n.key))){const b=document.createElement('button');b.textContent='Open Project '+project.id;b.onclick=()=>confirm({mode:'project',id:project.id,stage:null,branch:null},'compact',true);related.append(b);}
}
function refresh(){
 $('#preview-note').textContent=v.m.raw.presentation_fixture?'PRESENTATION-ONLY FIXTURE · simulated state, no Knowledge write':'Adaptive preview · Production migration paused';
 const s=v.scope,topics=[...s.topics],learned=topics.filter(k=>s.learned.has(k)).length,verified=topics.filter(k=>s.verified.has(k)).length;
 $('#summary').textContent=s.unknown?s.reason:s.options.mode==='global'?`${v.m.raw.counts.categories} Categories · ${v.m.raw.counts.topics} Topics · ${v.m.raw.counts.references} unresolved references`:s.isFixture?topics.length+' structural slots · FIXTURE':topics.length+' Topics · '+learned+' learned · '+verified+' verified';
 $('#view-title').textContent=(s.isFixture?'Presentation fixture':names[s.options.mode]||s.options.mode)+(s.options.mode==='course'||s.options.mode==='project'?' '+s.options.id+(s.options.stage?' / Stage '+s.options.stage:''):'')+' · '+({compact:'compact local geometry',mask:'strict global mask',reference:'global reference geometry'}[v.mode]);
 $('#empty').hidden=v.positions.size>0;$('#empty').textContent=s.unknown?s.reason:'Known empty scope';$('#pending').textContent='';
 for(const [id,mode]of [['compact','compact'],['highlight','reference'],['mask','mask']])$('#'+id).setAttribute('aria-pressed',String(v.mode===mode));
 $('#compact').textContent=s.options.mode==='course'?'Compact Course':s.options.mode==='project'?'Compact Project':'Compact view';
 const roots=$('#context-roots');roots.replaceChildren();for(const n of v.m.roots){const b=document.createElement('button');b.textContent=n.title+' · '+A.stats(v.m,s,n.key).topics;b.className=s.visible.has(n.key)?'relevant':'';b.onclick=()=>focus(n.key);roots.append(b);}
 const branch=$('#branch');branch.replaceChildren(new Option('Entire scope',''));for(const n of v.m.nodes.values())if(n.kind==='category'&&s.visible.has(n.key)&&A.stats(v.m,s,n.key).topics&&(n.depth<=3||n.children.some(c=>s.topics.has(c.key))))branch.add(new Option(label(n)+' · '+A.stats(v.m,s,n.key).topics,n.key));branch.value=v.options.branch||'';
 const crumbs=$('#breadcrumbs');crumbs.replaceChildren();let n=v.m.nodes.get(v.selected),path=[];while(n){path.unshift(n);n=v.m.nodes.get(n.parent);}for(const n of path){const b=document.createElement('button');b.textContent=label(n);b.onclick=()=>focus(n.key);crumbs.append(b);}
 $('#collapse').disabled=v.mode!=='compact'||v.m.nodes.get(v.selected)?.kind!=='category';$('#expand').disabled=v.mode!=='compact'||!v.selected;$('#summarize').disabled=v.mode!=='compact';inspector();
}
function configure(options=v.options){
 $('#scene').value=options.mode==='global'?'learned':options.mode;const course=$('#scene').value==='course',project=$('#scene').value==='project',rows=course?v.m.raw.courses:project?v.m.raw.projects:[];
 $('#context').replaceChildren();for(const r of rows)$('#context').add(new Option((course?'Course ':'Project ')+r.id+' · '+r.title+(r.requirements_status==='UNKNOWN'?' · UNKNOWN':''),r.id));$('#context').disabled=!rows.length;if(rows.length)$('#context').value=String(rows.some(r=>r.id===options.id)?options.id:rows[0].id);
 stages(options.stage);$('#only-learned').disabled=!(course||project);$('#only-learned').checked=(course||project)&&options.onlyLearned;
}
function stages(id=null){const p=v.m.raw.projects.find(p=>p.id===Number($('#context').value));$('#stage').replaceChildren(new Option('All requirements',''));for(const s of p?.stages||[])$('#stage').add(new Option('Stage '+s.id+' · '+s.title,s.id));$('#stage').disabled=$('#scene').value!=='project';$('#stage').value=id==null?'':String(id);}
function readOptions(){return {mode:$('#scene').value,id:Number($('#context').value)||8,stage:$('#stage').disabled||!$('#stage').value?null:Number($('#stage').value),onlyLearned:!$('#only-learned').disabled&&$('#only-learned').checked,branch:$('#branch').value||null};}
function confirm(options,mode,refit=false){const previousMode=v.mode,before=v.metrics.layoutCalls;v.confirm(options,mode);configure(v.options);refresh();if(refit||(v.mode==='compact'&&before!==v.metrics.layoutCalls&&(!v.selected||!v.local.positions.has(v.selected))))fit();else if(previousMode!==v.mode)schedule();schedule();}
function pending(){$('#pending').textContent='Selection changed · confirm with a view action';}
function draw(){
 const started=performance.now();ctx.clearRect(0,0,width,height);let ps=v.positions,camera=v.camera,animated=false;
 if(v.transition&&v.mode==='compact'){const f=AtlasViews.interpolate(v.transition,performance.now());ps=f.positions;camera=f.camera;animated=f.t<1;if(animated)schedule();else v.transition=null;}
 const sx=x=>x*camera.k+camera.x,sy=y=>y*camera.k+camera.y,s=v.scope;ctx.lineWidth=1.1;ctx.strokeStyle='#65899d';ctx.globalAlpha=.55;
 if(v.mode==='compact'&&!animated){ctx.save();ctx.globalAlpha=.25;ctx.setLineDash([3,6]);ctx.strokeStyle='#8aa6ba';for(const band of v.local.bands.values()){const y=sy(band.y);if(y<0||y>height)continue;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#b8cede';ctx.font='10px system-ui';ctx.fillText('depth '+band.depth,5,y-4);ctx.setLineDash([3,6]);}ctx.restore();}
 if(!animated)for(const route of v.routes){ctx.beginPath();route.points.forEach(([x,y],i)=>i?ctx.lineTo(sx(x),sy(y)):ctx.moveTo(sx(x),sy(y)));ctx.stroke();}
 if(v.mode==='reference'&&s.options.mode!=='global'){
  const slots=new Set([...s.visible].map(k=>C.slot(k)));ctx.strokeStyle='#efbf74';ctx.globalAlpha=1;ctx.lineWidth=2;for(const route of v.routes)if(slots.has(route.child)){ctx.beginPath();route.points.forEach(([x,y],i)=>i?ctx.lineTo(sx(x),sy(y)):ctx.moveTo(sx(x),sy(y)));ctx.stroke();}
 }
 if(v.mode==='compact'&&!animated)for(const group of v.local.groups){const b=screen(group,camera);ctx.fillStyle='#20364a55';ctx.fillRect(b.x,b.y,b.w,b.h);}
 let cards=0,labels=0,topicLabels=0;for(const [key,p]of ps){const b=screen(p,camera);if(b.x+b.w<0||b.y+b.h<0||b.x>width||b.y>height||p.opacity===0)continue;cards++;const n=v.m.nodes.get(key),chosen=key===v.selected||key===hover,relevant=s.visible.has(key),context=s.context.has(key);
  ctx.globalAlpha=(p.opacity??1)*(v.mode==='reference'&&s.options.mode!=='global'&&!relevant&&!chosen ? .22 : 1);ctx.fillStyle=chosen?'#34536b':context?'#172739':'#20394c';ctx.strokeStyle=chosen?'#ffe29a':v.mode==='reference'&&s.explicit.has(key)&&s.options.mode!=='global'?'#ffd084':color(n);ctx.lineWidth=chosen?2:1;ctx.beginPath();ctx.roundRect(b.x,b.y,Math.max(.5,b.w),Math.max(.5,b.h),Math.min(6,b.w/8));ctx.fill();ctx.stroke();
  if(camera.k>=.8&&labels<120){ctx.save();ctx.translate(b.x,b.y);ctx.scale(camera.k,camera.k);ctx.font=p.font||'14px system-ui';ctx.fillStyle='#ecf4fb';const wrapped=p.lines?{lines:p.lines,truncated:false}:L.wrap(label(n),t=>measure(t,'14px system-ui'),p.w-28,n.kind==='topic'||n.kind==='reference'?1:2),lines=wrapped.lines;lines.forEach((t,i)=>ctx.fillText(t,14,22+i*18));if(p.meta){const stats=A.stats(v.m,s,key),meta=n.kind==='category'?(p.collapsed?'Summary · ':'')+stats.topics+(s.isFixture?' slots':' Topics'):s.isFixture?'Fixture · no progress':s.learned.has(key)?'learned'+(s.verified.has(key)?' · verified':''):'Explicit scope content';ctx.font='11px system-ui';ctx.fillStyle='#adc6d8';ctx.fillText(meta,14,p.h-(p.count?27:12));if(p.count)ctx.fillText(s.isFixture?'No progress assertion':stats.learned+' learned · '+stats.verified+' verified',14,p.h-11);}ctx.restore();labels++;if(!s.isFixture&&s.topics.has(key)&&n.kind==='topic'&&!wrapped.truncated&&b.x>=0&&b.x+b.w<=width&&b.y>=0&&b.y+b.h<=height)topicLabels++;}
  if($('#progress').checked&&s.learned.has(key)){ctx.fillStyle='#78e9a1';ctx.beginPath();ctx.arc(b.x+b.w-7,b.y+7,3.5,0,Math.PI*2);ctx.fill();}if($('#progress').checked&&s.verified.has(key)){ctx.strokeStyle='#fff';ctx.beginPath();ctx.arc(b.x+b.w-7,b.y+7,6,0,Math.PI*2);ctx.stroke();}
 }
 ctx.globalAlpha=1;const boxes=[];if(camera.k<.8){const candidates=[...ps].filter(([k])=>v.m.nodes.get(k).kind==='category').sort(([ka,a],[kb,b])=>v.m.nodes.get(ka).depth-v.m.nodes.get(kb).depth||A.stats(v.m,s,kb).topics-A.stats(v.m,s,ka).topics||a.x-b.x);for(const [key,p]of candidates){if(boxes.length===18)break;const b=screen(p,camera);if(b.x<0||b.x>width||b.y<0||b.y>height-130)continue;const text=label(v.m.nodes.get(key)),lines=L.wrap(text,t=>measure(t,'12px system-ui'),155,2).lines,w=Math.max(...lines.map(t=>measure(t,'12px system-ui')))+16,showCount=v.mode!=='compact'||p.collapsed,h=lines.length*15+(showCount?24:8),box={x:Math.max(4,Math.min(width-w-4,b.x+b.w/2-w/2)),y:Math.max(4,v.mode==='compact'?b.y+2:b.y-h-8),w,h};if(v.mode==='compact'){const region=screen(v.local.subtrees.get(key),camera);if(w>region.w||box.y<region.y||box.y+h>region.y+region.h)continue;box.x=Math.max(region.x,Math.min(region.x+region.w-w,box.x));}box.key=key;if(boxes.some(a=>L.overlaps(a,box,5)))continue;if(v.mode==='compact'&&[...ps].some(([other,p])=>other!==key&&L.overlaps(screen(p,camera),box,2)))continue;ctx.fillStyle='#12283cf2';ctx.fillRect(box.x,box.y,w,h);ctx.strokeStyle='#47697f';ctx.strokeRect(box.x,box.y,w,h);ctx.font='12px system-ui';ctx.fillStyle='#e4f0f8';lines.forEach((t,i)=>ctx.fillText(t,box.x+8,box.y+15+i*15));ctx.font='11px system-ui';ctx.fillStyle='#97c6da';if(showCount)ctx.fillText(A.stats(v.m,s,key).topics+(s.isFixture?' slots':' relevant'),box.x+8,box.y+h-7);boxes.push(box);labels++;}}
 v.metrics.renderedCards=cards;v.metrics.labels=labels;v.metrics.readableTopicLabels=topicLabels;v.metrics.fitScale=v.camera.k;v.metrics.drawMs=performance.now()-started;v.metrics.labelBoxes=boxes;
 $('#metrics').textContent=(v.mode==='compact'?'Layout '+v.metrics.layoutMs.toFixed(2)+' ms · ':'Global layout: none · ')+cards+' cards · '+topicLabels+' readable Topic labels';$('#status').textContent=(s.isFixture?'FIXTURE · ':'')+(v.mode==='compact'?'Local presentation; ancestors are context':'Immutable global reference; highlight changes no layout')+' · '+(v.camera.k*100).toFixed(1)+'%';drawMinimap();
}
function drawMinimap(){
 const b=v.mode==='compact'?v.local.bounds:geometry.bounds;mini.clearRect(0,0,190,110);if(!b)return;const k=Math.min(178/b.w,88/b.h),x=n=>6+(n-b.x)*k,y=n=>19+(n-b.y)*k;mini.font='10px system-ui';mini.fillStyle='#cbdeeb';mini.fillText(v.mode==='compact'?'LOCAL VIEW':'GLOBAL REFERENCE',6,12);
 for(const [key,p]of v.positions){mini.fillStyle=v.scope.visible.has(key)?'#85c8df':'#506477';mini.fillRect(x(p.x),y(p.y),Math.max(1,p.w*k),Math.max(1,p.h*k));}
 const c=v.camera;mini.strokeStyle='#ffcf80';mini.strokeRect(x(-c.x/c.k),y(-c.y/c.k),width/c.k*k,height/c.k*k);v.metrics.minimapSystem=v.mode==='compact'?'local':'global';v.metrics.minimapBounds={...b};
}
function zoom(f,x=width/2,y=height/2){const c=v.camera,k=Math.max(.0001,Math.min(5,c.k*f));v.camera={k,x:x-(x-c.x)*k/c.k,y:y-(y-c.y)*k/c.k};v.transition=null;schedule();}
function hit(e){const r=$('#map').getBoundingClientRect(),x=(e.clientX-r.left-v.camera.x)/v.camera.k,y=(e.clientY-r.top-v.camera.y)/v.camera.k;return [...v.positions].reverse().find(([,p])=>x>=p.x&&x<=p.x+p.w&&y>=p.y&&y<=p.y+p.h)?.[0];}
$('#map').onwheel=e=>{e.preventDefault();const r=$('#map').getBoundingClientRect();zoom(Math.exp(-e.deltaY*.002),e.clientX-r.left,e.clientY-r.top);};$('#map').onpointerdown=e=>{$('#map').setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,c:{...v.camera},moved:false};};$('#map').onpointermove=e=>{if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved||=Math.abs(dx)+Math.abs(dy)>4;v.camera={...drag.c,x:drag.c.x+dx,y:drag.c.y+dy};schedule();}else{hover=hit(e);schedule();}};$('#map').onpointerup=e=>{if(drag&&!drag.moved){const key=hit(e);if(key){v.selected=key;refresh();schedule();}}drag=null;};$('#map').onpointercancel=()=>drag=null;$('#map').ondblclick=e=>{const key=hit(e);if(key)focus(key);};$('#map').onkeydown=e=>{if(e.key==='+'||e.key==='=')zoom(1.4);else if(e.key==='-')zoom(1/1.4);else if(e.key.startsWith('Arrow')){v.camera={...v.camera,x:v.camera.x+(e.key==='ArrowLeft'?60:e.key==='ArrowRight'?-60:0),y:v.camera.y+(e.key==='ArrowUp'?60:e.key==='ArrowDown'?-60:0)};schedule();}else return;e.preventDefault();};
$('#compact').onclick=()=>confirm(readOptions(),'compact');$('#highlight').onclick=()=>confirm(readOptions(),'reference');$('#mask').onclick=()=>confirm(readOptions(),'mask',true);$('#global').onclick=()=>confirm({mode:'global',branch:null},'reference',true);$('#fit').onclick=fit;$('#zoom-in').onclick=()=>zoom(1.4);$('#zoom-out').onclick=()=>zoom(1/1.4);
$('#scene').onchange=()=>{const mode=$('#scene').value;configure({mode,id:mode==='project'?113:8,stage:null,onlyLearned:false});pending();};$('#context').onchange=()=>{stages();pending();};$('#stage').onchange=pending;$('#only-learned').onchange=pending;$('#branch').onchange=pending;$('#progress').onchange=schedule;
$('#collapse').onclick=()=>{v.collapse(v.selected);refresh();schedule();};$('#expand').onclick=()=>{v.open(v.selected);refresh();schedule();};$('#summarize').onclick=()=>{v.summarize();refresh();fit();};$('#back').onclick=()=>{const h=history.pop();if(h){v.confirm(h.options,h.mode);v.selected=h.selected;v.camera=h.camera;configure();refresh();schedule();}};
$('#global-show').onclick=()=>{const key=v.selected;save();v.mode='reference';refresh();focus(key,{saveHistory:false});};$('#my-show').onclick=()=>{const key=v.selected;save();confirm({mode:'learned',branch:null,stage:null,onlyLearned:false},'compact');focus(key,{saveHistory:false});};
$('#search').oninput=()=>{const box=$('#results'),found=A.search(v.m,$('#search').value);box.replaceChildren();for(const n of found.slice(0,12)){const b=document.createElement('button');b.textContent=label(n)+' · '+n.key;const meta=document.createElement('small');meta.textContent=v.scope.visible.has(n.key)?'Current scope; inspect / open details':'Outside scope; inspect without learning';b.append(meta);b.onclick=()=>{v.selected=n.key;if(v.mode==='compact'&&v.local.hidden.has(n.key))v.open(n.key);refresh();schedule();};box.append(b);}if(found.length>12)box.append(document.createTextNode(found.length+' matches; refine search'));};$('#search').onkeydown=e=>{if(e.key==='ArrowDown'){$('#results button')?.focus();e.preventDefault();}if(e.key==='Enter')$('#results button')?.click();};
$('#snapshot-refresh').onclick=async()=>{const next=await (await fetch('model.json',{cache:'no-store'})).json();v.updateSnapshot(next,{reducedMotion:!$('#animate').checked||matchMedia('(prefers-reduced-motion: reduce)').matches});refresh();schedule();};
$('#mini').onclick=fit;$('#mini').onkeydown=e=>{if(e.key==='Enter')fit();};
function resize(){const r=$('#surface').getBoundingClientRect(),oldWidth=width,oldHeight=height;width=r.width;height=r.height;const d=devicePixelRatio;$('#map').width=Math.round(width*d);$('#map').height=Math.round(height*d);ctx.setTransform(d,0,0,d,0,0);if(oldWidth){for(const key of ['local','global']){v.cameras[key].x+=(width-oldWidth)/2;v.cameras[key].y+=(height-oldHeight)/2;}}schedule();}
new ResizeObserver(resize).observe($('#surface'));resize();v.confirm(v.options,'compact');configure();refresh();fit();const localCamera={...v.camera};v.mode='reference';fit();v.mode='compact';v.camera=localCamera;schedule();
globalThis.KnowledgeAtlas={views:v,confirm:(o,mode='compact')=>confirm(o,mode,mode==='compact'||mode==='mask'||o.mode==='global'),focus,fit,render:schedule,measure,refreshSnapshot:raw=>{v.updateSnapshot(raw,{reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches});refresh();schedule();}};
})().catch(e=>{document.querySelector('#status').textContent='Preview failed: '+e.message;console.error(e);});
