/* Focused 1440x900 comparison. External Playwright; no acquisition or storage. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),base=path.resolve(__dirname,'..'),out=__dirname;
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1}),errors=[],external=[],results=[],shots=[],movements=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:8765'?r.continue():(external.push(r.request().url()),r.abort()));
 await page.goto('http://127.0.0.1:8765/prototypes/adaptive-pyramid/');await page.waitForFunction(()=>window.AdaptivePyramid);const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await settle();
 const shot=async name=>{await settle();await page.screenshot({path:path.join(out,name+'.png')});shots.push(name+'.png');};
 const measureScene=async(name,o)=>{if(o)await page.evaluate(o=>AdaptivePyramid.setOptions(o),o);await settle();const row=await page.evaluate(name=>{const p=AdaptivePyramid,l=p.local(),s=p.selection();return {name,options:p.state().options,topics:s.topics.size,visible:s.visible.size,unknown:s.unknown,layoutMs:p.metrics.layoutMs,bounds:l.bounds,totalCards:l.positions.size,renderedCards:p.metrics.renderedCards,labels:p.metrics.renderedLabels,readableLabels:p.metrics.readableLabels,zoom:p.state().cam.k};},name);results.push(row);return row;};
 await measureScene('my-compact');await shot('my-compact');await page.locator('#mask').click();await shot('my-global-mask');results.push(await page.evaluate(()=>({name:'my-global-mask',bounds:GlobalAtlasCore.bounds([...AdaptivePyramid.selection().visible].map(k=>AdaptivePyramid.m.nodes.get(k))),...AdaptivePyramid.metrics})));
 await page.locator('#compact').click();await page.evaluate(()=>AdaptivePyramid.focus('category:35'));await measureScene('my-topic-group');await shot('my-topic-group');
 await measureScene('accepted',{mode:'accepted',id:8,stage:null,onlyLearned:false,branch:null});await shot('accepted');await measureScene('course-8',{mode:'course'});await shot('course-8');
 await page.locator('#only-learned').check();const calls=await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls);assert.equal(await page.evaluate(()=>AdaptivePyramid.selection().topics.size),89);await page.locator('#compact').click();assert.equal(await page.evaluate(()=>AdaptivePyramid.selection().topics.size),31);assert.equal(await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls),calls+1);await shot('course-8-learned');
 await measureScene('project-113',{mode:'project',id:113,stage:null,onlyLearned:false,branch:null});await shot('project-113');
 await page.evaluate(()=>AdaptivePyramid.focus('category:35'));await measureScene('project-topic-group');await shot('project-topic-group');
 await page.locator('#stage').selectOption('617');const previous=await page.evaluate(()=>AdaptivePyramid.selection().topics.size);assert.equal(previous,26);await page.locator('#compact').click();assert.equal(await page.evaluate(()=>AdaptivePyramid.selection().topics.size),12);await page.locator('#fit').click();await measureScene('stage-617');await shot('stage-617');
 await page.locator('#only-learned').check();await page.locator('#compact').click();assert.equal(await page.evaluate(()=>AdaptivePyramid.selection().topics.size),12);
 await measureScene('project-unknown',{mode:'project',id:380,stage:null,onlyLearned:false});assert.match(await page.locator('#empty').innerText(),/UNKNOWN/);assert.doesNotMatch(await page.locator('#summary').innerText(),/0 relevante/);await shot('project-unknown');
 await measureScene('known-empty-stage',{mode:'project',id:113,stage:618});assert.match(await page.locator('#empty').innerText(),/Bekannte leere Auswahl/);
 // Styling, hover, typing and pan/zoom never invoke layout.
 await measureScene('style-check',{mode:'learned',stage:null,branch:null});const before=await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls);await page.locator('#progress').uncheck();await page.locator('#search').fill('topic:78');await page.mouse.move(700,500);await page.locator('#zoom-in').click();await page.locator('#map').focus();await page.keyboard.press('ArrowRight');await settle();assert.equal(await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls),before);
 // Existing Atlas camera is unchanged by highlighting a new selection.
 await page.locator('#highlight').click();await page.waitForFunction(()=>document.querySelector('#atlas').contentWindow.GlobalAtlas);await settle();const atlasCamera=await page.evaluate(()=>document.querySelector('#atlas').contentWindow.GlobalAtlas.state().cam);const highlightCalls=await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls);
 await page.locator('#scene').selectOption('project');await page.locator('#highlight').click();await settle();assert.deepEqual(await page.evaluate(()=>document.querySelector('#atlas').contentWindow.GlobalAtlas.state().cam),atlasCamera);assert.equal(await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls),highlightCalls);await shot('atlas-project-highlight');
 // ID-based navigation to actual master coordinate, without altering master objects.
 await page.evaluate(()=>AdaptivePyramid.inspect('topic:78'));await page.locator('#global-show').click();await settle();assert.equal(await page.evaluate(()=>document.querySelector('#atlas').contentWindow.GlobalAtlas.state().selected),'topic:78');await shot('atlas-topic-78');
 await page.locator('#compact').click();await page.locator('#search').fill('reference:333');await page.locator('#search').press('Enter');assert.equal(await page.evaluate(()=>AdaptivePyramid.state().selected),'reference:333');assert(!await page.evaluate(()=>AdaptivePyramid.selection().explicit.has('reference:333')));await page.locator('#global-show').click();await settle();assert.equal(await page.evaluate(()=>document.querySelector('#atlas').contentWindow.GlobalAtlas.state().selected),'reference:333');await shot('atlas-reference-333');
 for(const mode of ['fixture:load-300','fixture:load-1000','fixture:full']){
  const name=mode.split(':')[1];await measureScene(name,{mode,branch:null,stage:null,onlyLearned:false});await shot(name+'-expanded');await page.locator('#summarize').click();await measureScene(name+'-summarized');await shot(name+'-summarized');
  const hidden=await page.evaluate(()=>[...AdaptivePyramid.local().hidden].find(k=>!k.startsWith('category:')));await page.locator('#search').fill(hidden);await page.locator('#search').press('Enter');assert(await page.evaluate(key=>AdaptivePyramid.local().positions.has(key),hidden));await shot(name+'-opened');
 }
 for(const mode of ['fixture:growth-branch','fixture:growth-wide']){
  await measureScene(mode,{mode,step:0});await shot(mode.split(':')[1]+'-0');
  const key=await page.evaluate(()=>[...AdaptivePyramid.local().positions.keys()].find(k=>!k.startsWith('category:')));assert(key);await page.evaluate(key=>AdaptivePyramid.inspect(key),key);
  for(let step=1;step<4;step++){const anchor=await page.evaluate(key=>{const p=AdaptivePyramid.local().positions.get(key),c=AdaptivePyramid.state().cam;return {x:p.x*c.k+c.x,y:p.y*c.k+c.y};},key);await page.locator('#next-step').click();await settle();const movement=await page.evaluate(({key,anchor})=>{const p=AdaptivePyramid.local().positions.get(key),c=AdaptivePyramid.state().cam;return {movement:AdaptivePyramid.metrics.movement,anchorDelta:Math.hypot(p.x*c.k+c.x-anchor.x,p.y*c.k+c.y-anchor.y),layoutMs:AdaptivePyramid.metrics.layoutMs};},{key,anchor});assert(movement.anchorDelta<.001);movements.push({mode,step,...movement});}
  await shot(mode.split(':')[1]+'-3');
 }
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#animate').check();await page.evaluate(()=>AdaptivePyramid.setOptions({mode:'fixture:growth-branch',step:0}));await page.locator('#next-step').click();await settle();assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);
 // Browser-measured sizes: collision and repeatability checks in each expanded scene.
 const realMeasurements=await page.evaluate(()=>{
  const p=AdaptivePyramid,rows=[];for(const options of [{mode:'learned'},{mode:'accepted'},{mode:'project',id:113},{mode:'project',id:113,stage:617},{mode:'fixture:load-300'},{mode:'fixture:load-1000'},{mode:'fixture:full'}]){
   const s=AdaptiveCore.selection(p.m,options),a=AdaptiveCore.layout(p.m,s,{measure:p.measure}),b=AdaptiveCore.layout(p.m,s,{measure:p.measure});if(JSON.stringify([...a.positions])!==JSON.stringify([...b.positions])||JSON.stringify(a.routes)!==JSON.stringify(b.routes))throw Error('Non-repeatable browser geometry');rows.push({options,positions:[...a.positions.values()],routes:a.routes,durationMs:a.durationMs});
  }return rows;
 });
 // Import isolated collision checker after removing the test-run portion.
 const check=require('./collisions.cjs');for(const row of realMeasurements)row.checks=check({positions:new Map(row.positions.map(p=>[p.key,p])),routes:row.routes});
 const immutable=await page.evaluate(()=>{let count=0;for(const n of AdaptivePyramid.m.nodes.values()){const p=n.geometry;if(n.x!==p.x||n.y!==p.y||n.w!==p.w||n.h!==p.h)throw Error('Global mutation '+n.key);count++;}const boxes=AdaptivePyramid.metrics.labelBoxes;for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)if(PyramidLabels.overlaps(boxes[i],boxes[j],0))throw Error('Overview label collision');return count;});assert.equal(immutable,3955);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight));
 fs.writeFileSync(out+'/browser-results.json',JSON.stringify({viewport:[1440,900],scenes:results,movements,screenshots:shots,browserMeasuredChecks:realMeasurements.map(({options,durationMs,checks})=>({options,durationMs,checks})),globalEntityComparisons:immutable,globalDisplacement:0,highlightLayoutCalls:0,stylingLayoutCalls:0,errors,external,checks:'PASS explicit selection, filters, focus anchor, collapse/search, navigation, repeatability, browser-measured geometry, no overflow/storage/external requests'},null,2)+'\n');console.log(JSON.stringify({scenes:results,movement:movements.map(({mode,step,movement,anchorDelta})=>({mode,step,existing:movement.existing,moved:movement.moved,median:movement.median,max:movement.max,anchorDelta})),screenshots:shots.length,checks:'PASS'},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
