const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 try{const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto('http://127.0.0.1:8765/prototypes/adaptive-pyramid/');await page.waitForFunction(()=>window.AdaptivePyramid);
 const result={viewport:[1440,900],focus:[]};let calls=await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls);
 for(const key of ['category:35','topic:15']){await page.evaluate(key=>AdaptivePyramid.focus(key),key);result.focus.push(await page.evaluate(()=>({key:AdaptivePyramid.state().selected,durationMs:AdaptivePyramid.metrics.focusMs,camera:AdaptivePyramid.state().cam})));assert.equal(await page.evaluate(()=>AdaptivePyramid.metrics.layoutCalls),calls);}
 await page.locator('#branch').selectOption('category:35');assert.equal(await page.evaluate(()=>AdaptivePyramid.selection().topics.size),31);await page.locator('#compact').click();const branch=await page.evaluate(()=>({topics:[...AdaptivePyramid.selection().topics],expected:[...AdaptiveCore.selection(AdaptivePyramid.m,{mode:'learned',branch:'category:35'}).topics],calls:AdaptivePyramid.metrics.layoutCalls}));assert.deepEqual(branch.topics,branch.expected);assert.equal(branch.calls,calls+1);result.branchFilter={topics:branch.topics.length,confirmationRequired:true};
 await page.evaluate(()=>AdaptivePyramid.setOptions({mode:'accepted',branch:null}));await page.locator('#search').fill('reference:36');await page.locator('#search').press('Enter');assert.equal(await page.evaluate(()=>AdaptivePyramid.state().selected),'topic:36');assert.equal(await page.locator('#details button').count(),2);result.secondaryMembershipsAccessible=2;
 await page.evaluate(()=>AdaptivePyramid.setOptions({mode:'fixture:growth-branch',step:0,branch:null}));await page.locator('#animate').check();await page.locator('#next-step').click();assert.equal(await page.evaluate(()=>AdaptivePyramid.metrics.animationMs),180);await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#next-step').click();assert.equal(await page.evaluate(()=>AdaptivePyramid.metrics.animationMs),0);result.animation={optionalMs:180,reducedMotionMs:0,type:'fade at validated final coordinates'};
 result.checks='PASS focus timing / no layout, confirmed branch filter, aliases / secondary memberships, optional fade / reduced motion';fs.writeFileSync(__dirname+'/navigation-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
