const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require('/home/anton/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const prefix='http://127.0.0.1:8780/',source=prefix+'prototypes/knowledge-atlas-v6/',baselineUrl=prefix+'docs/knowledge-atlas-preview/',out=__dirname,checks=[],runs=[];
const spatial=fs.readFileSync(out+'/../spatial.cjs','utf8'),geometrySource=spatial.slice(spatial.indexOf('function geometry('),spatial.indexOf('\n(async()=>'));
function pathOracle(){
 const s=AtlasV6.state(),m=s.m,L=s.L;let sameTray=0,crossCategory=0,crossMajor=0;
 const ancestors=key=>{const a=[];for(let n=m.nodes.get(key);n;n=n.canonical_parent_id==null?null:m.nodes.get('category:'+n.canonical_parent_id))a.push(n.key);return a};
 const contains=(p,a,b)=>Math.abs((b.x-a.x)*(p.y-a.y)-(b.y-a.y)*(p.x-a.x))<1e-6&&p.x>=Math.min(a.x,b.x)-1e-6&&p.x<=Math.max(a.x,b.x)+1e-6&&p.y>=Math.min(a.y,b.y)-1e-6&&p.y<=Math.max(a.y,b.y)+1e-6;
 const routes=[];for(const e of m.connections){
  const a=ancestors(e.source),b=ancestors(e.target),common=a.filter(k=>b.includes(k)),lca=common[0],path=[...a.slice(0,a.indexOf(lca)+1),...b.slice(0,b.indexOf(lca)).reverse()],r=s.relationIndex.route(e),same=m.nodes.get(e.source).canonical_parent_id===m.nodes.get(e.target).canonical_parent_id;
  if(JSON.stringify(path)!==JSON.stringify(r.path)||r.lca!==lca||r.source!==e.source||r.target!==e.target||JSON.stringify(a)!==JSON.stringify(r.sourceAncestors)||JSON.stringify(b)!==JSON.stringify(r.targetAncestors))throw Error('LCA/endpoints/ancestor mismatch '+e.key);
  const physical=[];for(let i=1;i<path.length;i++){const x=m.nodes.get(path[i-1]),y=m.nodes.get(path[i]),parent=x.canonical_parent_id===y.id&&y.type==='category'?y:x,child=parent===y?x:y;
   if(child.canonical_parent_id!==parent.id||parent.type!=='category')throw Error('Noncanonical step '+e.key);
   const pn=L.byKey.get(parent.key),tn=child.type==='topic'?L.trays.find(t=>t.topics.includes(child.key)):L.byKey.get(child.key),target=child.type==='topic'?{x:tn.x+tn.width/2,y:tn.y}:{x:tn.x,y:tn.y},start={x:pn.x,y:pn.y+pn.height},bus=start.y+AtlasLayout.LAYOUT.parentToBus;
   physical.push(start.x===target.x?[start,target]:[start,{x:start.x,y:bus},{x:target.x,y:bus},target]);
  }
  const expected=same?[]:L.connectorSegments.flatMap((segment,id)=>physical.some(ps=>ps.slice(1).some((p,i)=>contains(segment.points[0],ps[i],p)&&contains(segment.points[1],ps[i],p)))?[id]:[]);
  if(JSON.stringify([...r.segmentIds].sort((a,b)=>a-b))!==JSON.stringify(expected))throw Error('Foreign/missing physical segment '+e.key+' actual '+JSON.stringify(r.segmentIds)+' expected '+JSON.stringify(expected)+' path '+JSON.stringify(path));
  if(r.sameTray!==same)throw Error('Same-tray mismatch '+e.key);
  if(same){sameTray++;if(r.segmentIds.length)throw Error('External same tray loop')}else crossCategory++;
  if(a.at(-2)!==b.at(-2))crossMajor++;
  routes.push({key:e.key,source:e.source,target:e.target,lca,path,sameTray:same,segments:r.segmentIds});
 }
 return{pairs:m.connections.length,records:m.raw.edges.filter(e=>['prerequisite','dependent'].includes(e.type)).length,sameTray,crossCategory,crossMajor,routes};
}
(async()=>{
 const browser=await chromium.launch({executablePath:'/opt/google/chrome/chrome'}),bp=await browser.newPage();await bp.goto(baselineUrl);await bp.waitForFunction(()=>window.AtlasV6);
 const snapshot=()=>{const s=AtlasV6.state();return{coords:s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height]),checkpoint:JSON.stringify(s.L.checkpoint),segments:s.L.connectorSegments.map(e=>e.d),semantics:JSON.stringify(s.m.connections)}};
 const baseline=await bp.evaluate(snapshot);await bp.evaluate(()=>AtlasV6.select('project:113'));const amber=await bp.evaluate(()=>[...document.querySelectorAll('.taxonomy.covered')].map(e=>e.getAttribute('d')).sort());await bp.close();
 const check=(name,ok)=>{assert(ok,name);checks.push(name)};let oracle;
 for(const width of [1920,1440,1280,1200,1024,768,430,390,320])for(const theme of ['dark','light']){
  const p=await browser.newPage({viewport:{width,height:width===1920?1080:width<=430?844:900},hasTouch:width<=430,isMobile:width<=430}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(source);await p.waitForFunction(()=>window.AtlasV6);await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(t=>document.body.classList.toggle('light',t==='light'),theme);
  assert.deepEqual(await p.evaluate(snapshot),baseline);check('135 bounds/checkpoint/segments/semantics identical '+width+' '+theme,true);
  await p.evaluate(()=>{window.initialLayout=AtlasV6.state().L;window.layoutCalls=0;const build=AtlasLayout.build;AtlasLayout.build=(...args)=>{window.layoutCalls++;return build(...args)};});
  const geom=await p.evaluate(src=>eval('('+src+')')(AtlasV6.state().L),geometrySource);for(const k of ['overlaps','hits','crossings','safeHits','spacingErrors','regionErrors','trayPortErrors'])check(k+' zero',geom[k].length===0);check('exact hierarchy ports',geom.ports);
  check('full taxonomy no selection/no relations',await p.evaluate(()=>document.querySelectorAll('.node.topic').length===89&&document.querySelectorAll('.node.category').length===46&&!document.querySelector('.relation-path')&&!document.querySelector('.knowledge')));
  if(!oracle){oracle=await p.evaluate(pathOracle);check('137 directed pairs retain all 274 records',oracle.pairs===137&&oracle.records===274);check('real local/cross-category/cross-major cases',oracle.sameTray>0&&oracle.crossCategory>0&&oracle.crossMajor>0);fs.writeFileSync(out+'/path-results.json',JSON.stringify(oracle,null,2)+'\n');}
  const ids=await p.evaluate(()=>Object.fromEntries(['For loop','Types and variables','Conditional statement','Writing first program','IntelliJ IDEA','IDE','Basics'].map(t=>[t,[...AtlasV6.state().m.nodes.values()].find(n=>n.title.toLowerCase()===t.toLowerCase()).key])));
  await p.fill('#search','For loop');await p.press('#search','Enter');
  check('Topic Focus 16px',await p.evaluate(()=>AtlasV6.state().transform.k*14>=15.99&&AtlasV6.state().viewState==='topic'));
  check('For loop all 2+2 direct relations',await p.evaluate(()=>{const s=AtlasV6.state();return s.relationProjection.routes.length===4&&s.relationProjection.routes.filter(r=>r.type==='prerequisite').length===2&&document.querySelectorAll('[data-relation]').length===4}));
  const camera=()=>p.evaluate(()=>{const t=AtlasV6.state().transform;return[t.x,t.y,t.k]});let cam=await camera();
  const verify=()=>p.evaluate(()=>{const s=AtlasV6.state(),expected=new Set(s.relationProjection.segments.keys()),els=[...document.querySelectorAll('.taxonomy.relation-path')],actual=els.map(e=>Number(e.dataset.segment));return actual.length===expected.size&&actual.every(id=>expected.has(id))&&new Set(els.map(e=>e.getAttribute('d'))).size===els.length&&!document.querySelector('.knowledge')&&document.querySelectorAll('.taxonomy').length===s.L.connectorSegments.length});
  check('existing segments only / dedup',await verify());
  const relationKeys=await p.locator('[data-relation]').evaluateAll(bs=>bs.map(b=>b.dataset.relation));
  for(const key of relationKeys){await p.locator('#search').focus();const item=p.locator('[data-relation="'+key+'"]');await item.hover();check('hover exactly one strong route',await p.evaluate(k=>{const s=AtlasV6.state(),r=s.relationProjection.routes.find(r=>r.key===k),strong=[...document.querySelectorAll('.taxonomy.relation-strong')].map(e=>Number(e.dataset.segment));return s.relationProjection.focused.key===k&&strong.length===r.segmentIds.length&&strong.every(i=>r.segmentIds.includes(i))},key));assert.deepEqual(await camera(),cam);check('hover dedup',await verify());await p.mouse.move(1,1);await p.waitForFunction(()=>!AtlasV6.state().previewRelation);check('hover clears unpinned preview',await p.evaluate(()=>!AtlasV6.state().previewRelation));await item.click();check('click locks route / preserves selected',await p.evaluate(({k,selected})=>AtlasV6.state().focusedRelation.key===k&&AtlasV6.state().selected===selected,{k:key,selected:ids['For loop']}));assert.equal(await item.getAttribute('aria-pressed'),'true');assert.deepEqual(await camera(),cam);await item.press('Escape');check('Escape restores all direct relations',await p.evaluate(()=>!AtlasV6.state().focusedRelation&&!AtlasV6.state().relationProjection.focused));}
  const first=p.locator('[data-relation]').first();await first.focus();check('keyboard focus previews route',await p.evaluate(()=>!!AtlasV6.state().previewRelation));await first.press('Enter');const focused=await p.evaluate(()=>AtlasV6.state().focusedRelation);await p.click('#roadmap');await p.click('#my');await p.click('#theme');await p.click('#theme');assert.deepEqual(await p.evaluate(()=>AtlasV6.state().focusedRelation),focused);assert.deepEqual(await camera(),cam);check('mode/theme preserve relation and viewport',true);
  check('hollow/filled markers + labels',await p.evaluate(()=>!!document.querySelector('.relation-endpoint.prerequisite')&&!!document.querySelector('.relation-endpoint.dependent')&&[...document.querySelectorAll('[data-relation]')].every(b=>/^(Prerequisite|Dependent): /.test(b.getAttribute('aria-label')))));
  if(width<=430){await first.tap();check('mobile tap locks focused relation',await p.evaluate(()=>!!AtlasV6.state().focusedRelation));assert.deepEqual(await camera(),cam);}
  if(width===1920&&theme==='dark'){await p.evaluate(()=>AtlasV6.focusRelation(null));await p.evaluate(k=>{AtlasV6.select(k,true);AtlasV6.select('topic:89');AtlasV6.fitSubtree(k,false)},ids.Basics);await p.screenshot({path:out+'/1920-basics-all-relations.png'});const cross=await p.evaluate(()=>AtlasV6.state().relationProjection.routes.find(r=>!r.sameTray&&r.type==='prerequisite').key);await p.evaluate(k=>AtlasV6.focusRelation(k),cross);await p.screenshot({path:out+'/1920-basics-focused-prerequisite.png'});}
  if(width===390&&theme==='dark'){await p.screenshot({path:out+'/390-topic-focused.png',fullPage:true});}
  for(const title of ['Types and variables','Conditional statement','Writing first program','IntelliJ IDEA']){await p.evaluate(k=>AtlasV6.select(k),ids[title]);check('real Topic '+title,await verify());}
  await p.evaluate(k=>AtlasV6.select(k,true),ids.IDE);check('IDE is real category; category focus has no relations',await p.evaluate(()=>AtlasV6.state().m.nodes.get(AtlasV6.state().selected).type==='category'&&!document.querySelector('.relation-path')));
  await p.evaluate(()=>AtlasV6.select('project:113'));check('Project 113 exact 26',await p.locator('.node.topic.covered').count()===26);assert.deepEqual(await p.locator('.taxonomy.covered').evaluateAll(es=>es.map(e=>e.getAttribute('d')).sort()),amber);
  await p.locator('[data-stage]').filter({hasText:'Stage 4'}).click();check('Stage 4 exact 12',await p.locator('.node.topic.covered').count()===12);const stageSegments=await p.locator('.taxonomy.covered').evaluateAll(es=>es.map(e=>e.getAttribute('d')).sort());await p.evaluate(k=>AtlasV6.select(k),ids['For loop']);check('coverage + selected topic retain 12',await p.locator('.node.topic.covered').count()===12);assert.deepEqual(await p.locator('.taxonomy.covered').evaluateAll(es=>es.map(e=>e.getAttribute('d')).sort()),stageSegments);await p.locator('[data-relation]').last().click();check('project + relation priority uses exact route',await verify());
  // Explicit computed color/opacity check (CSS variables resolve to RGB on SVG).
  check('project + relation remains visibly distinct',await p.evaluate(()=>{const e=document.querySelector('.taxonomy.covered:not(.relation-path)'),r=document.querySelector('.taxonomy.relation-strong');return(!e||Number(getComputedStyle(e).strokeOpacity)<=.22)&&(!r||Number(getComputedStyle(r).strokeOpacity)===1)&&getComputedStyle(document.querySelector('.evidence')).opacity==='0.35'}));
  check('relation card colors override amber without changing coverage',await p.evaluate(()=>{const swatch=document.createElement('span');document.body.append(swatch);const color=name=>{swatch.style.color=getComputedStyle(document.body).getPropertyValue(name);return getComputedStyle(swatch).color};const colors={prerequisite:color('--prerequisite'),dependent:color('--dependent'),shared:color('--relation-shared')};swatch.remove();return [...document.querySelectorAll('.node.relation-path .card')].every(c=>{const n=c.parentNode,type=n.classList.contains('relation-shared')?'shared':n.classList.contains('relation-prerequisite')?'prerequisite':'dependent';return getComputedStyle(c).stroke===colors[type]})}));
  if(width===1440&&theme==='light')await p.screenshot({path:out+'/1440-light-project-topic.png'});
  await p.click('#fit');check('Overview with selected Topic only direct routes',await verify());await p.click('#clear');check('unselected Overview no knowledge routes',await p.evaluate(()=>!document.querySelector('.relation-path')&&!document.querySelector('.knowledge')));
  check('no layout calls / same object',await p.evaluate(()=>window.layoutCalls===0&&AtlasV6.state().L===window.initialLayout));assert.deepEqual(await p.evaluate(snapshot),baseline);
  check('labels retained / no overflow / Inspector responsive',await p.evaluate(()=>[...document.querySelectorAll('.node .label')].every(e=>getComputedStyle(e).display!=='none'&&Number(getComputedStyle(e).opacity)>0)&&document.documentElement.scrollWidth<=innerWidth&&(innerWidth>1200?document.querySelector('aside').getBoundingClientRect().left>=document.querySelector('#graph').getBoundingClientRect().right:document.querySelector('aside').getBoundingClientRect().top>=document.querySelector('#graph').getBoundingClientRect().bottom)));
  assert.deepEqual(errors,[]);runs.push({width,theme,errors,geometry:geom,metrics:await p.evaluate(()=>AtlasV6.state().metrics),samples:await p.evaluate(()=>AtlasV6.state().samples)});await p.close();
 }
 const all=await browser.newPage();await all.goto(source);await all.waitForFunction(()=>window.AtlasV6);await all.emulateMedia({reducedMotion:'reduce'});check('all 89 Topic selections have dedup taxonomy routes',await all.evaluate(()=>{for(const n of AtlasV6.state().m.nodes.values()){if(n.type!=='topic')continue;AtlasV6.select(n.key);if(document.querySelector('.knowledge'))return false;const expected=AtlasV6.state().relationProjection.segments,els=[...document.querySelectorAll('.taxonomy.relation-path')];if(els.length!==expected.size||els.some(e=>!expected.has(Number(e.dataset.segment))))return false;}return true}));await all.close();
 fs.writeFileSync(out+'/browser-results.json',JSON.stringify({checks,runs,routeCases:{sameTray:oracle.sameTray,crossCategory:oracle.crossCategory,crossMajor:oracle.crossMajor},physicalDevices:'not tested'},null,2)+'\n');console.log('PASS',checks.length,'checks /',runs.length,'width-theme configurations; routes',oracle.sameTray,oracle.crossCategory,oracle.crossMajor);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
