const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require('/home/anton/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const url='http://127.0.0.1:8780/prototypes/knowledge-atlas-v6/',checks=[];
(async()=>{const b=await chromium.launch({executablePath:'/opt/google/chrome/chrome'});
const p=await b.newPage({viewport:{width:1920,height:1080}});await p.goto(url);await p.waitForFunction(()=>window.AtlasV6);await p.fill('#search','For loop');await p.press('#search','Enter');await p.waitForFunction(()=>!AtlasV6.state().transitioning);assert(await p.evaluate(()=>AtlasV6.state().transform.k*14>=15.99));checks.push('normal animated search retains 16px focus');
await p.fill('#search','Java');await p.press('#search','Enter');await p.fill('#search','For loop');await p.press('#search','Enter');await p.waitForFunction(()=>!AtlasV6.state().transitioning);assert(await p.evaluate(()=>AtlasV6.state().viewState==='topic'&&AtlasV6.state().transform.k*14>=15.99));checks.push('interrupted navigation works with relation highlights');
await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>{const s=AtlasV6.state();window.relationSnapshot={L:s.L,coords:JSON.stringify(s.L.nodes.map(n=>[n.key,n.x,n.y,n.width,n.height])),cp:JSON.stringify(s.L.checkpoint)}});
const k=await p.evaluate(()=>AtlasV6.state().relationProjection.routes.find(r=>!r.sameTray).key);await p.evaluate(key=>{const r=AtlasV6.state().relationProjection.routes.find(r=>r.key===key),n=AtlasV6.state().m.nodes.get(r.counterpart);AtlasV6.toggle('category:'+n.canonical_parent_id)},k);const folded=await p.evaluate(()=>[...AtlasV6.state().collapsed]);await p.evaluate(k=>AtlasV6.focusRelation(k),k);assert.deepEqual(await p.evaluate(()=>[...AtlasV6.state().collapsed]),folded);assert(await p.evaluate(()=>!document.querySelector('.knowledge')&&AtlasV6.state().L===window.relationSnapshot.L&&JSON.stringify(AtlasV6.state().L.checkpoint)===window.relationSnapshot.cp));checks.push('relation focus preserves manual collapse and frozen layout');
await p.evaluate(()=>{for(const k of [...AtlasV6.state().collapsed])AtlasV6.toggle(k);const e=AtlasV6.state().m.connections.find(e=>{const a=AtlasV6.state().relationIndex.chain(e.source),b=AtlasV6.state().relationIndex.chain(e.target);return a.at(-2)!==b.at(-2)});AtlasV6.select(e.source);AtlasV6.focusRelation(e.key);AtlasV6.fit(null,false)});assert(await p.evaluate(()=>AtlasV6.state().relationProjection.focused.lca===AtlasV6.state().m.root.key&&document.querySelectorAll('.taxonomy.relation-strong').length===AtlasV6.state().relationProjection.focused.segmentIds.length));await p.screenshot({path:__dirname+'/1920-cross-major-overview.png'});checks.push('real cross-major relation uses root LCA');await p.close();
for(const width of [430,390,320]){const p=await b.newPage({viewport:{width,height:844},hasTouch:true,isMobile:true});await p.goto(url);await p.waitForFunction(()=>window.AtlasV6);await p.emulateMedia({reducedMotion:'reduce'});await p.fill('#search','For loop');await p.press('#search','Enter');await p.locator('[data-relation]').last().tap();const before=await p.evaluate(()=>{const s=AtlasV6.state();return{coords:JSON.stringify(s.L.nodes.map(n=>[n.key,n.x,n.y])),cp:JSON.stringify(s.L.checkpoint),focus:s.focusedRelation.key,k:s.transform.k}});await p.locator('#graph').scrollIntoViewIfNeeded();const c=await p.context().newCDPSession(p),r=await p.locator('#graph').boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;
await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-30,y,id:1},{x:x+30,y,id:2}]});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-60,y,id:1},{x:x+60,y,id:2}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await p.evaluate(k=>AtlasV6.state().transform.k>k,before.k));const previous=await p.evaluate(()=>AtlasV6.state().transform.x);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:3}]});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+30,y:y+20,id:3}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await p.evaluate(x=>AtlasV6.state().transform.x!==x,previous));assert(await p.evaluate(b=>{const s=AtlasV6.state();return JSON.stringify(s.L.nodes.map(n=>[n.key,n.x,n.y]))===b.coords&&JSON.stringify(s.L.checkpoint)===b.cp&&s.focusedRelation.key===b.focus&&!document.querySelector('.knowledge')&&document.documentElement.scrollWidth<=innerWidth},before));checks.push('touch pinch/pan with focused relation '+width);await p.close();}
fs.writeFileSync(__dirname+'/interaction-results.json',JSON.stringify({checks,physicalTests:'not performed'},null,2)+'\n');console.log('PASS',checks.length,'additional navigation/collapse/touch checks');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
