const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{performance}=require('node:perf_hooks');
const root=path.resolve(__dirname,'../../..'),prod=root+'/docs/knowledge-map',ctx=vm.createContext({performance}),check=require('../layout-refinement-tests/invariants.cjs');
// Execute the actual published UMD bytes with browser globals, avoiding Node-only relative adapters.
for(const n of ['atlas.js','labels.js','adaptive.cjs','registry.cjs','views.cjs'])vm.runInContext(fs.readFileSync(prod+'/'+n,'utf8'),ctx,{filename:n});
const A=ctx.AdaptiveCore,R=ctx.AtlasRegistry,V=ctx.AtlasViews,raw=JSON.parse(fs.readFileSync(prod+'/model.json')),geometry=JSON.parse(fs.readFileSync(prod+'/global-reference.json')),m=R.index(raw,geometry),before=JSON.stringify(geometry),measure=(s,f)=>s.length*(f.includes('15px')?7.6:f.includes('14px')?7.1:5.5);
assert.equal(new Set(raw.entities.map(e=>e.key)).size,raw.entities.length);assert.equal(m.entities.size,3955);
const learned=new Set(raw.progress.filter(r=>r.is_learned===true).map(r=>'topic:'+r.topic_id)),visible=new Set(learned);
for(const key of learned){let n=m.nodes.get(key);while(n.parent){visible.add(n.parent);n=m.nodes.get(n.parent);}}
const s=A.selection(m,{mode:'learned'});assert.deepEqual([...s.visible].sort(),[...visible].sort());assert.equal(s.topics.size,31);assert.equal(s.visible.size,52);
const scenes=[];for(const options of [{mode:'learned'},{mode:'accepted'},{mode:'course',id:8},{mode:'project',id:113},{mode:'project',id:113,stage:617}]){const scope=A.selection(m,options),l=A.layout(m,scope,{measure});scenes.push({options,topics:scope.topics.size,cards:l.positions.size,...check(m,scope,l)});}
const v=new V.Views(m,measure);v.confirm({mode:'learned'});const calls=v.metrics.layoutCalls,next=structuredClone(raw),addition=next.progress.find(r=>!r.is_learned);next.presentation_fixture=true;addition.is_learned=true;
assert.equal(v.updateSnapshot(next,{reducedMotion:true}),true);assert.equal(v.metrics.layoutCalls,calls+1);assert.equal(v.scope.topics.size,32);check(v.m,v.scope,v.local);assert.equal(JSON.stringify(v.m.geometry),before);
const growth={addedTopic:addition.topic_id,learnedBefore:31,learnedAfter:32,cardsAfter:v.local.positions.size,layoutCalls:1,averageDisplacement:v.metrics.movement.average,maxDisplacement:v.metrics.movement.max,globalReferenceUnchanged:true};
const styling=structuredClone(v.m.raw),record=styling.progress.find(r=>r.is_learned&&!r.is_verified);record.is_verified=true;record.verification_status='verified';const count=v.metrics.layoutCalls,local=v.local,verified=v.scope.verified.size;
assert.equal(v.updateSnapshot(styling,{reducedMotion:true}),false);assert.equal(v.metrics.layoutCalls,count);assert.equal(v.local,local);assert.equal(v.scope.verified.size,verified+1);assert.equal(JSON.stringify(v.m.geometry),before);
const result={status:'PASS',actualProductionBytesExecuted:true,uniqueSemanticEntities:m.entities.size,myKnowledgeTopics:31,myKnowledgeCards:52,scenes,growth,verifiedOnlyNoStructuralRelayout:true,realDataWrites:false};fs.writeFileSync(__dirname+'/focused-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:'PASS',scenes:scenes.map(s=>({options:s.options,topics:s.topics,cards:s.cards,cardOverlaps:s.cardOverlaps,subtreeOverlaps:s.subtreeOverlaps})),growth,verifiedOnlyNoStructuralRelayout:true},null,2));
