/* Frozen-file comparison. Camera transforms only; no layout generation or persistence. */
(async()=>{
'use strict';const $=s=>document.querySelector(s),start=performance.now(),names=['current-geometry','target-geometry','migration-diff','migration-metrics','migration-manifest','semantic-snapshot'];
const [current,target,diff,metrics,manifest,semantic]=await Promise.all(names.map(n=>fetch('../'+n+'.json').then(r=>r.json())));const master=await fetch(target.master_reference).then(r=>r.json());
function freeze(v){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}[current,target,diff,metrics,manifest,semantic,master].forEach(freeze);
const cmap=new Map(current.positions.map(n=>[n.key,n])),tmap=new Map(target.positions.map(n=>[n.key,n])),dmap=new Map(diff.entities.map(n=>[n.key,n])),smap=new Map(master.positions.map(n=>[n.key,n]));
let mode='split',scope='atlas',kind='all',branch='',selected='',rank='all',world=false,frame=null;const cameras={},hitBoxes={},performanceData={};
function bounds(ns){if(!ns.length)return null;const x=Math.min(...ns.map(n=>n.x)),y=Math.min(...ns.map(n=>n.y));return{x,y,w:Math.max(...ns.map(n=>n.x+n.w))-x,h:Math.max(...ns.map(n=>n.y+n.h))-y};}
const rows=()=>diff.entities.filter(n=>{if(kind!=='all'&&n.entity_type!==kind)return false;if(selected)return n.key===selected;if(branch&&!n.current_path.includes(branch)&&!n.target_path.includes(branch))return false;if(scope==='project'||scope==='stage')return semantic.edges.some(e=>e.type==='project_requires'&&e.source==='project:113'&&e.target===n.key&&(scope!=='stage'||e.stage_id===617));if(scope==='course')return semantic.courses.some(c=>c.id===8&&(n.entity_type==='topic'?c.topic_ids:c.category_ids).includes(Number(n.key.split(':')[1])));return true;}).sort((a,b)=>b.displacement-a.displacement||a.key.localeCompare(b.key)).slice(0,selected?1:rank==='all'?135:Number(rank));
function camera(b,w,h){if(!b)return{x:0,y:0,k:1};const k=Math.min(3,(w-40)/Math.max(1,b.w),(h-135)/Math.max(1,b.h));return{k,x:w/2-(b.x+b.w/2)*k,y:55+(h-135)/2-(b.y+b.h/2)*k};}
function resize(){for(const id of ['current','target','overlay']){const c=$('#'+id),r=c.getBoundingClientRect();if(!r.width)continue;c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;}fit();}
function fit(){const t=performance.now(),rr=rows();for(const id of ['current','target','overlay']){const c=$('#'+id),r=c.getBoundingClientRect();if(!r.width)continue;let ns=rr.map(n=>(id==='current'?cmap:tmap).get(n.key));if(id==='overlay')ns=rr.flatMap(n=>[cmap.get(n.key),tmap.get(n.key)]);let b=world&&id==='target'?master.bounds:bounds(ns);if(id==='current'&&!selected&&!branch&&rank==='all'&&kind==='all'&&['atlas','course'].includes(scope))b=current.bounds;cameras[id]=camera(b,r.width,r.height);}performanceData.fitMs=performance.now()-t;schedule();}
function schedule(){if(!frame)frame=requestAnimationFrame(()=>{frame=null;draw();});}
function draw(){const t=performance.now(),rr=rows();for(const id of ['current','target','overlay'])if($('#'+id).getBoundingClientRect().width)render(id,rr);minimap(rr);performanceData.drawMs=performance.now()-t;}
function render(id,rr){const c=$('#'+id),ctx=c.getContext('2d'),W=c.clientWidth,H=c.clientHeight,cam=cameras[id];if(!cam)return;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,W,H);hitBoxes[id]=[];const sx=x=>x*cam.k+cam.x,sy=y=>y*cam.k+cam.y,keys=new Set(rr.map(n=>n.key)),color=id==='current'?'#88c4ff':'#ffca75',labels=[];
 if(id==='overlay'){
  const chosen=rr.slice(0,5);for(const r of chosen){const a=cmap.get(r.key),b=tmap.get(r.key),x=sx(a.x),y=sy(a.y),tx=sx(b.x),ty=sy(b.y);ctx.strokeStyle='#d2b279';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(tx,ty);ctx.stroke();const angle=Math.atan2(ty-y,tx-x);ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx-9*Math.cos(angle-.45),ty-9*Math.sin(angle-.45));ctx.lineTo(tx-9*Math.cos(angle+.45),ty-9*Math.sin(angle+.45));ctx.closePath();ctx.fillStyle='#ffca75';ctx.fill();for(const [n,clr]of [[a,'#88c4ff'],[b,'#ffca75']]){ctx.fillStyle=clr;ctx.beginPath();ctx.arc(sx(n.x),sy(n.y),5,0,Math.PI*2);ctx.fill();}labels.push({x,y:y-30,text:'Current · '+a.title,key:r.key,priority:0},{x:tx,y:ty-30,text:'Target · '+b.title,key:r.key,priority:0});}
  ctx.fillStyle='#aac1d8';ctx.font='12px system-ui';ctx.fillText(`${chosen.length} vectors · ${rr.length} matched entities · raw world origins`,12,H-15);performanceData.vectors=chosen.length;
 }else{
  const map=id==='current'?cmap:tmap,context=new Set(rr.flatMap(r=>(id==='current'?cmap.get(r.key):tmap.get(r.key)).path));
  const ns=id==='current'?current.positions:master.positions;
  if(id==='current'){for(const tray of current.native_geometry.trays){if(!tray.topics.some(k=>keys.has(k)))continue;ctx.fillStyle='#17283b';ctx.fillRect(sx(tray.x),sy(tray.y),tray.width*cam.k,tray.height*cam.k);}}
  else for(const s of master.root_sectors){const root=smap.get(s.root);ctx.fillStyle='#15253b50';ctx.beginPath();ctx.moveTo(sx(root.x+root.w/2),sy(root.y));ctx.lineTo(sx(s.x+s.w),sy(s.y+s.h));ctx.lineTo(sx(s.x),sy(s.y+s.h));ctx.closePath();ctx.fill();}
  const routes=id==='current'?current.routes:master.hierarchy_routes;for(const route of routes){const relevant=id==='current'?context.has(route.parent)||route.children.some(k=>context.has(k)):context.has(route.child);ctx.strokeStyle=relevant?color+'aa':'#50668120';ctx.lineWidth=relevant?1.1:.6;ctx.beginPath();route.points.forEach((p,i)=>i?ctx.lineTo(sx(p[0]),sy(p[1])):ctx.moveTo(sx(p[0]),sy(p[1])));ctx.stroke();}
  const topicKey=n=>n.key.startsWith('leaf:')?'topic:'+n.key.split(':')[1]:n.key;let objects=0;
  for(const n of ns){const key=id==='current'?n.key:topicKey(n),active=keys.has(key),isContext=context.has(n.key),x=sx(n.x),y=sy(n.y),w=n.w*cam.k,h=n.h*cam.k;if(x+w<0||y+h<40||x>W||y>H-75)continue;if(id==='current'&&!active&&!isContext)continue;ctx.globalAlpha=active?1:isContext?.4:.08;ctx.fillStyle=active?color:'#8295ac';if(w<8||h<6){ctx.beginPath();ctx.arc(x+w/2,y+h/2,active?2.5:1,0,Math.PI*2);ctx.fill();}else{ctx.beginPath();ctx.roundRect(x,y,w,h,Math.min(6,h/4));ctx.fill();}if(active){const row=semantic.progress.topics.filter(p=>p.topic_id===Number(key.split(':')[1]));if(key.startsWith('topic:')&&row.some(p=>p.is_learned)){ctx.fillStyle='#4de1ad';ctx.beginPath();ctx.arc(x+w/2,y+h/2,2.5,0,Math.PI*2);ctx.fill();}if(key.startsWith('topic:')&&row.some(p=>p.is_verified)){ctx.strokeStyle='#fff';ctx.beginPath();ctx.arc(x+w/2,y+h/2,4,0,Math.PI*2);ctx.stroke();}hitBoxes[id].push({x,y,w:Math.max(8,w),h:Math.max(8,h),key});}objects++;
   const fact=map.get(key);const rootLabel=id==='target'&&world&&n.depth===0;const text=fact?.title||(rootLabel?semantic.categories.find(c=>'category:'+c.id===n.key)?.title||({'category:525':'Math','category:2148':'Natural science','category:3051':'Product development','category:4055':'Generative AI'}[n.key]):null);
   if(!rootLabel&&text&&(key===selected||(active||isContext)&&((n.depth<=2&&n.key.startsWith('category:'))||w>100&&h>25)))labels.push({x:x+w/2,y:y-25,text,key,rootLabel,fixedY:rootLabel?Math.max(45,y-60):null,labelWidth:rootLabel?Math.max(55,Math.min(170,master.root_sectors.find(s=>s.root===n.key).w*cam.k-26)):null,priority:key===selected?0:rootLabel?1:n.depth<3?2:3});
  }
  ctx.globalAlpha=1;ctx.font='12px system-ui';ctx.fillStyle='#a9c0d5';ctx.fillText(`${rr.length} matched · ${objects} drawn marks · exact ${id==='current'?'V6 rectangles + trays':'canonical slots'}`,12,H-15);$('#'+id+'-zoom').textContent=`· ${(cam.k*100).toFixed(cam.k<.01?2:0)}% camera`;performanceData[id+'Objects']=objects;
 }
 const rootNames={'category:1162':'Computer science','category:525':'Math','category:2148':'Natural science','category:3051':'Product development','category:4055':'Generative AI'};
 const a=master.presentation_super_root,topLabels=id==='target'&&world?PyramidLabels.topLevel(ctx,{width:W,height:H,top:45,bottom:95,
  apex:{key:a.key,anchorX:sx(a.x+a.w/2),anchorY:sy(a.y+a.h/2)},
  roots:master.root_sectors.map(s=>{const n=smap.get(s.root);return {key:n.key,text:rootNames[n.key],anchorX:sx(n.x+n.w/2),anchorY:sy(n.y+n.h/2),sectorWidth:s.w*cam.k};})}):[];
 const labelStart=performance.now(),occupied=[...topLabels];for(const l of labels.sort((a,b)=>a.priority-b.priority||a.key.localeCompare(b.key))){if(occupied.length>=35)break;ctx.font='12px system-ui';const lines=PyramidLabels.wrap(l.text,s=>ctx.measureText(s).width,l.labelWidth??Math.min(290,W-40),4).lines,w=Math.max(...lines.map(s=>ctx.measureText(s).width))+16,h=lines.length*16+10;let b={x:Math.max(8,Math.min(W-w-8,l.x-w/2)),y:l.fixedY??Math.max(45,Math.min(H-95-h,l.y-h)),w,h};if(occupied.some(a=>PyramidLabels.overlaps(a,b)))continue;occupied.push(b);ctx.globalAlpha=1;if(l.rootLabel){ctx.strokeStyle='#71869d';ctx.beginPath();ctx.moveTo(l.x,l.y+25);ctx.lineTo(Math.max(b.x,Math.min(b.x+b.w,l.x)),b.y+b.h);ctx.stroke();}ctx.fillStyle='#0c1929f2';ctx.fillRect(b.x,b.y,w,h);ctx.fillStyle='#e3edf8';lines.forEach((s,i)=>ctx.fillText(s,b.x+8,b.y+17+i*16));hitBoxes[id].push({...b,key:l.key});}PyramidLabels.paintTopLevel(ctx,topLabels);performanceData[id+'TopLevelLabels']=topLabels;performanceData[id+'LabelMs']=performance.now()-labelStart;
}
function minimap(rr){const c=$('#bounds-mini'),ctx=c.getContext('2d');ctx.clearRect(0,0,270,130);for(const [id,b,ox]of [['current',current.bounds,8],['target',master.bounds,140]]){const W=120,H=88,x=v=>ox+(v-b.x)/b.w*W,y=v=>25+(v-b.y)/b.h*H;ctx.strokeStyle='#678098';ctx.strokeRect(ox,25,W,H);ctx.font='11px system-ui';ctx.fillStyle='#c0d1e3';ctx.fillText(`${id==='current'?'V6':'Global'} · ${b.w.toLocaleString('en-US')} width`,ox,14);ctx.save();ctx.beginPath();ctx.rect(ox,25,W,H);ctx.clip();const ns=id==='current'?current.positions:master.positions;ctx.fillStyle='#7590ab';for(const n of ns)ctx.fillRect(x(n.x),y(n.y),1,1);const scopeBounds=bounds(rr.map(n=>(id==='current'?cmap:tmap).get(n.key)));if(scopeBounds){ctx.strokeStyle='#ffca75';ctx.strokeRect(x(scopeBounds.x),y(scopeBounds.y),Math.max(2,scopeBounds.w/b.w*W),Math.max(2,scopeBounds.h/b.h*H));}const cam=cameras[id],canvas=$('#'+id);if(cam&&canvas.clientWidth){ctx.strokeStyle='#fff';ctx.strokeRect(x(-cam.x/cam.k),y(-cam.y/cam.k),canvas.clientWidth/cam.k/b.w*W,canvas.clientHeight/cam.k/b.h*H);}ctx.restore();}}
function update(fitting=true){const rr=rows();$('#context').textContent=`${scope==='stage'?'Stage 617 · 12 explicit requirements':scope==='project'?'Project 113 · 26 explicit requirements':scope==='course'?'Course 8 · 135 explicit members':'My Atlas · 46 Categories + 89 Topics'} · ${rr.length} matched in filter · ${selected?'entity focus':branch?'branch focus':'overview'} · geometry frozen`;
 $('#summary').textContent='135/135 mapped · 31 learned · 12 verified · Generation 0 unchanged. All 135 positions move once; no semantic changes.';
 const d=selected?dmap.get(selected):rr[0],div=$('#details');div.replaceChildren();if(d){const h=document.createElement('h3');h.textContent=(selected?'Selected: ':'Largest in filter: ')+cmap.get(d.key).title;div.append(h);const dl=document.createElement('dl');for(const [title,value]of [['Identity',d.key+' → '+d.target_slot],['One-time left/top displacement',d.displacement.toLocaleString('en-US',{maximumFractionDigits:2})+' world units'],['Delta x / y',d.delta_x.toFixed(2)+' / '+d.delta_y.toFixed(2)],['Current rectangle',`${d.current_x}, ${d.current_y} · ${d.current_width} × ${d.current_height}`],['Target exact master rectangle',`${d.target_x}, ${d.target_y} · ${d.target_width} × ${d.target_height}`],['Current layout parent',cmap.get(d.key).parent||'none'],['Target primary layout parent',d.target_global_parent||'presentation anchor'],['Semantic identity / learning','UNCHANGED'],['After migration future reveal','0 px movement of existing entities']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=title;dd.textContent=value;dl.append(dt,dd);}div.append(dl);}if(fitting)fit();else schedule();}
function setMode(value){mode=value;$('#world-mini').hidden=mode==='overlay';for(const b of document.querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',String(b.dataset.mode===mode));$('#current-pane').hidden=!['current','split'].includes(mode);$('#target-pane').hidden=!['target','split'].includes(mode);$('#overlay-pane').hidden=mode!=='overlay';resize();}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>setMode(b.dataset.mode);
for(const n of current.positions.filter(n=>n.type==='category').sort((a,b)=>a.title.localeCompare(b.title)))$('#branch').add(new Option(n.title,n.key));for(const n of [...current.positions].sort((a,b)=>a.title.localeCompare(b.title)))$('#entity').add(new Option(n.title+' · '+n.key,n.key));
for(const [id,change]of [['scope',v=>scope=v],['type',v=>kind=v],['largest',v=>rank=v],['branch',v=>{branch=v;selected='';$('#entity').value='';}],['entity',v=>selected=v]])$('#'+id).onchange=()=>{change($('#'+id).value);world=false;update();};
$('#fit').onclick=()=>{world=false;fit();};$('#world').onclick=()=>{world=true;if(mode==='current'||mode==='overlay')setMode('target');fit();};
function clear(){scope='atlas';kind='all';rank='all';branch='';selected='';world=false;for(const [id,value]of [['scope','atlas'],['type','all'],['largest','all'],['branch',''],['entity','']])$('#'+id).value=value;update();}
$('#clear').onclick=clear;document.addEventListener('keydown',e=>{if(e.key==='Escape'){selected='';$('#entity').value='';world=false;update();}});
for(const id of ['current','target','overlay']){const c=$('#'+id);let drag=null;c.onwheel=e=>{e.preventDefault();const b=c.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top,cam=cameras[id],k=Math.max(.0001,Math.min(8,cam.k*Math.exp(-e.deltaY*.002)));cam.x=x-(x-cam.x)*k/cam.k;cam.y=y-(y-cam.y)*k/cam.k;cam.k=k;schedule();};c.onpointerdown=e=>{c.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,cam:{...cameras[id]}};};c.onpointermove=e=>{if(drag){cameras[id].x=drag.cam.x+e.clientX-drag.x;cameras[id].y=drag.cam.y+e.clientY-drag.y;schedule();}};c.onpointerup=e=>{if(drag&&Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)<5){const b=c.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top,n=(hitBoxes[id]||[]).find(n=>x>=n.x&&x<=n.x+n.w&&y>=n.y&&y<=n.y+n.h);if(n&&dmap.has(n.key)){selected=n.key;$('#entity').value=selected;update();}}drag=null;};c.onkeydown=e=>{if(e.key.startsWith('Arrow')){e.preventDefault();cameras[id].x+=e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0;cameras[id].y+=e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0;schedule();}};}
window.addEventListener('resize',resize);update();resize();performanceData.initMs=performance.now()-start;
window.MigrationPreview={current,target,master,diff,metrics,manifest,semantic,setMode,fit,clear,rows,state:()=>({mode,scope,kind,branch,selected,rank,cameras:structuredClone(cameras)}),performanceData};
})().catch(e=>{document.querySelector('#context').textContent='MIGRATION_GEOMETRY_CONFLICT · preview failed to load';console.error(e);});
