const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{performance}=require('node:perf_hooks');
const here=__dirname,result=JSON.parse(fs.readFileSync(here+'/pipeline-results.json')),check=require('../layout-refinement-tests/invariants.cjs');
function scene(folder){const ctx=vm.createContext({performance});for(const n of ['atlas.js','labels.js','adaptive.cjs','registry.cjs','views.cjs'])vm.runInContext(fs.readFileSync(folder+'/'+n,'utf8'),ctx);const raw=JSON.parse(fs.readFileSync(folder+'/model.json')),g=JSON.parse(fs.readFileSync(folder+'/global-reference.json')),m=ctx.AtlasRegistry.index(raw,g),scope=ctx.AdaptiveCore.selection(m,{mode:'learned'}),measure=(s,f)=>s.length*(f.includes('15px')?7.6:f.includes('14px')?7.1:5.5),layout=ctx.AdaptiveCore.layout(m,scope,{measure});
assert.equal(m.entities.size,3955);assert.equal(new Set(raw.entities.map(e=>e.key)).size,3955);
const expected=new Set(scope.topics);for(const key of scope.topics){let n=m.nodes.get(key);while(n.parent){expected.add(n.parent);n=m.nodes.get(n.parent);}}assert.deepEqual([...scope.visible].sort(),[...expected].sort());
const invariant=check(m,scope,layout);return{ctx,raw,g,m,scope,layout,measure,invariant};}
function positions(s){return JSON.stringify([...s.layout.positions].map(([k,p])=>[k,p.x,p.y,p.w,p.h]));}
const report={status:'PASS',scenarios:{}};
for(const [name,r] of Object.entries(result.scenarios)){const before=scene(r.disposable_root+'/baseline'),after=scene(r.candidate_path),movement=[];
for(const [k,p]of before.layout.positions){const q=after.layout.positions.get(k);if(q)movement.push(Math.hypot(p.x-q.x,p.y-q.y));}movement.sort((a,b)=>a-b);
assert.equal(JSON.stringify(before.g),JSON.stringify(after.g));assert.deepEqual(before.raw.entities,after.raw.entities);assert.equal(before.scope.topics.size,r.before.learned);assert.equal(after.scope.topics.size,r.after.learned);assert.equal(after.scope.verified.size,r.after.verified);
const v=new before.ctx.AtlasViews.Views(before.m,before.measure);v.confirm({mode:'learned'});const calls=v.metrics.layoutCalls,old=v.local;
const changed=v.updateSnapshot(after.raw,{reducedMotion:true});
if(name==='learned'){assert(after.scope.visible.has('topic:'+result.learned_topic_id));assert.equal(changed,true);assert.equal(v.metrics.layoutCalls,calls+1);}else{assert.equal(positions(before),positions(after));assert.deepEqual([...before.scope.visible].sort(),[...after.scope.visible].sort());assert.equal(changed,false);assert.equal(v.local,old);assert.equal(v.metrics.layoutCalls,calls);}
report.scenarios[name]={learnedBefore:before.scope.topics.size,learnedAfter:after.scope.topics.size,verifiedBefore:before.scope.verified.size,verifiedAfter:after.scope.verified.size,cardsBefore:before.layout.positions.size,cardsAfter:after.layout.positions.size,boundsBefore:before.layout.bounds,boundsAfter:after.layout.bounds,existingCardsMoved:movement.filter(n=>n>1e-9).length,medianMovement:movement.length%2?movement[Math.floor(movement.length/2)]:(movement[movement.length/2-1]+movement[movement.length/2])/2,maxMovement:Math.max(...movement),layoutMs:after.layout.durationMs,globalDisplacementPx:0,structuralRelayout:changed,invariants:after.invariant};}
fs.writeFileSync(here+'/layout-results.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
